/**
 * Arab Batch 2 Group 1A — Syrian / Levantine mains (part 1).
 * Studio draft sources only. Sheikh al-Mahshi skipped (already in Batch 1).
 */

import {
  b2g1Ing,
  b2g1Loc,
  b2g1Photo,
  b2g1Recipe,
} from "./arabBatch2Group1Shared";
import type { GeneratedRecipe } from "./generatedRecipeLibrary";

const BAMIEH: GeneratedRecipe = b2g1Recipe({
  matchKeys: [
    "bamieh bil lahmeh",
    "bamieh bil lahm",
    "bamya bil lahmeh",
    "okra stew with meat",
    "syrian okra stew",
    "بامية باللحمة",
    "بامية باللحم",
  ],
  canonicalTitle: "Bamieh bil Lahmeh",
  prepMinutes: 75,
  difficulty: "medium",
  servings: 3,
  mealTypes: ["main", "stew"],
  mealSlotRole: "dinner_complete",
  mealIntents: ["family_friendly", "budget", "healthy"],
  proteinCategory: "lamb",
  budgetTier: "low",
  suitability: ["everyday_host", "shareable"],
  moods: ["everyday"],
  dietaryTags: ["contains_meat"],
  allergens: [],
  ingredientTokens: ["okra", "lamb", "tomato", "garlic", "onion", "coriander"],
  pantryIngredients: [
    { canonicalId: "okra", role: "critical", tokens: ["okra", "bamieh", "bamya"] },
    { canonicalId: "meat", role: "critical", tokens: ["lamb", "beef", "meat"] },
    { canonicalId: "tomato", role: "supporting", tokens: ["tomato"] },
    { canonicalId: "garlic", role: "supporting", tokens: ["garlic"] },
    { canonicalId: "onion", role: "supporting", tokens: ["onion"] },
  ],
  ingredients: [
    b2g1Ing("okra", "Okra (bamieh)", "Okra (Bamieh)", "بامية", "Bamya", "500 g, trimmed", "500 g, geputzt", "500 غرام، منظّفة", "500 g, ayıklanmış"),
    b2g1Ing("meat", "Lamb or beef cubes", "Lamm- oder Rindfleischwürfel", "لحم غنم أو بقر مكعّبات", "Kuzu veya dana kuşbaşı", "400 g", "400 g", "400 غرام", "400 g"),
    b2g1Ing("tomato", "Tomatoes", "Tomaten", "بندورة", "Domates", "3 grated + 1 tbsp paste", "3 gerieben + 1 EL Mark", "3 مبشورة + ملعقة معجون", "3 rendelenmiş + 1 yk salça"),
    b2g1Ing("onion", "Onion", "Zwiebel", "بصل", "Soğan", "1, chopped", "1, gehackt", "حبة مفرومة", "1, doğranmış"),
    b2g1Ing("garlic", "Garlic", "Knoblauch", "ثوم", "Sarımsak", "4 cloves, minced", "4 Zehen, gehackt", "4 فصوص مفرومة", "4 diş, ezilmiş"),
    b2g1Ing("coriander", "Ground coriander", "Gemahlener Koriander", "كزبرة مطحونة", "Toz kişniş", "1 tsp", "1 TL", "ملعقة صغيرة", "1 tatlı kaşığı"),
    b2g1Ing("lemon", "Lemon juice", "Zitronensaft", "عصير ليمون", "Limon suyu", "1–2 tbsp", "1–2 EL", "1–2 ملاعق", "1–2 yk"),
    b2g1Ing("oil", "Olive oil or ghee", "Olivenöl oder Butterschmalz", "زيت زيتون أو سمن", "Zeytinyağı veya sadeyağ", "3 tbsp", "3 EL", "3 ملاعق كبيرة", "3 yk"),
    b2g1Ing("salt", "Salt & black pepper", "Salz & Pfeffer", "ملح وفلفل", "Tuz ve biber", "to taste", "nach Geschmack", "حسب الذوق", "damak tadına göre"),
  ],
  localeCopy: {
    en: b2g1Loc(
      "Syrian okra stew with tender meat in tomato-garlic sauce — a classic family main with rice or bread.",
      "Syrian",
      ["Trim okra carefully; avoid over-stirring.", "Brown the meat well before the tomato sauce.", "Finish with lemon for a bright Syrian note."],
      "Refrigerate up to 3 days; reheat gently. Serve with rice or flatbread.",
      [
        "Brown the meat with onion in oil; season with salt, pepper and coriander.",
        "Add grated tomato and tomato paste; simmer until slightly thickened.",
        "Add water to cover the meat and cook until tender.",
        "Add trimmed okra and garlic; simmer gently until okra is soft and sauce rich.",
        "Finish with lemon juice to taste and rest a few minutes.",
      ],
    ),
    de: b2g1Loc(
      "Syrischer Okra-Eintopf mit zartem Fleisch in Knoblauch-Tomatensauce — klassisches Familienessen mit Reis oder Brot.",
      "Syrisch",
      ["Okra vorsichtig putzen; nicht zu stark rühren.", "Fleisch gut anbräunen.", "Mit Zitrone abschließen."],
      "Bis zu 3 Tage kühlen; sanft erwärmen. Mit Reis oder Fladenbrot.",
      [
        "Fleisch mit Zwiebel in Öl anbräunen; mit Salz, Pfeffer und Koriander würzen.",
        "Geriebene Tomate und Mark zugeben; leicht eindicken lassen.",
        "Wasser zum Bedecken zugeben und garen, bis das Fleisch zart ist.",
        "Geputzte Okra und Knoblauch zugeben; sanft köcheln bis weich.",
        "Mit Zitronensaft abschmecken und kurz ruhen lassen.",
      ],
    ),
    ar: b2g1Loc(
      "بامية باللحمة على الطريقة السورية: لحم طري وبامية في صلصة بندورة وثوم — يخنة عائلية مع الرز أو الخبز.",
      "سوري",
      ["نظّفي البامية بعناية وتجنّبي التحريك الشديد.", "حمّري اللحم جيداً قبل صلصة البندورة.", "أنهي بعصير الليمون."],
      "تُحفظ حتى 3 أيام؛ أعيدي التسخين بهدوء. مع أرز أو خبز.",
      [
        "حمّري اللحم مع البصل في الزيت؛ تبّلي بالملح والفلفل والكزبرة.",
        "أضيفي البندورة المبشورة والمعجون؛ اتركيه يتكثّف قليلاً.",
        "أضيفي ماءً ليغطّي اللحم واطبخي حتى يطرى.",
        "أضيفي البامية والثوم؛ اتركيه يغلي بهدوء حتى تطرى البامية.",
        "أنهي بعصير الليمون واتركيه يرتاح دقائق.",
      ],
    ),
    tr: b2g1Loc(
      "Suriye usulü etli bamya: domates-sarımsak sosunda yumuşak et ve bamya — pirinç veya ekmekle aile yemeği.",
      "Suriye",
      ["Bamyayı dikkatle ayıklayın; fazla karıştırmayın.", "Eti iyice kavurun.", "Limonla bitirin."],
      "3 güne kadar saklayın; hafif ısıtın. Pilav veya ekmekle.",
      [
        "Eti soğanla yağda kavurun; tuz, biber ve kişnişle tatlandırın.",
        "Rendelenmiş domates ve salçayı ekleyip biraz koyulaştırın.",
        "Eti örtecek su ekleyip yumuşayana dek pişirin.",
        "Bamya ve sarımsağı ekleyip nazikçe pişirin.",
        "Limon suyu ekleyip birkaç dakika dinlendirin.",
      ],
    ),
  },
  naturalYield: {
    baseServingsMin: 3,
    baseServingsMax: 4,
    servingLabel: "Serves ~3 as a family main (with rice)",
    scalingNote: "Scale meat and okra together; keep tomato, garlic and lemon balanced.",
  },
  defaultRole: "main",
  canServeAsMain: false,
  photo: b2g1Photo(
    "Syrian okra and meat stew in tomato sauce, homemade natural look.",
    "Stew as hero on a calm neutral plate; optional rice beside.",
    "Must show okra and meat in tomato sauce — Syrian bamieh bil lahmeh.",
    "/assets/dishes/arab/bamieh-bil-lahmeh.jpg",
  ),
});

const SHAKRIYEH: GeneratedRecipe = b2g1Recipe({
  matchKeys: [
    "shakriyeh with rice",
    "shakriyeh",
    "shakriya",
    "laban immo",
    "شاكرية",
    "شاكرية مع رز",
    "شاكرية مع الأرز",
  ],
  canonicalTitle: "Shakriyeh with Rice",
  prepMinutes: 90,
  difficulty: "medium",
  servings: 3,
  mealTypes: ["main"],
  mealSlotRole: "dinner_complete",
  mealIntents: ["family_friendly", "special", "high_calorie"],
  proteinCategory: "lamb",
  budgetTier: "medium",
  suitability: ["guest_friendly", "everyday_host", "shareable"],
  moods: ["everyday", "special"],
  dietaryTags: ["contains_meat", "contains_dairy"],
  allergens: ["Dairy", "Eggs"],
  ingredientTokens: ["lamb", "yogurt", "rice", "garlic", "mint", "egg"],
  pantryIngredients: [
    { canonicalId: "meat", role: "critical", tokens: ["lamb", "meat"] },
    { canonicalId: "yogurt", role: "critical", tokens: ["yogurt", "laban"] },
    { canonicalId: "rice", role: "critical", tokens: ["rice"] },
    { canonicalId: "garlic", role: "supporting", tokens: ["garlic"] },
  ],
  ingredients: [
    b2g1Ing("meat", "Lamb pieces", "Lammstücke", "قطع لحم غنم", "Kuzu eti", "600 g", "600 g", "600 غرام", "600 g"),
    b2g1Ing("yogurt", "Full-fat yogurt", "Vollfettjoghurt", "لبن رائب كامل الدسم", "Tam yağlı yoğurt", "700 g plain", "700 g natur", "700 غرام سادة", "700 g sade"),
    b2g1Ing("egg", "Egg yolk", "Eigelb", "صفار بيض", "Yumurta sarısı", "1, to stabilize yogurt", "1, zum Stabilisieren", "1 لتثبيت اللبن", "1, sabitlemek için"),
    b2g1Ing("starch", "Cornstarch", "Maisstärke", "نشا ذرة", "Mısır nişastası", "1 tbsp", "1 EL", "ملعقة كبيرة", "1 yk"),
    b2g1Ing("garlic", "Garlic", "Knoblauch", "ثوم", "Sarımsak", "4 cloves, crushed", "4 Zehen, zerdrückt", "4 فصوص مهروسة", "4 diş ezilmiş"),
    b2g1Ing("mint", "Dried mint", "Getrocknete Minze", "نعناع يابس", "Kuru nane", "1 tsp", "1 TL", "ملعقة صغيرة", "1 tk"),
    b2g1Ing("rice", "Rice", "Reis", "أرز", "Pirinç", "1.5 cups (300 g)", "1,5 Tassen (300 g)", "كوب ونصف (300 غ)", "1,5 su bardağı (300 g)"),
    b2g1Ing("ghee", "Ghee or butter", "Butterschmalz oder Butter", "سمن أو زبدة", "Sadeyağ veya tereyağı", "2 tbsp", "2 EL", "ملعقتان", "2 yk"),
    b2g1Ing("salt", "Salt", "Salz", "ملح", "Tuz", "to taste", "nach Geschmack", "حسب الذوق", "damak tadına göre"),
  ],
  localeCopy: {
    en: b2g1Loc(
      "Syrian shakriyeh: tender meat finished in a warm seasoned yogurt sauce, served with rice.",
      "Syrian",
      ["Temper yogurt gently so it does not split.", "Cook meat in broth first, then fold into yogurt.", "Serve immediately with steaming rice."],
      "Best fresh. Refrigerate meat and sauce separately up to 2 days; reheat yogurt very gently.",
      [
        "Simmer lamb with salt until tender; reserve some broth.",
        "Whisk yogurt with egg yolk and cornstarch until smooth.",
        "Warm yogurt over low heat, stirring, until lightly thickened — do not boil hard.",
        "Add crushed garlic and dried mint; fold in meat with a little broth.",
        "Cook rice separately with ghee until fluffy.",
        "Serve shakriyeh over or beside the rice.",
      ],
    ),
    de: b2g1Loc(
      "Syrisches Shakriyeh: zartes Fleisch in warmer Joghurtsauce, mit Reis serviert.",
      "Syrisch",
      ["Joghurt behutsam erhitzen.", "Fleisch zuerst in Brühe garen.", "Sofort mit heißem Reis servieren."],
      "Am besten frisch. Getrennt bis 2 Tage kühlen; Joghurt sehr sanft erwärmen.",
      [
        "Lamm mit Salz garen; etwas Brühe zurückhalten.",
        "Joghurt mit Eigelb und Stärke glatt verrühren.",
        "Joghurt bei niedriger Hitze unter Rühren leicht eindicken — nicht stark kochen.",
        "Knoblauch und Minze zugeben; Fleisch mit etwas Brühe unterheben.",
        "Reis separat mit Butterschmalz garen.",
        "Shakriyeh über oder neben dem Reis servieren.",
      ],
    ),
    ar: b2g1Loc(
      "شاكرية سورية: لحم طري في صلصة لبن دافئة متبّلة، مع الرز.",
      "سوري",
      ["سخّني اللبن بلطف حتى لا يفصّل.", "اطبخي اللحم في المرق أولاً.", "قدّمي فوراً مع رز ساخن."],
      "الأفضل طازجة. احفظي اللحم والصلصة منفصلين حتى يومين.",
      [
        "اطبخي اللحم مع الملح حتى يطرى؛ احتفظي بقليل من المرق.",
        "اخفقي اللبن مع صفار البيض والنشا.",
        "سخّني اللبن على نار هادئة مع التحريك حتى يتكثّف قليلاً دون غليان قوي.",
        "أضيفي الثوم والنعناع؛ أدخلي اللحم مع قليل من المرق.",
        "اطبخي الأرز منفصلاً بالسمن.",
        "قدّمي الشاكرية فوق الرز أو إلى جانبه.",
      ],
    ),
    tr: b2g1Loc(
      "Suriye şakriyesi: ılık baharatlı yoğurt sosunda yumuşak et, pilavla.",
      "Suriye",
      ["Yoğurdu ayırmadan nazik ısıtın.", "Eti önce suda pişirin.", "Hemen sıcak pilavla servis edin."],
      "En iyisi taze. Eti ve sosu ayrı 2 güne kadar saklayın.",
      [
        "Kuzuyu tuzla yumuşayana dek haşlayın; biraz suyunu ayırın.",
        "Yoğurdu yumurta sarısı ve nişasta ile çırpın.",
        "Yoğurdu kısık ateşte karıştırarak koyulaştırın — sert kaynatmayın.",
        "Sarımsak ve naneyi ekleyin; eti biraz suyla katın.",
        "Pirinci ayrı sadeyağla pişirin.",
        "Şakriyeyi pilavın üzerinde veya yanında servis edin.",
      ],
    ),
  },
  naturalYield: {
    baseServingsMin: 3,
    baseServingsMax: 4,
    servingLabel: "Serves ~3 with rice",
    scalingNote: "Scale meat, yogurt and rice together; keep garlic and mint balanced.",
  },
  defaultRole: "main",
  canServeAsMain: false,
  photo: b2g1Photo(
    "Syrian shakriyeh yogurt-meat sauce with plain rice, soft natural daylight.",
    "Yogurt sauce with meat as hero; rice secondary.",
    "Meat in warm yogurt sauce with rice — Syrian shakriyeh identity.",
    "/assets/dishes/arab/shakriyeh-with-rice.jpg",
  ),
});

const MOLOKHIA: GeneratedRecipe = b2g1Recipe({
  matchKeys: [
    "syrian molokhia with chicken",
    "syrian molokhia",
    "molokhia bil dajaj",
    "mulukhiyah syrian",
    "ملوخية بالدجاج",
    "ملوخية سورية",
    "ملوخية شامية",
  ],
  canonicalTitle: "Syrian Molokhia with Chicken",
  prepMinutes: 70,
  difficulty: "medium",
  servings: 3,
  mealTypes: ["main", "stew"],
  mealSlotRole: "dinner_complete",
  mealIntents: ["family_friendly", "healthy", "budget"],
  proteinCategory: "chicken",
  budgetTier: "medium",
  suitability: ["everyday_host", "shareable"],
  moods: ["everyday"],
  dietaryTags: ["contains_meat"],
  allergens: [],
  ingredientTokens: ["molokhia", "chicken", "garlic", "coriander", "lemon", "rice"],
  pantryIngredients: [
    { canonicalId: "molokhia", role: "critical", tokens: ["molokhia", "mulukhiyah"] },
    { canonicalId: "chicken", role: "critical", tokens: ["chicken"] },
    { canonicalId: "garlic", role: "supporting", tokens: ["garlic"] },
    { canonicalId: "rice", role: "supporting", tokens: ["rice"] },
  ],
  ingredients: [
    b2g1Ing("molokhia", "Chopped molokhia", "Gehackte Molokhia", "ملوخية مفرومة", "Doğranmış molohiya", "400 g frozen or fresh", "400 g TK oder frisch", "400 غ مجمدة أو طازجة", "400 g donuk veya taze"),
    b2g1Ing("chicken", "Chicken pieces", "Hähnchenteile", "قطع دجاج", "Tavuk parçaları", "700 g", "700 g", "700 غرام", "700 g"),
    b2g1Ing("garlic", "Garlic", "Knoblauch", "ثوم", "Sarımsak", "6–8 cloves, crushed", "6–8 Zehen", "6–8 فصوص مهروسة", "6–8 diş ezilmiş"),
    b2g1Ing("coriander", "Ground coriander", "Gemahlener Koriander", "كزبرة مطحونة", "Toz kişniş", "1.5 tsp", "1,5 TL", "ملعقة ونصف", "1,5 tk"),
    b2g1Ing("cardamom", "Cardamom pods", "Kardamomkapseln", "حبّ هيل", "Kakule", "3–4 for broth", "3–4 für Brühe", "3–4 للمرق", "3–4 et suyu için"),
    b2g1Ing("lemon", "Lemon", "Zitrone", "ليمون", "Limon", "1–2, juiced to taste", "1–2, Saft nach Geschmack", "1–2 عصير حسب الذوق", "1–2, suyuna göre"),
    b2g1Ing("rice", "Rice", "Reis", "أرز", "Pirinç", "1.5 cups, to serve", "1,5 Tassen", "كوب ونصف للتقديم", "1,5 su bardağı"),
    b2g1Ing("ghee", "Ghee or oil", "Butterschmalz oder Öl", "سمن أو زيت", "Sadeyağ veya yağ", "3 tbsp", "3 EL", "3 ملاعق", "3 yk"),
    b2g1Ing("salt", "Salt & pepper", "Salz & Pfeffer", "ملح وفلفل", "Tuz ve biber", "to taste", "nach Geschmack", "حسب الذوق", "damak tadına göre"),
  ],
  localeCopy: {
    en: b2g1Loc(
      "Syrian molokhia with chicken: smooth green leaf stew with garlic-coriander taqliya, served with rice and lemon — Levantine style, not Egyptian whole-leaf.",
      "Syrian",
      ["Use finely chopped molokhia for the Syrian texture.", "Fry garlic and coriander in ghee (taqliya).", "Serve with rice and lemon at the table."],
      "Refrigerate up to 3 days; reheat gently. Add lemon when serving.",
      [
        "Simmer chicken with cardamom, salt and pepper; reserve broth.",
        "Add chopped molokhia to strained broth; simmer until soft and slightly thick.",
        "Fry crushed garlic with coriander in ghee until fragrant (taqliya).",
        "Stir taqliya into molokhia; return chicken and simmer briefly.",
        "Serve over or beside rice with lemon.",
      ],
    ),
    de: b2g1Loc(
      "Syrische Molokhia mit Hähnchen: glatter Blattendufttopf mit Knoblauch-Koriander-Taqliya, mit Reis und Zitrone — nicht ägyptische Ganzblatt-Variante.",
      "Syrisch",
      ["Fein gehackte Molokhia verwenden.", "Knoblauch und Koriander in Butterschmalz anbraten.", "Mit Reis und Zitrone servieren."],
      "Bis zu 3 Tage kühlen; sanft erwärmen. Zitrone beim Servieren.",
      [
        "Hähnchen mit Kardamom, Salz und Pfeffer garen; Brühe zurückhalten.",
        "Gehackte Molokhia in die Brühe geben; köcheln bis weich.",
        "Knoblauch mit Koriander in Butterschmalz duftig braten (Taqliya).",
        "Taqliya unterrühren; Hähnchen zurückgeben.",
        "Mit Reis und Zitrone servieren.",
      ],
    ),
    ar: b2g1Loc(
      "ملوخية سورية بالدجاج: يخنة ورق ناعمة بتقليلة ثوم وكزبرة، مع الرز والليمون — أسلوب شامي لا النسخة المصرية بالورق الصحيح.",
      "سوري",
      ["استخدمي ملوخية مفرومة ناعماً.", "اقلِ الثوم والكزبرة بالسمن (تقلية).", "قدّمي مع الرز والليمون."],
      "تُحفظ حتى 3 أيام. يُضاف الليمون عند التقديم.",
      [
        "اطبخي الدجاج مع الهيل والملح والفلفل؛ احتفظي بالمرق.",
        "أضيفي الملوخية المفرومة للمرق واتركيه يغلي حتى يطرى.",
        "اقلِ الثوم المهروس مع الكزبرة بالسمن حتى تفوح الرائحة.",
        "قلّبي التقلية في الملوخية؛ أعيدي الدجاج.",
        "قدّمي مع الرز والليمون.",
      ],
    ),
    tr: b2g1Loc(
      "Suriye usulü tavuklu molohiya: sarımsak-kişniş takliyeli pürüzsüz yeşil yahni; pirinç ve limonla — Mısır usulü değil.",
      "Suriye",
      ["İnce doğranmış molohiya kullanın.", "Sarımsak ve kişnişi sadeyağda kavurun.", "Pirinç ve limonla servis edin."],
      "3 güne kadar saklayın. Limon serviste.",
      [
        "Tavuğu kakule, tuz ve biberle pişirin; suyunu ayırın.",
        "Doğranmış molohiyayı et suyuna ekleyip yumuşayana dek pişirin.",
        "Ezilmiş sarımsağı kişnişle sadeyağda kavurun (takliye).",
        "Takliyeyi karıştırın; tavuğu geri ekleyin.",
        "Pirinç ve limonla servis edin.",
      ],
    ),
  },
  naturalYield: {
    baseServingsMin: 3,
    baseServingsMax: 4,
    servingLabel: "Serves ~3 with rice",
    scalingNote: "Scale molokhia, chicken and broth together; keep taqliya fragrant.",
  },
  defaultRole: "main",
  canServeAsMain: false,
  photo: b2g1Photo(
    "Syrian green molokhia with chicken, rice and lemon, natural light.",
    "Green stew as hero; rice and lemon secondary.",
    "Syrian chopped molokhia with chicken — distinct from Egyptian style.",
    "/assets/dishes/arab/syrian-molokhia-with-chicken.jpg",
  ),
});

const MEAT_MAQLUBA: GeneratedRecipe = b2g1Recipe({
  matchKeys: [
    "syrian meat maqluba",
    "maqluba bil lahmeh",
    "meat maqluba syrian",
    "مقلوبة باللحمة",
    "مقلوبة لحم سورية",
    "مقلوبة باللحم",
  ],
  canonicalTitle: "Syrian Meat Maqluba",
  prepMinutes: 95,
  difficulty: "medium",
  servings: 3,
  mealTypes: ["main", "rice"],
  mealSlotRole: "dinner_complete",
  mealIntents: ["family_friendly", "special", "high_calorie"],
  proteinCategory: "lamb",
  budgetTier: "medium",
  suitability: ["guest_friendly", "everyday_host", "shareable"],
  moods: ["special", "everyday"],
  dietaryTags: ["contains_meat"],
  allergens: ["Nuts"],
  ingredientTokens: ["lamb", "rice", "eggplant", "potato", "onion", "allspice", "almonds"],
  pantryIngredients: [
    { canonicalId: "meat", role: "critical", tokens: ["lamb", "beef", "meat"] },
    { canonicalId: "rice", role: "critical", tokens: ["rice"] },
    { canonicalId: "eggplant", role: "supporting", tokens: ["eggplant"] },
    { canonicalId: "potato", role: "supporting", tokens: ["potato"] },
  ],
  ingredients: [
    b2g1Ing("meat", "Lamb or beef pieces", "Lamm- oder Rindfleischstücke", "قطع لحم غنم أو بقر", "Kuzu veya dana", "600 g", "600 g", "600 غرام", "600 g"),
    b2g1Ing("rice", "Rice", "Reis", "أرز", "Pirinç", "2 cups (400 g)", "2 Tassen (400 g)", "كوبان (400 غ)", "2 su bardağı (400 g)"),
    b2g1Ing("eggplant", "Eggplant", "Aubergine", "باذنجان", "Patlıcan", "2, sliced and fried", "2, Scheiben gebraten", "حبتان شرائح مقلية", "2, dilim kızartılmış"),
    b2g1Ing("potato", "Potato", "Kartoffel", "بطاطا", "Patates", "2, sliced and fried", "2, Scheiben gebraten", "حبتان شرائح مقلية", "2, dilim kızartılmış"),
    b2g1Ing("onion", "Onion", "Zwiebel", "بصل", "Soğan", "1, for broth", "1, für Brühe", "حبة للمرق", "1, et suyu için"),
    b2g1Ing("spice", "Allspice & cinnamon", "Piment & Zimt", "بهار وقرفة", "Yenibahar ve tarçın", "2 tsp + 1/2 tsp", "2 TL + 1/2 TL", "ملعقتان + نصف", "2 tk + 1/2 tk"),
    b2g1Ing("almonds", "Toasted almonds or pine nuts", "Geröstete Mandeln/Pinienkerne", "لوز أو صنوبر محمّص", "Kavrulmuş badem/çam fıstığı", "1/4 cup garnish", "1/4 Tasse", "ربع كوب", "1/4 su bardağı"),
    b2g1Ing("oil", "Oil", "Öl", "زيت", "Yağ", "for frying", "zum Braten", "للقلي", "kızartmak için"),
    b2g1Ing("salt", "Salt & pepper", "Salz & Pfeffer", "ملح وفلفل", "Tuz ve biber", "to taste", "nach Geschmack", "حسب الذوق", "damak tadına göre"),
  ],
  localeCopy: {
    en: b2g1Loc(
      "Syrian meat maqluba: spiced meat with fried eggplant and potato under rice, flipped into a dome — no cauliflower in this approved variant.",
      "Syrian",
      ["Meat with eggplant and potato only — no cauliflower.", "Rest before flipping.", "Broth just covering the rice."],
      "Refrigerate up to 3 days; reheat covered with a splash of water.",
      [
        "Simmer meat with onion and spices until tender; reserve broth.",
        "Fry eggplant and potato until golden; drain.",
        "Season rinsed rice with a little spice.",
        "Layer meat, then vegetables, then rice in the pot.",
        "Pour broth to just cover; cook gently until rice is tender.",
        "Rest 10 minutes, invert, garnish with toasted nuts.",
      ],
    ),
    de: b2g1Loc(
      "Syrisches Fleisch-Maqluba: Fleisch mit Aubergine und Kartoffel unter Reis, gestürzt — ohne Blumenkohl.",
      "Syrisch",
      ["Nur Fleisch, Aubergine, Kartoffel — kein Blumenkohl.", "Vor dem Stürzen ruhen.", "Brühe knapp über dem Reis."],
      "Bis zu 3 Tage kühlen; mit etwas Wasser erwärmen.",
      [
        "Fleisch mit Zwiebel und Gewürzen garen; Brühe zurückhalten.",
        "Aubergine und Kartoffel goldbraun braten.",
        "Reis mit etwas Gewürz würzen.",
        "Fleisch, Gemüse, dann Reis schichten.",
        "Brühe knapp darüber; sanft garen.",
        "10 Min. ruhen, stürzen, mit Nüssen garnieren.",
      ],
    ),
    ar: b2g1Loc(
      "مقلوبة سورية باللحمة: لحم مع باذنجان وبطاطا مقلية تحت الأرز ثم تُقلب — دون قرنبيط في هذه النسخة.",
      "سوري",
      ["لحم مع باذنجان وبطاطا فقط — بلا قرنبيط.", "اتركيها ترتاح قبل القلب.", "المرق يغطّي الأرز بالكاد."],
      "تُحفظ حتى 3 أيام؛ أعيدي التسخين مع رشة ماء.",
      [
        "اطبخي اللحم مع البصل والبهار؛ احتفظي بالمرق.",
        "اقلي الباذنجان والبطاطا حتى تذهبّ.",
        "تبّلي الأرز بقليل من البهار.",
        "رصّي اللحم ثم الخضار ثم الأرز.",
        "اسكبي المرق بالكاد فوق الأرز؛ اطبخي بهدوء.",
        "اتركيها 10 دقائق، اقلبيها وزيّني بالمكسّرات.",
      ],
    ),
    tr: b2g1Loc(
      "Suriye et maklubesi: et, kızarmış patlıcan ve patatesli pirinç kubbesi — bu onaylı varyantta karnabahar yok.",
      "Suriye",
      ["Sadece et, patlıcan, patates — karnabahar yok.", "Çevirmeden önce dinlendirin.", "Su pirinci ancak örtsün."],
      "3 güne kadar saklayın; biraz suyla ısıtın.",
      [
        "Eti soğan ve baharatla pişirin; suyunu ayırın.",
        "Patlıcan ve patatesi kızartıp süzün.",
        "Pirinci biraz baharatla tatlandırın.",
        "Et, sebze, sonra pirinç katmanlayın.",
        "Suyu ancak örtecek kadar döküp pişirin.",
        "10 dk dinlendirip ters çevirin; kuruyemişle süsleyin.",
      ],
    ),
  },
  naturalYield: {
    baseServingsMin: 3,
    baseServingsMax: 4,
    servingLabel: "One inverted pot · serves ~3–4",
    scalingNote: "Distinct from Palestinian chicken maqluba with cauliflower already in catalog.",
  },
  defaultRole: "main",
  canServeAsMain: false,
  photo: b2g1Photo(
    "Inverted Syrian meat maqluba with eggplant and potato, no cauliflower.",
    "Upside-down rice dome centered on a platter.",
    "Syrian meat maqluba without cauliflower — distinct from Palestinian Maqluba.",
    "/assets/dishes/arab/syrian-meat-maqluba.jpg",
  ),
});

const SHISH_BARAK: GeneratedRecipe = b2g1Recipe({
  matchKeys: [
    "shish barak",
    "shishbarak",
    "shishbarak yogurt",
    "ششبرك",
    "شيش برك",
    "ششبرك لبن",
  ],
  canonicalTitle: "Shish Barak",
  prepMinutes: 100,
  difficulty: "medium",
  servings: 3,
  mealTypes: ["main"],
  mealSlotRole: "dinner_complete",
  mealIntents: ["family_friendly", "special", "high_calorie"],
  proteinCategory: "mixed",
  budgetTier: "medium",
  suitability: ["guest_friendly", "everyday_host", "shareable"],
  moods: ["special"],
  dietaryTags: ["contains_meat", "contains_dairy", "contains_egg"],
  allergens: ["Gluten", "Dairy", "Eggs"],
  ingredientTokens: ["flour", "minced meat", "yogurt", "garlic", "onion", "pine nuts"],
  pantryIngredients: [
    { canonicalId: "flour", role: "critical", tokens: ["flour", "dough"] },
    { canonicalId: "minced-meat", role: "critical", tokens: ["minced meat", "lamb", "beef"] },
    { canonicalId: "yogurt", role: "critical", tokens: ["yogurt"] },
    { canonicalId: "garlic", role: "supporting", tokens: ["garlic"] },
  ],
  ingredients: [
    b2g1Ing("flour", "Flour", "Mehl", "طحين", "Un", "250 g, for dumpling dough", "250 g für Teig", "250 غ للعجين", "250 g hamur için"),
    b2g1Ing("egg", "Egg", "Ei", "بيض", "Yumurta", "1, for dough (optional water)", "1, für Teig", "1 للعجين", "1, hamur için"),
    b2g1Ing("minced-meat", "Minced lamb or beef", "Lamm- oder Rinderhack", "لحم مفروم", "Kıyma", "250 g", "250 g", "250 غرام", "250 g"),
    b2g1Ing("onion", "Onion", "Zwiebel", "بصل", "Soğan", "1 small, for filling", "1 kleine", "حبة صغيرة للحشوة", "1 küçük"),
    b2g1Ing("pine-nuts", "Pine nuts", "Pinienkerne", "صنوبر", "Çam fıstığı", "2 tbsp, toasted", "2 EL geröstet", "ملعقتان محمّص", "2 yk kavrulmuş"),
    b2g1Ing("yogurt", "Full-fat yogurt", "Vollfettjoghurt", "لبن رائب", "Yoğurt", "800 g", "800 g", "800 غرام", "800 g"),
    b2g1Ing("starch", "Cornstarch", "Maisstärke", "نشا", "Nişasta", "1.5 tbsp", "1,5 EL", "ملعقة ونصف", "1,5 yk"),
    b2g1Ing("garlic", "Garlic", "Knoblauch", "ثوم", "Sarımsak", "4 cloves, crushed", "4 Zehen", "4 فصوص", "4 diş"),
    b2g1Ing("mint", "Dried mint", "Getrocknete Minze", "نعناع يابس", "Kuru nane", "1 tsp", "1 TL", "ملعقة صغيرة", "1 tk"),
    b2g1Ing("salt", "Salt & pepper", "Salz & Pfeffer", "ملح وفلفل", "Tuz ve biber", "to taste", "nach Geschmack", "حسب الذوق", "damak tadına göre"),
  ],
  localeCopy: {
    en: b2g1Loc(
      "Syrian shish barak: small meat-filled dumplings cooked in a warm garlicky yogurt sauce.",
      "Syrian",
      ["Seal dumplings well so they do not open in the yogurt.", "Temper yogurt gently.", "Toast pine nuts for the filling."],
      "Best same day. Refrigerate up to 2 days; reheat yogurt sauce very gently.",
      [
        "Make a soft dough from flour, egg, salt and water; rest 20 minutes.",
        "Cook minced meat with onion, salt, pepper and pine nuts; cool.",
        "Roll dough thin, cut small circles, fill and seal into dumplings.",
        "Whisk yogurt with cornstarch; warm gently until lightly thick.",
        "Add garlic and mint; simmer dumplings in the yogurt until cooked through.",
        "Serve hot in bowls.",
      ],
    ),
    de: b2g1Loc(
      "Syrisches Shish Barak: kleine fleischgefüllte Teigtaschen in warmer Knoblauch-Joghurtsauce.",
      "Syrisch",
      ["Teigtaschen gut verschließen.", "Joghurt behutsam erhitzen.", "Pinienkerne rösten."],
      "Am besten am selben Tag. Bis 2 Tage kühlen; Joghurt sehr sanft erwärmen.",
      [
        "Weichen Teig aus Mehl, Ei, Salz und Wasser machen; 20 Min. ruhen.",
        "Hack mit Zwiebel, Salz, Pfeffer und Pinienkernen garen; abkühlen.",
        "Teig dünn ausrollen, Kreise schneiden, füllen und schließen.",
        "Joghurt mit Stärke verrühren; sanft leicht eindicken.",
        "Knoblauch und Minze zugeben; Teigtaschen darin gar ziehen.",
        "Heiß in Schalen servieren.",
      ],
    ),
    ar: b2g1Loc(
      "ششبرك سوري: عجينة صغيرة محشوّة باللحم تُطهى في صلصة لبن وثوم.",
      "سوري",
      ["أغلقي العجينة جيداً.", "سخّني اللبن بلطف.", "حمّصي الصنوبر للحشوة."],
      "الأفضل في نفس اليوم. حتى يومين في الثلاجة.",
      [
        "اعجني عجينة طرية من الطحين والبيض والملح والماء؛ ارتاحي 20 دقيقة.",
        "اطبخي اللحم المفروم مع البصل والملح والفلفل والصنوبر؛ برّديه.",
        "افردي العجين، قطّعي دوائر، احشي وأغلقي.",
        "اخفقي اللبن مع النشا؛ سخّنيه بلطف حتى يتكثّف قليلاً.",
        "أضيفي الثوم والنعناع؛ اطبخي الششبرك في اللبن حتى ينضج.",
        "قدّمي ساخناً في صحون.",
      ],
    ),
    tr: b2g1Loc(
      "Suriye şiş barağı: yoğurt sosunda pişen küçük kıymalı mantılar.",
      "Suriye",
      ["Mantıları iyi kapatın.", "Yoğurdu nazik ısıtın.", "Çam fıstığını kavurun."],
      "Aynı gün en iyisi. 2 güne kadar saklayın.",
      [
        "Un, yumurta, tuz ve sudan yumuşak hamur yoğurun; 20 dk dinlendirin.",
        "Kıymayı soğan, tuz, biber ve çam fıstığıyla pişirip soğutun.",
        "Hamuru açıp daire kesin, doldurup kapatın.",
        "Yoğurdu nişasta ile çırpıp hafif koyulaştırın.",
        "Sarımsak ve nane ekleyip mantıları yoğurtta pişirin.",
        "Sıcak kaselerde servis edin.",
      ],
    ),
  },
  naturalYield: {
    baseServingsMin: 3,
    baseServingsMax: 4,
    servingLabel: "Serves ~3 as a main",
    scalingNote: "Scale dough, filling and yogurt together.",
  },
  defaultRole: "main",
  canServeAsMain: false,
  photo: b2g1Photo(
    "Bowl of shish barak dumplings in yogurt sauce with garlic and mint.",
    "Dumplings in yogurt sauce as hero.",
    "Small meat dumplings in yogurt — Syrian shish barak.",
    "/assets/dishes/arab/shish-barak.jpg",
  ),
});

const FASOLIA: GeneratedRecipe = b2g1Recipe({
  matchKeys: [
    "fasolia bi zeit",
    "fasoulia bi zeit",
    "green beans olive oil",
    "loubieh bi zeit",
    "فاصوليا بزيت",
    "فاصولياء بزيت",
    "لوبيا بزيت",
  ],
  canonicalTitle: "Fasolia bi Zeit",
  prepMinutes: 55,
  difficulty: "easy",
  servings: 3,
  mealTypes: ["side", "stew"],
  mealSlotRole: "side_component",
  mealIntents: ["family_friendly", "budget", "healthy"],
  proteinCategory: "legume",
  budgetTier: "low",
  suitability: ["everyday_host", "shareable"],
  moods: ["everyday", "quick"],
  dietaryTags: ["vegetarian_ok", "vegan_ok"],
  allergens: [],
  ingredientTokens: ["green beans", "tomato", "garlic", "onion", "olive oil"],
  pantryIngredients: [
    { canonicalId: "green-beans", role: "critical", tokens: ["green beans", "fasolia", "loubieh"] },
    { canonicalId: "tomato", role: "supporting", tokens: ["tomato"] },
    { canonicalId: "olive-oil", role: "critical", tokens: ["olive oil"] },
    { canonicalId: "garlic", role: "supporting", tokens: ["garlic"] },
  ],
  ingredients: [
    b2g1Ing("green-beans", "Green beans", "Grüne Bohnen", "فاصوليا خضراء", "Taze fasulye", "500 g, trimmed", "500 g, geputzt", "500 غ منظّفة", "500 g ayıklanmış"),
    b2g1Ing("tomato", "Tomatoes", "Tomaten", "بندورة", "Domates", "3 grated + 1 tbsp paste", "3 gerieben + 1 EL Mark", "3 مبشورة + ملعقة معجون", "3 rendelenmiş + 1 yk salça"),
    b2g1Ing("onion", "Onion", "Zwiebel", "بصل", "Soğan", "1, sliced", "1, in Scheiben", "حبة شرائح", "1, dilim"),
    b2g1Ing("garlic", "Garlic", "Knoblauch", "ثوم", "Sarımsak", "4 cloves", "4 Zehen", "4 فصوص", "4 diş"),
    b2g1Ing("olive-oil", "Olive oil", "Olivenöl", "زيت زيتون", "Zeytinyağı", "1/3 cup", "1/3 Tasse", "ثلث كوب", "1/3 su bardağı"),
    b2g1Ing("lemon", "Lemon juice", "Zitronensaft", "عصير ليمون", "Limon suyu", "1–2 tbsp optional", "1–2 EL optional", "1–2 ملاعق اختيارية", "1–2 yk isteğe bağlı"),
    b2g1Ing("salt", "Salt & pepper", "Salz & Pfeffer", "ملح وفلفل", "Tuz ve biber", "to taste", "nach Geschmack", "حسب الذوق", "damak tadına göre"),
  ],
  localeCopy: {
    en: b2g1Loc(
      "Fasolia bi zeit: green beans slowly cooked in olive oil with tomato and garlic — vegetarian Syrian home classic, not a meat bean stew.",
      "Syrian",
      ["Use plenty of olive oil — it is the cooking medium.", "Cook until beans are soft and sauce thick.", "Excellent warm or at room temperature."],
      "Keeps 3–4 days refrigerated; flavour improves next day.",
      [
        "Warm olive oil; soften onion and garlic.",
        "Add grated tomato and paste; simmer a few minutes.",
        "Add green beans, salt and pepper; toss to coat.",
        "Add a splash of water, cover, and cook gently until beans are tender and sauce rich.",
        "Finish with lemon if desired; serve with bread or rice.",
      ],
    ),
    de: b2g1Loc(
      "Fasolia bi Zeit: grüne Bohnen langsam in Olivenöl mit Tomate und Knoblauch — vegetarisches syrisches Hausessen, kein Fleischeintopf.",
      "Syrisch",
      ["Viel Olivenöl verwenden.", "Bohnen weich und Sauce dick kochen.", "Warm oder Zimmertemperatur."],
      "3–4 Tage kühlbar; am nächsten Tag noch besser.",
      [
        "Olivenöl erwärmen; Zwiebel und Knoblauch anschwitzen.",
        "Tomate und Mark zugeben; kurz köcheln.",
        "Grüne Bohnen, Salz und Pfeffer zugeben.",
        "Mit etwas Wasser zugedeckt garen, bis die Bohnen zart sind.",
        "Optional mit Zitrone; mit Brot oder Reis servieren.",
      ],
    ),
    ar: b2g1Loc(
      "فاصوليا بزيت: فاصوليا خضراء تُطهى بزيت الزيتون مع البندورة والثوم — طبق سوري نباتي، لا يخنة فاصوليا باللحم.",
      "سوري",
      ["استخدمي زيت زيتون بسخاء.", "اطبخي حتى تطرى الفاصوليا وتكثف الصلصة.", "ممتازة دافئة أو بدرجة حرارة الغرفة."],
      "تُحفظ 3–4 أيام؛ تتحسّن في اليوم التالي.",
      [
        "سخّني زيت الزيتون؛ ليّني البصل والثوم.",
        "أضيفي البندورة والمعجون؛ اتركيه دقائق.",
        "أضيفي الفاصوليا والملح والفلفل.",
        "أضيفي رشة ماء وغطّي واطبخي حتى تطرى.",
        "أنهي بالليمون إن رغبت؛ مع خبز أو رز.",
      ],
    ),
    tr: b2g1Loc(
      "Fasulye bi zeit: zeytinyağında domates ve sarımsakla pişen taze fasulye — etli fasulye yahnisi değil, Suriye zeytinyağlısı.",
      "Suriye",
      ["Bol zeytinyağı kullanın.", "Fasulye yumuşayıp sos koyulaşana dek pişirin.", "Ilık veya oda sıcaklığında güzeldir."],
      "3–4 gün saklanır; ertesi gün daha iyi.",
      [
        "Zeytinyağını ısıtıp soğan ve sarımsağı yumuşatın.",
        "Domates ve salçayı ekleyip birkaç dakika pişirin.",
        "Fasulye, tuz ve biberi ekleyin.",
        "Biraz su ekleyip kapağı kapalı yumuşayana dek pişirin.",
        "İsterseniz limon ekleyin; ekmek veya pilavla servis edin.",
      ],
    ),
  },
  naturalYield: {
    baseServingsMin: 3,
    baseServingsMax: 4,
    servingLabel: "Serves 3–4 as side or light main with bread",
    scalingNote: "Scale beans and tomato together; keep olive oil generous.",
  },
  defaultRole: "side",
  canServeAsMain: true,
  photo: b2g1Photo(
    "Bowl of green beans in olive oil tomato sauce, vegetarian Syrian style.",
    "Beans in sauce as hero; calm neutrals.",
    "Olive-oil fasolia — not meat-based fasolia bil lahmeh.",
    "/assets/dishes/arab/fasolia-bi-zeit.jpg",
  ),
});

export const ARAB_BATCH_2_GROUP_1_A: GeneratedRecipe[] = [
  BAMIEH,
  SHAKRIYEH,
  MOLOKHIA,
  MEAT_MAQLUBA,
  SHISH_BARAK,
  FASOLIA,
];
