/**
 * Arab Batch 2 Group 2A — recipes 16–22 (Mutabbal Batinjan skipped: near-dup of Baba Ghanouj).
 * Studio draft sources only. No images.
 */

import {
  b2g1Ing,
  b2g1Loc,
  b2g1Photo,
  b2g1Recipe,
} from "./arabBatch2Group1Shared";
import type { GeneratedRecipe } from "./generatedRecipeLibrary";

const FATTET_DAJAJ: GeneratedRecipe = b2g1Recipe({
  matchKeys: [
    "fattet dajaj",
    "fattet chicken",
    "chicken fatteh",
    "fatteh dajaj",
    "فتة الدجاج",
    "فتة دجاج",
    "فتّة الدجاج",
  ],
  canonicalTitle: "Fattet Dajaj",
  prepMinutes: 70,
  difficulty: "medium",
  servings: 3,
  mealTypes: ["main"],
  mealSlotRole: "dinner_complete",
  mealIntents: ["family_friendly", "special", "high_calorie"],
  proteinCategory: "chicken",
  budgetTier: "medium",
  suitability: ["guest_friendly", "everyday_host", "shareable"],
  moods: ["special", "everyday"],
  dietaryTags: ["contains_meat", "contains_dairy"],
  allergens: ["Gluten", "Dairy", "Nuts", "Sesame"],
  ingredientTokens: ["chicken", "pita", "yogurt", "tahini", "garlic", "pine nuts"],
  pantryIngredients: [
    { canonicalId: "chicken", role: "critical", tokens: ["chicken"] },
    { canonicalId: "pita", role: "critical", tokens: ["pita", "bread"] },
    { canonicalId: "yogurt", role: "critical", tokens: ["yogurt"] },
    { canonicalId: "tahini", role: "supporting", tokens: ["tahini"] },
  ],
  ingredients: [
    b2g1Ing("chicken", "Chicken pieces", "Hähnchenteile", "قطع دجاج", "Tavuk parçaları", "700 g, cooked and shredded", "700 g, gegart und gezupft", "700 غ مسلوق ومفتت", "700 g haşlanıp didiklenmiş"),
    b2g1Ing("pita", "Arabic pita / flatbread", "Pita / Fladenbrot", "خبز عربي", "Arap ekmeği", "3 pieces, crisped", "3 Stück, knusprig", "3 أرغفة محمّصة", "3 adet, çıtır"),
    b2g1Ing("yogurt", "Full-fat yogurt", "Vollfettjoghurt", "لبن رائب", "Yoğurt", "500 g", "500 g", "500 غرام", "500 g"),
    b2g1Ing("tahini", "Tahini", "Tahini", "طحينة", "Tahin", "3 tbsp", "3 EL", "3 ملاعق كبيرة", "3 yk"),
    b2g1Ing("garlic", "Garlic", "Knoblauch", "ثوم", "Sarımsak", "3 cloves, crushed", "3 Zehen", "3 فصوص مهروسة", "3 diş ezilmiş"),
    b2g1Ing("lemon", "Lemon juice", "Zitronensaft", "عصير ليمون", "Limon suyu", "2 tbsp", "2 EL", "ملعقتان", "2 yk"),
    b2g1Ing("pine-nuts", "Pine nuts", "Pinienkerne", "صنوبر", "Çam fıstığı", "3 tbsp, toasted in ghee", "3 EL in Butterschmalz geröstet", "3 ملاعق محمّصة بالسمن", "3 yk sadeyağda kavrulmuş"),
    b2g1Ing("ghee", "Ghee or butter", "Butterschmalz", "سمن أو زبدة", "Sadeyağ", "2 tbsp", "2 EL", "ملعقتان", "2 yk"),
    b2g1Ing("salt", "Salt", "Salz", "ملح", "Tuz", "to taste", "nach Geschmack", "حسب الذوق", "damak tadına göre"),
  ],
  localeCopy: {
    en: b2g1Loc(
      "Syrian chicken fatteh: crisp pita layered with shredded chicken and garlicky yogurt-tahini sauce, finished with sizzling pine nuts — distinct from fattet hummus.",
      "Syrian",
      ["Crisp the pita well so it stays crunchy under the sauce.", "Warm chicken before layering.", "Pour hot ghee with pine nuts last."],
      "Best assembled fresh. Components keep 2 days refrigerated.",
      [
        "Cook chicken until tender; shred and season lightly with salt.",
        "Toast or fry pita pieces until crisp.",
        "Whisk yogurt with tahini, crushed garlic, lemon and salt until smooth.",
        "Layer crisp pita in a deep dish, top with warm chicken, then yogurt sauce.",
        "Fry pine nuts in ghee until golden; pour over the fatteh and serve immediately.",
      ],
    ),
    de: b2g1Loc(
      "Syrische Hähnchen-Fatteh: knuspriges Pita mit Hähnchen und Knoblauch-Joghurt-Tahini, mit Pinienkernen — anders als Hummus-Fatteh.",
      "Syrisch",
      ["Pita gut knusprig rösten.", "Hähnchen warm schichten.", "Heißes Butterschmalz mit Pinienkernen zuletzt."],
      "Frisch anrichten. Komponenten 2 Tage kühlbar.",
      [
        "Hähnchen garen, zerzupfen und leicht salzen.",
        "Pita knusprig rösten oder braten.",
        "Joghurt mit Tahini, Knoblauch, Zitrone und Salz verrühren.",
        "Pita, warmes Hähnchen und Sauce schichten.",
        "Pinienkerne in Butterschmalz goldbraun rösten und darüber gießen; sofort servieren.",
      ],
    ),
    ar: b2g1Loc(
      "فتة دجاج سورية: خبز مقرمش مع دجاج مفتت ولبن وثوم وطحينة، تُختَم بصنوبر ساخن — متميزة عن فتة الحمص.",
      "سوري",
      ["حمّصي الخبز جيداً.", "ادفئي الدجاج قبل الرصّ.", "اسكبي السمن والصنوبر في الآخر."],
      "تُركَّب طازجة. المكوّنات يومان في الثلاجة.",
      [
        "اطبخي الدجاج حتى يطرى؛ فتّتيه ورشّي ملحاً خفيفاً.",
        "حمّصي أو اقلي الخبز حتى يقرمش.",
        "اخفقي اللبن مع الطحينة والثوم والليمون والملح.",
        "رصّي الخبز ثم الدجاج الدافئ ثم صلصة اللبن.",
        "حمّصي الصنوبر بالسمن واسكبيه فوق الفتة وقدّمي فوراً.",
      ],
    ),
    tr: b2g1Loc(
      "Suriye tavuklu fette: çıtır ekmek, didiklenmiş tavuk ve sarımsaklı yoğurt-tahin; üstünde kavrulmuş çam fıstığı — humus fette’den ayrı.",
      "Suriye",
      ["Ekmeği iyice çıtırlaştırın.", "Tavuğu sıcak katmanlayın.", "Sıcak sadeyağ ve çam fıstığını en son dökün."],
      "Taze birleştirin. Malzemeler 2 gün saklanır.",
      [
        "Tavuğu pişirip didikleyin, hafif tuzlayın.",
        "Ekmeği çıtır olana dek kızartın.",
        "Yoğurdu tahin, sarımsak, limon ve tuzla çırpın.",
        "Ekmek, sıcak tavuk ve sosu katmanlayın.",
        "Çam fıstığını sadeyağda kavurup üzerine dökün; hemen servis edin.",
      ],
    ),
  },
  naturalYield: {
    baseServingsMin: 3,
    baseServingsMax: 4,
    servingLabel: "Serves ~3 as a layered main",
    scalingNote: "Scale chicken, pita and yogurt together; keep garlic and lemon balanced.",
  },
  defaultRole: "main",
  canServeAsMain: false,
  photo: b2g1Photo(
    "Layered chicken fatteh with crisp pita, yogurt sauce and pine nuts.",
    "Deep dish layers as hero.",
    "Chicken fatteh — distinct from fattet hummus already in Batch 1.",
    "/assets/dishes/arab/fattet-dajaj.jpg",
  ),
});

const BASHA_ASAKRO: GeneratedRecipe = b2g1Recipe({
  matchKeys: [
    "basha wa asakro",
    "basha w asakro",
    "pasha and his soldiers",
    "باشا وعساكره",
    "الباشا وعساكره",
  ],
  canonicalTitle: "Basha wa Asakro",
  prepMinutes: 80,
  difficulty: "medium",
  servings: 3,
  mealTypes: ["main"],
  mealSlotRole: "dinner_complete",
  mealIntents: ["family_friendly", "special", "high_calorie"],
  proteinCategory: "mixed",
  budgetTier: "medium",
  suitability: ["guest_friendly", "everyday_host", "shareable"],
  moods: ["special"],
  dietaryTags: ["contains_meat", "contains_dairy"],
  allergens: ["Dairy", "Nuts"],
  ingredientTokens: ["eggplant", "minced meat", "yogurt", "garlic", "pine nuts", "tomato"],
  pantryIngredients: [
    { canonicalId: "eggplant", role: "critical", tokens: ["eggplant"] },
    { canonicalId: "minced-meat", role: "critical", tokens: ["minced meat"] },
    { canonicalId: "yogurt", role: "critical", tokens: ["yogurt"] },
  ],
  ingredients: [
    b2g1Ing("eggplant", "Eggplant", "Aubergine", "باذنجان", "Patlıcan", "2 large, sliced and fried", "2 große, Scheiben gebraten", "حبتان كبيرتان شرائح مقلية", "2 büyük, dilim kızartılmış"),
    b2g1Ing("minced-meat", "Minced lamb or beef", "Hackfleisch", "لحم مفروم", "Kıyma", "350 g, small kofta/meatballs", "350 g kleine Bällchen", "350 غ كرات صغيرة", "350 g küçük köfte"),
    b2g1Ing("tomato", "Tomato sauce", "Tomatensauce", "صلصة بندورة", "Domates sosu", "1.5 cups light sauce", "1,5 Tassen", "كوب ونصف خفيفة", "1,5 su bardağı"),
    b2g1Ing("yogurt", "Full-fat yogurt", "Vollfettjoghurt", "لبن رائب", "Yoğurt", "500 g", "500 g", "500 غرام", "500 g"),
    b2g1Ing("garlic", "Garlic", "Knoblauch", "ثوم", "Sarımsak", "4 cloves, crushed", "4 Zehen", "4 فصوص", "4 diş"),
    b2g1Ing("starch", "Cornstarch", "Maisstärke", "نشا", "Nişasta", "1 tbsp", "1 EL", "ملعقة كبيرة", "1 yk"),
    b2g1Ing("pine-nuts", "Pine nuts", "Pinienkerne", "صنوبر", "Çam fıstığı", "3 tbsp, toasted", "3 EL geröstet", "3 ملاعق محمّص", "3 yk kavrulmuş"),
    b2g1Ing("oil", "Oil", "Öl", "زيت", "Yağ", "for frying", "zum Braten", "للقلي", "kızartmak için"),
    b2g1Ing("salt", "Salt & pepper", "Salz & Pfeffer", "ملح وفلفل", "Tuz ve biber", "to taste", "nach Geschmack", "حسب الذوق", "damak tadına göre"),
  ],
  localeCopy: {
    en: b2g1Loc(
      "Basha wa asakro ('the pasha and his soldiers'): fried eggplant with small meatballs in tomato, finished with garlic yogurt — a Syrian celebration main, distinct from dawood basha.",
      "Syrian",
      ["Fry eggplant until soft and golden.", "Keep meatballs small ('soldiers').", "Temper yogurt gently over the assembled dish."],
      "Refrigerate up to 2 days; reheat gently.",
      [
        "Fry eggplant slices until tender; drain.",
        "Form and brown small meatballs; simmer briefly in light tomato sauce.",
        "Arrange eggplant in a dish, nestle meatballs and spoon tomato sauce around.",
        "Warm yogurt with cornstarch and garlic until lightly thick; pour over.",
        "Finish with toasted pine nuts and serve with rice.",
      ],
    ),
    de: b2g1Loc(
      "Basha wa Asakro: gebratene Aubergine mit kleinen Fleischbällchen in Tomate, mit Knoblauchjoghurt — anders als Dawood Basha.",
      "Syrisch",
      ["Aubergine weich goldbraun braten.", "Fleischbällchen klein halten.", "Joghurt sanft erhitzen."],
      "Bis 2 Tage kühlen; sanft erwärmen.",
      [
        "Auberginenscheiben braten und abtropfen.",
        "Kleine Fleischbällchen braten; kurz in Tomatensauce köcheln.",
        "Aubergine und Bällchen anrichten; Sauce darum.",
        "Joghurt mit Stärke und Knoblauch leicht eindicken; übergießen.",
        "Mit Pinienkernen und Reis servieren.",
      ],
    ),
    ar: b2g1Loc(
      "باشا وعساكره: باذنجان مقلي مع كرات لحم صغيرة وصلصة بندورة ولبن وثوم — طبق مناسبات سوري، متميز عن داوود باشا.",
      "سوري",
      ["اقلي الباذنجان حتى يطرى ويذهبّ.", "أبقي الكرات صغيرة (العساكر).", "سخّني اللبن بلطف."],
      "يُحفظ يومين؛ أعيدي التسخين بهدوء.",
      [
        "اقلي شرائح الباذنجان حتى تطرى؛ صفّيها.",
        "شكّلي كرات صغيرة وحمّريها؛ اتركيه تغلي قليلاً في صلصة بندورة خفيفة.",
        "رصّي الباذنجان والكرات واسكبي الصلصة حولها.",
        "سخّني اللبن مع النشا والثوم حتى يتكثّف قليلاً؛ اسكبيه فوق الطبق.",
        "زيّني بالصنوبر وقدّمي مع الرز.",
      ],
    ),
    tr: b2g1Loc(
      "Başa ve askerleri: kızarmış patlıcan, küçük köfteler, domates ve sarımsaklı yoğurt — Dawood Basha’dan ayrı Suriye ziyafet yemeği.",
      "Suriye",
      ["Patlıcanı yumuşak altın rengi kızartın.", "Köfteleri küçük tutun.", "Yoğurdu nazik ısıtın."],
      "2 güne kadar saklayın; hafif ısıtın.",
      [
        "Patlıcan dilimlerini kızartıp süzün.",
        "Küçük köfteleri kızartıp hafif domates sosunda kısaca pişirin.",
        "Patlıcan ve köfteleri dizin; sosu etrafına gezin.",
        "Yoğurdu nişasta ve sarımsakla koyulaştırıp üzerine dökün.",
        "Çam fıstığı ve pilavla servis edin.",
      ],
    ),
  },
  naturalYield: {
    baseServingsMin: 3,
    baseServingsMax: 4,
    servingLabel: "Serves ~3 with rice",
    scalingNote: "Scale eggplant, meatballs and yogurt together. Distinct from Dawood Basha.",
  },
  defaultRole: "main",
  canServeAsMain: false,
  photo: b2g1Photo(
    "Eggplant slices with small meatballs, tomato and yogurt sauce, pine nuts.",
    "Assembled dish as hero.",
    "Basha wa asakro — eggplant + meatball soldiers + yogurt; not dawood basha alone.",
    "/assets/dishes/arab/basha-wa-asakro.jpg",
  ),
});

const HARRAQ_ESBAO: GeneratedRecipe = b2g1Recipe({
  matchKeys: [
    "harraq esbao",
    "haraq osbao",
    "burnt finger lentils",
    "حراق إصبعه",
    "حرق إصبعه",
    "حراق اصبعه",
  ],
  canonicalTitle: "Harraq Esbao",
  prepMinutes: 75,
  difficulty: "medium",
  servings: 3,
  mealTypes: ["main", "stew"],
  mealSlotRole: "dinner_complete",
  mealIntents: ["family_friendly", "budget", "healthy"],
  proteinCategory: "legume",
  budgetTier: "low",
  suitability: ["everyday_host", "shareable"],
  moods: ["everyday"],
  dietaryTags: ["vegetarian_ok", "contains_dairy"],
  allergens: ["Gluten", "Dairy"],
  ingredientTokens: ["lentils", "pasta", "onion", "tamarind", "garlic", "yogurt"],
  pantryIngredients: [
    { canonicalId: "lentils", role: "critical", tokens: ["lentils"] },
    { canonicalId: "pasta", role: "supporting", tokens: ["pasta", "noodles"] },
    { canonicalId: "tamarind", role: "supporting", tokens: ["tamarind", "pomegranate"] },
  ],
  ingredients: [
    b2g1Ing("lentils", "Brown lentils", "Braune Linsen", "عدس بني", "Kahverengi mercimek", "1.5 cups (300 g)", "1,5 Tassen (300 g)", "كوب ونصف (300 غ)", "1,5 su bardağı (300 g)"),
    b2g1Ing("pasta", "Small pasta / broken noodles", "Kleine Nudeln", "معكرونة صغيرة / شعيرية", "Küçük makarna", "1 cup", "1 Tasse", "كوب", "1 su bardağı"),
    b2g1Ing("onion", "Onion", "Zwiebel", "بصل", "Soğan", "2 large, for crispy topping", "2 große", "حبتان كبيرتان", "2 büyük"),
    b2g1Ing("garlic", "Garlic", "Knoblauch", "ثوم", "Sarımsak", "4 cloves, for coriander-garlic oil", "4 Zehen", "4 فصوص", "4 diş"),
    b2g1Ing("coriander", "Ground coriander", "Koriander", "كزبرة", "Kişniş", "1.5 tsp", "1,5 TL", "ملعقة ونصف", "1,5 tk"),
    b2g1Ing("tamarind", "Tamarind or pomegranate molasses", "Tamarinde oder Granatapfelmelasse", "تمر هندي أو دبس رمان", "Demirhindi veya nar ekşisi", "2–3 tbsp, to taste", "2–3 EL", "2–3 ملاعق", "2–3 yk"),
    b2g1Ing("yogurt", "Yogurt, to serve", "Joghurt zum Servieren", "لبن للتقديم", "Yoğurt", "1 cup", "1 Tasse", "كوب", "1 su bardağı"),
    b2g1Ing("oil", "Oil", "Öl", "زيت", "Yağ", "for frying onions", "zum Braten", "لقلي البصل", "soğan için"),
    b2g1Ing("salt", "Salt & pepper", "Salz & Pfeffer", "ملح وفلفل", "Tuz ve biber", "to taste", "nach Geschmack", "حسب الذوق", "damak tadına göre"),
  ],
  localeCopy: {
    en: b2g1Loc(
      "Harraq esbao: Syrian lentil-and-pasta pot with sweet-sour tamarind, crispy onions and garlic-coriander oil — a vegetarian Damascus classic.",
      "Syrian",
      ["Cook lentils soft before adding pasta.", "Fry onions deep golden for the signature crunch.", "Balance tamarind/molasses to taste."],
      "Keeps 3 days; reheat with a splash of water. Add yogurt when serving.",
      [
        "Simmer lentils in water with salt until almost tender.",
        "Add small pasta and cook until soft; stew should be thick, not watery.",
        "Fry sliced onion until deep golden and crisp; reserve.",
        "Fry garlic with coriander in oil; stir most into the pot with tamarind/molasses.",
        "Serve topped with crispy onions, remaining garlic oil and yogurt.",
      ],
    ),
    de: b2g1Loc(
      "Harraq Esbao: syrischer Linsen-Nudel-Topf mit süß-saurer Tamarinde, Röstzwiebeln und Knoblauch-Koriander-Öl.",
      "Syrisch",
      ["Linsen zuerst weich kochen.", "Zwiebeln tiefgolden braten.", "Tamarinde abschmecken."],
      "3 Tage haltbar; mit etwas Wasser erwärmen. Joghurt beim Servieren.",
      [
        "Linsen mit Salz köcheln bis fast gar.",
        "Kleine Nudeln zugeben; dicklich einkochen.",
        "Zwiebeln tiefgolden knusprig braten.",
        "Knoblauch mit Koriander anbraten; mit Tamarinde unterheben.",
        "Mit Röstzwiebeln, Öl und Joghurt servieren.",
      ],
    ),
    ar: b2g1Loc(
      "حراق إصبعه: عدس ومعكرونة سورية بحموضة تمر هندي وبصل مقرمش وتقليلة ثوم وكزبرة — كلاسيكية دمشقية نباتية.",
      "سوري",
      ["اطبخي العدس حتى يطرى قبل المعكرونة.", "اقلي البصل ذهبياً عميقاً.", "وازني التمر الهندي حسب الذوق."],
      "3 أيام؛ أعيدي التسخين برشة ماء. اللبن عند التقديم.",
      [
        "اسلقي العدس بالماء والملح حتى يكاد ينضج.",
        "أضيفي المعكرونة الصغيرة واطبخي حتى يثخن القوام.",
        "اقلي البصل شرائح حتى يذهبّ ويقرمش.",
        "اقلِ الثوم مع الكزبرة؛ قلّبي معظمها مع التمر الهندي في القدر.",
        "قدّمي مع البصل المقرمش وبقية التقلية واللبن.",
      ],
    ),
    tr: b2g1Loc(
      "Harrak esbao: tatlı-ekşi demirhindili Suriye mercimek-makarna yemeği; çıtır soğan ve sarımsak-kişniş yağıyla.",
      "Suriye",
      ["Önce mercimeği yumuşatın.", "Soğanları koyu altın rengi kızartın.", "Demirhindiyi damak tadına göre ayarlayın."],
      "3 gün saklanır; biraz suyla ısıtın. Yoğurt serviste.",
      [
        "Mercimeği tuzlu suda neredeyse yumuşayana dek pişirin.",
        "Küçük makarnayı ekleyip koyu kıvama getirin.",
        "Soğanları koyu altın ve çıtır olana dek kızartın.",
        "Sarımsak ve kişnişi yağda kavurup demirhindiyle tencereye katın.",
        "Üzerine soğan, kalan yağ ve yoğurtla servis edin.",
      ],
    ),
  },
  naturalYield: {
    baseServingsMin: 3,
    baseServingsMax: 4,
    servingLabel: "Serves ~3 as a hearty pot",
    scalingNote: "Scale lentils and pasta together; keep tamarind and onion topping generous.",
  },
  defaultRole: "main",
  canServeAsMain: false,
  photo: b2g1Photo(
    "Bowl of Syrian lentil pasta stew with crispy onions and yogurt.",
    "Pot/bowl as hero with onion topping.",
    "Harraq esbao — lentils, pasta, tamarind, crispy onions.",
    "/assets/dishes/arab/harraq-esbao.jpg",
  ),
});

const MACARONA: GeneratedRecipe = b2g1Recipe({
  matchKeys: [
    "macarona bil lahmeh",
    "macarona bil lahm",
    "syrian pasta with meat",
    "معكرونة باللحمة",
    "معكرونة باللحم",
    "مكرونة باللحمة",
  ],
  canonicalTitle: "Macarona bil Lahmeh",
  prepMinutes: 55,
  difficulty: "easy",
  servings: 3,
  mealTypes: ["main"],
  mealSlotRole: "dinner_complete",
  mealIntents: ["family_friendly", "budget", "high_calorie"],
  proteinCategory: "lamb",
  budgetTier: "low",
  suitability: ["everyday_host", "shareable"],
  moods: ["everyday"],
  dietaryTags: ["contains_meat"],
  allergens: ["Gluten"],
  ingredientTokens: ["pasta", "minced meat", "tomato", "onion", "allspice"],
  pantryIngredients: [
    { canonicalId: "pasta", role: "critical", tokens: ["pasta", "macaroni"] },
    { canonicalId: "minced-meat", role: "critical", tokens: ["minced meat"] },
    { canonicalId: "tomato", role: "supporting", tokens: ["tomato"] },
  ],
  ingredients: [
    b2g1Ing("pasta", "Pasta (penne or macaroni)", "Pasta (Penne oder Makkaroni)", "معكرونة", "Makarna", "350 g", "350 g", "350 غرام", "350 g"),
    b2g1Ing("minced-meat", "Minced lamb or beef", "Hackfleisch", "لحم مفروم", "Kıyma", "400 g", "400 g", "400 غرام", "400 g"),
    b2g1Ing("tomato", "Tomato passata or grated tomato", "Passata oder geriebene Tomate", "بندورة مبشورة أو صلصة", "Domates", "2 cups + 1 tbsp paste", "2 Tassen + 1 EL Mark", "كوبان + ملعقة معجون", "2 su bardağı + 1 yk salça"),
    b2g1Ing("onion", "Onion", "Zwiebel", "بصل", "Soğan", "1, chopped", "1, gehackt", "حبة مفرومة", "1, doğranmış"),
    b2g1Ing("garlic", "Garlic", "Knoblauch", "ثوم", "Sarımsak", "3 cloves", "3 Zehen", "3 فصوص", "3 diş"),
    b2g1Ing("spice", "Allspice & cinnamon", "Piment & Zimt", "بهار وقرفة", "Yenibahar ve tarçın", "1.5 tsp + pinch cinnamon", "1,5 TL + Prise Zimt", "ملعقة ونصف + رشة قرفة", "1,5 tk + bir tutam tarçın"),
    b2g1Ing("oil", "Oil", "Öl", "زيت", "Yağ", "3 tbsp", "3 EL", "3 ملاعق", "3 yk"),
    b2g1Ing("salt", "Salt & pepper", "Salz & Pfeffer", "ملح وفلفل", "Tuz ve biber", "to taste", "nach Geschmack", "حسب الذوق", "damak tadına göre"),
  ],
  localeCopy: {
    en: b2g1Loc(
      "Syrian macarona bil lahmeh: pasta tossed with spiced minced meat in tomato sauce — everyday Levantine comfort, not Italian ragù.",
      "Syrian",
      ["Brown the meat well with allspice.", "Sauce should coat the pasta generously.", "Optional bake with a little cheese is not required for the classic."],
      "Keeps 3 days refrigerated.",
      [
        "Boil pasta in salted water until just tender; drain.",
        "Brown onion and minced meat in oil; season with allspice, cinnamon, salt and pepper.",
        "Add garlic, tomato and paste; simmer until rich.",
        "Toss pasta with the meat sauce.",
        "Serve hot as a family main.",
      ],
    ),
    de: b2g1Loc(
      "Syrische Macarona bil Lahmeh: Pasta mit gewürztem Hack in Tomatensauce — levantinischer Alltag, kein italienisches Ragù.",
      "Syrisch",
      ["Hack mit Piment gut anbräunen.", "Sauce soll die Pasta gut umhüllen.", "Überbacken optional, nicht klassisch nötig."],
      "3 Tage kühlbar.",
      [
        "Pasta in Salzwasser al dente kochen; abgießen.",
        "Zwiebel und Hack anbräunen; mit Piment, Zimt, Salz und Pfeffer würzen.",
        "Knoblauch, Tomate und Mark zugeben; einköcheln.",
        "Pasta mit der Fleischsauce vermengen.",
        "Heiß als Familienessen servieren.",
      ],
    ),
    ar: b2g1Loc(
      "معكرونة باللحمة سورية: معكرونة مع لحم مفروم متبّل وصلصة بندورة — راحة شامية يومية، لا راغو إيطالي.",
      "سوري",
      ["حمّري اللحم جيداً بالبهار.", "الصلصة تغطّي المعكرونة بسخاء.", "الخبز بالجبن اختياري وليس كلاسيكياً ضرورياً."],
      "3 أيام في الثلاجة.",
      [
        "اسلقي المعكرونة بماء مملح حتى تطرى؛ صفّيها.",
        "حمّري البصل واللحم؛ تبّلي بالبهار والقرفة والملح والفلفل.",
        "أضيفي الثوم والبندورة والمعجون؛ اتركيه يغني.",
        "قلّبي المعكرونة مع صلصة اللحم.",
        "قدّمي ساخنة كطبق عائلي.",
      ],
    ),
    tr: b2g1Loc(
      "Suriye usulü kıymalı makarna: baharatlı kıyma ve domates soslu — İtalyan ragù değil, Levanten ev yemeği.",
      "Suriye",
      ["Kıymayı yenibaharla iyice kavurun.", "Sos makarnayı bolca kaplasın.", "Peynirli fırınlama klasik için şart değil."],
      "3 gün saklanır.",
      [
        "Makarnayı tuzlu suda haşlayıp süzün.",
        "Soğan ve kıymayı kavurup yenibahar, tarçın, tuz ve biberle tatlandırın.",
        "Sarımsak, domates ve salçayı ekleyip koyulaştırın.",
        "Makarnayı et sosuyla karıştırın.",
        "Sıcak aile yemeği olarak servis edin.",
      ],
    ),
  },
  naturalYield: {
    baseServingsMin: 3,
    baseServingsMax: 4,
    servingLabel: "Serves ~3 as a pasta main",
    scalingNote: "Scale pasta and minced meat together; keep Levantine spices, not Italian herbs.",
  },
  defaultRole: "main",
  canServeAsMain: false,
  photo: b2g1Photo(
    "Bowl of Syrian pasta with minced meat tomato sauce.",
    "Pasta bowl as hero.",
    "Macarona bil lahmeh — Syrian spiced meat pasta, not Italian.",
    "/assets/dishes/arab/macarona-bil-lahmeh.jpg",
  ),
});

const BEET_MUTABBAL: GeneratedRecipe = b2g1Recipe({
  matchKeys: [
    "beetroot mutabbal",
    "beet mutabbal",
    "mutabbal shamandar",
    "متبل شمندر",
    "متبل الشمندر",
    "متبل بنجر",
  ],
  canonicalTitle: "Beetroot Mutabbal",
  prepMinutes: 40,
  difficulty: "easy",
  servings: 3,
  mealTypes: ["side"],
  mealSlotRole: "side_component",
  mealIntents: ["healthy", "budget", "family_friendly"],
  proteinCategory: "vegetable",
  budgetTier: "low",
  suitability: ["everyday_host", "guest_friendly", "shareable"],
  moods: ["everyday", "quick"],
  dietaryTags: ["vegetarian_ok", "vegan_ok"],
  allergens: ["Sesame"],
  ingredientTokens: ["beetroot", "tahini", "garlic", "lemon", "olive oil"],
  pantryIngredients: [
    { canonicalId: "beetroot", role: "critical", tokens: ["beetroot", "beet"] },
    { canonicalId: "tahini", role: "critical", tokens: ["tahini"] },
    { canonicalId: "lemon", role: "supporting", tokens: ["lemon"] },
  ],
  ingredients: [
    b2g1Ing("beetroot", "Beetroot", "Rote Bete", "شمندر / بنجر", "Pancar", "400 g cooked, peeled", "400 g gekocht, geschält", "400 غ مسلوق ومقشّر", "400 g haşlanmış soyulmuş"),
    b2g1Ing("tahini", "Tahini", "Tahini", "طحينة", "Tahin", "4 tbsp", "4 EL", "4 ملاعق", "4 yk"),
    b2g1Ing("garlic", "Garlic", "Knoblauch", "ثوم", "Sarımsak", "1–2 cloves", "1–2 Zehen", "1–2 فصوص", "1–2 diş"),
    b2g1Ing("lemon", "Lemon juice", "Zitronensaft", "عصير ليمون", "Limon suyu", "2–3 tbsp", "2–3 EL", "2–3 ملاعق", "2–3 yk"),
    b2g1Ing("olive-oil", "Olive oil", "Olivenöl", "زيت زيتون", "Zeytinyağı", "2 tbsp + drizzle", "2 EL", "ملعقتان + رشة", "2 yk + gezdirme"),
    b2g1Ing("salt", "Salt", "Salz", "ملح", "Tuz", "to taste", "nach Geschmack", "حسب الذوق", "damak tadına göre"),
  ],
  localeCopy: {
    en: b2g1Loc(
      "Beetroot mutabbal: smooth roasted or boiled beet dip with tahini, garlic and lemon — a bright mezze, distinct from eggplant baba ghanouj.",
      "Syrian",
      ["Blend until creamy but not watery.", "Balance tahini and lemon.", "Serve cool with bread."],
      "Keeps 3 days refrigerated.",
      [
        "Chop cooked beetroot and blend or mash with tahini, garlic, lemon, olive oil and salt.",
        "Adjust thickness with a spoon of cold water if needed.",
        "Taste for lemon and salt.",
        "Spoon into a bowl, drizzle olive oil, and serve with flatbread.",
      ],
    ),
    de: b2g1Loc(
      "Rote-Bete-Mutabbal: cremiger Rote-Bete-Dip mit Tahini, Knoblauch und Zitrone — anders als Auberginen-Baba Ghanouj.",
      "Syrisch",
      ["Cremig pürieren, nicht wässrig.", "Tahini und Zitrone ausbalancieren.", "Kühl mit Brot."],
      "3 Tage kühlbar.",
      [
        "Gekochte Rote Bete mit Tahini, Knoblauch, Zitrone, Öl und Salz pürieren.",
        "Bei Bedarf mit etwas kaltem Wasser verdünnen.",
        "Mit Zitrone und Salz abschmecken.",
        "Anrichten, Öl beträufeln, mit Fladenbrot servieren.",
      ],
    ),
    ar: b2g1Loc(
      "متبل شمندر: متبل ناعم من الشمندر بالطحينة والثوم والليمون — مقبلات مشرقة، متميز عن بابا غنوج الباذنجان.",
      "سوري",
      ["اخلطي كريمي دون ماء زائد.", "وازني الطحينة والليمون.", "قدّمي بارداً مع الخبز."],
      "3 أيام في الثلاجة.",
      [
        "اهرسي أو اخلطي الشمندر المسلوق مع الطحينة والثوم والليمون والزيت والملح.",
        "خفّفي بملعقة ماء بارد إن لزم.",
        "ذوقّي الليمون والملح.",
        "اسكبي في صحن ورشّي زيتاً وقدّمي مع خبز.",
      ],
    ),
    tr: b2g1Loc(
      "Pancar mutabbalı: tahinli, sarımsaklı, limonlu pürüzsüz pancar mezesi — patlıcan baba ghanouj’dan ayrı.",
      "Suriye",
      ["Kremamsı ama sulu olmasın.", "Tahin ve limonu dengeleyin.", "Soğuk ekmekle servis edin."],
      "3 gün saklanır.",
      [
        "Haşlanmış pancarı tahin, sarımsak, limon, yağ ve tuzla ezip karıştırın.",
        "Gerekirse soğuk suyla inceltin.",
        "Limon ve tuzu ayarlayın.",
        "Kaseye alıp zeytinyağı gezdirin; ekmekle servis edin.",
      ],
    ),
  },
  naturalYield: {
    baseServingsMin: 3,
    baseServingsMax: 4,
    servingLabel: "Serves 3–4 as mezze",
    scalingNote: "Scale beetroot and tahini together. Distinct from eggplant Baba Ghanouj.",
  },
  defaultRole: "side",
  canServeAsMain: false,
  photo: b2g1Photo(
    "Pink beetroot mutabbal dip with olive oil in a shallow bowl.",
    "Dip bowl as hero.",
    "Beetroot mutabbal — not eggplant baba/mutabbal.",
    "/assets/dishes/arab/beetroot-mutabbal.jpg",
  ),
});

const POTATO_SALAD: GeneratedRecipe = b2g1Recipe({
  matchKeys: [
    "syrian boiled potato salad",
    "potato salad onion tomato parsley",
    "salatet batata",
    "سلطة بطاطا مسلوقة",
    "سلطة بطاطا مع بصل وبندورة وبقدونس",
    "سلطة البطاطا السورية",
  ],
  canonicalTitle: "Syrian Boiled Potato Salad",
  prepMinutes: 35,
  difficulty: "easy",
  servings: 3,
  mealTypes: ["salad", "side"],
  mealSlotRole: "side_component",
  mealIntents: ["healthy", "budget", "quick", "family_friendly"],
  proteinCategory: "vegetable",
  budgetTier: "low",
  suitability: ["everyday_host", "shareable"],
  moods: ["everyday", "quick"],
  dietaryTags: ["vegetarian_ok", "vegan_ok"],
  allergens: [],
  ingredientTokens: ["potato", "onion", "tomato", "parsley", "lemon", "olive oil"],
  pantryIngredients: [
    { canonicalId: "potato", role: "critical", tokens: ["potato"] },
    { canonicalId: "tomato", role: "supporting", tokens: ["tomato"] },
    { canonicalId: "onion", role: "supporting", tokens: ["onion"] },
    { canonicalId: "parsley", role: "supporting", tokens: ["parsley"] },
  ],
  ingredients: [
    b2g1Ing("potato", "Potatoes", "Kartoffeln", "بطاطا", "Patates", "600 g, boiled and cubed", "600 g, gekocht gewürfelt", "600 غ مسلوقة مكعّبات", "600 g haşlanmış küp"),
    b2g1Ing("onion", "Onion", "Zwiebel", "بصل", "Soğan", "1 small, thinly sliced", "1 kleine, dünn", "حبة صغيرة شرائح رفيعة", "1 küçük ince dilim"),
    b2g1Ing("tomato", "Tomatoes", "Tomaten", "بندورة", "Domates", "2, diced", "2, gewürfelt", "حبتان مقطّعتان", "2, küp"),
    b2g1Ing("parsley", "Flat-leaf parsley", "Petersilie", "بقدونس", "Maydanoz", "1/2 cup chopped", "1/2 Tasse", "نصف كوب مفروم", "1/2 su bardağı"),
    b2g1Ing("lemon", "Lemon juice", "Zitronensaft", "عصير ليمون", "Limon suyu", "3 tbsp", "3 EL", "3 ملاعق", "3 yk"),
    b2g1Ing("olive-oil", "Olive oil", "Olivenöl", "زيت زيتون", "Zeytinyağı", "4 tbsp", "4 EL", "4 ملاعق", "4 yk"),
    b2g1Ing("salt", "Salt & pepper", "Salz & Pfeffer", "ملح وفلفل", "Tuz ve biber", "to taste", "nach Geschmack", "حسب الذوق", "damak tadına göre"),
  ],
  localeCopy: {
    en: b2g1Loc(
      "Syrian boiled potato salad with onion, tomato and parsley in lemon-olive oil — a simple home side, not German Kartoffelsalat.",
      "Syrian",
      ["Dress potatoes while slightly warm.", "Keep onion thin and not overpowering.", "Plenty of parsley and lemon."],
      "Best same day; keeps 2 days refrigerated.",
      [
        "Boil potatoes until tender; cool slightly and cube.",
        "Toss with sliced onion, diced tomato and chopped parsley.",
        "Dress with lemon juice, olive oil, salt and pepper.",
        "Rest 10 minutes and serve at room temperature.",
      ],
    ),
    de: b2g1Loc(
      "Syrischer Kartoffelsalat mit Zwiebel, Tomate und Petersilie in Zitrone-Olivenöl — kein deutscher Kartoffelsalat.",
      "Syrisch",
      ["Kartoffeln leicht warm marinieren.", "Zwiebel dünn halten.", "Viel Petersilie und Zitrone."],
      "Am besten am selben Tag; 2 Tage kühlbar.",
      [
        "Kartoffeln garen, leicht abkühlen, würfeln.",
        "Mit Zwiebel, Tomate und Petersilie mischen.",
        "Mit Zitrone, Öl, Salz und Pfeffer anmachen.",
        "10 Min. ziehen; Zimmertemperatur servieren.",
      ],
    ),
    ar: b2g1Loc(
      "سلطة بطاطا مسلوقة سورية مع بصل وبندورة وبقدونس بليمون وزيت زيتون — جانب بيتي بسيط، لا سلطة بطاطا ألمانية.",
      "سوري",
      ["تبّلي البطاطا وهي دافئة قليلاً.", "أبقي البصل رفيعاً.", "بقدونس وليمون بوفرة."],
      "الأفضل نفس اليوم؛ يومان في الثلاجة.",
      [
        "اسلقي البطاطا حتى تطرى؛ برّديها قليلاً وقطّعيها مكعّبات.",
        "قلّبي مع البصل والشرائح والبندورة والبقدونس.",
        "تبّلي بالليمون وزيت الزيتون والملح والفلفل.",
        "اتركيها 10 دقائق وقدّمي بدرجة حرارة الغرفة.",
      ],
    ),
    tr: b2g1Loc(
      "Suriye usulü haşlanmış patates salatası: soğan, domates, maydanoz, limon-zeytinyağı — Alman Kartoffelsalat değil.",
      "Suriye",
      ["Patatesi hafif ılıyken soslayın.", "Soğanı ince tutun.", "Bol maydanoz ve limon."],
      "Aynı gün en iyisi; 2 gün saklanır.",
      [
        "Patatesleri haşlayıp biraz soğutup küp doğrayın.",
        "Soğan, domates ve maydanozla karıştırın.",
        "Limon, zeytinyağı, tuz ve biberle soslayın.",
        "10 dk dinlendirip oda sıcaklığında servis edin.",
      ],
    ),
  },
  naturalYield: {
    baseServingsMin: 3,
    baseServingsMax: 4,
    servingLabel: "Serves 3–4 as a side",
    scalingNote: "Scale potatoes and dressing vegetables together.",
  },
  defaultRole: "side",
  canServeAsMain: false,
  photo: b2g1Photo(
    "Syrian potato salad with tomato, onion and parsley, lemon dressing.",
    "Salad bowl as hero.",
    "Syrian potato-tomato-parsley salad — not German potato salad.",
    "/assets/dishes/arab/syrian-boiled-potato-salad.jpg",
  ),
});

export const ARAB_BATCH_2_GROUP_2_A: GeneratedRecipe[] = [
  FATTET_DAJAJ,
  BASHA_ASAKRO,
  HARRAQ_ESBAO,
  MACARONA,
  BEET_MUTABBAL,
  POTATO_SALAD,
];
