/**
 * Arab Batch 2 Group 2B — recipes 23–30 (Syrian stews + Maghreb + Lebanese).
 * Studio draft sources only. No images.
 */

import {
  B2_REGION_LEBANESE,
  B2_REGION_MOROCCAN,
  B2_REGION_TUNISIAN,
  b2g1Ing,
  b2g1Loc,
  b2g1Photo,
  b2g1Recipe,
  b2Recipe,
} from "./arabBatch2Group1Shared";
import type { GeneratedRecipe } from "./generatedRecipeLibrary";

const DAWOOD_BASHA: GeneratedRecipe = b2g1Recipe({
  matchKeys: [
    "dawood basha",
    "daoud basha",
    "david pasha meatballs",
    "داوود باشا",
    "داود باشا",
  ],
  canonicalTitle: "Dawood Basha",
  prepMinutes: 70,
  difficulty: "medium",
  servings: 3,
  mealTypes: ["main", "stew"],
  mealSlotRole: "dinner_complete",
  mealIntents: ["family_friendly", "special", "high_calorie"],
  proteinCategory: "lamb",
  budgetTier: "medium",
  suitability: ["guest_friendly", "everyday_host", "shareable"],
  moods: ["everyday", "special"],
  dietaryTags: ["contains_meat"],
  allergens: ["Nuts"],
  ingredientTokens: ["minced meat", "tomato", "onion", "pine nuts", "allspice"],
  pantryIngredients: [
    { canonicalId: "minced-meat", role: "critical", tokens: ["minced meat"] },
    { canonicalId: "tomato", role: "critical", tokens: ["tomato"] },
    { canonicalId: "onion", role: "supporting", tokens: ["onion"] },
  ],
  ingredients: [
    b2g1Ing("minced-meat", "Minced lamb or beef", "Hackfleisch", "لحم مفروم", "Kıyma", "500 g", "500 g", "500 غرام", "500 g"),
    b2g1Ing("onion", "Onion", "Zwiebel", "بصل", "Soğan", "1 in meatballs + 1 in sauce", "1 in Bällchen + 1 in Sauce", "حبة في الكرات + حبة في الصلصة", "1 köftede + 1 sosta"),
    b2g1Ing("tomato", "Tomatoes", "Tomaten", "بندورة", "Domates", "4 grated + 1 tbsp paste", "4 gerieben + 1 EL Mark", "4 مبشورة + ملعقة معجون", "4 rendelenmiş + 1 yk salça"),
    b2g1Ing("pine-nuts", "Pine nuts", "Pinienkerne", "صنوبر", "Çam fıstığı", "3 tbsp, in meatballs", "3 EL in Bällchen", "3 ملاعق في الكرات", "3 yk köftede"),
    b2g1Ing("spice", "Allspice & cinnamon", "Piment & Zimt", "بهار وقرفة", "Yenibahar ve tarçın", "1.5 tsp + 1/2 tsp", "1,5 + 1/2 TL", "ملعقة ونصف + نصف", "1,5 + 1/2 tk"),
    b2g1Ing("garlic", "Garlic", "Knoblauch", "ثوم", "Sarımsak", "3 cloves", "3 Zehen", "3 فصوص", "3 diş"),
    b2g1Ing("oil", "Oil", "Öl", "زيت", "Yağ", "3 tbsp", "3 EL", "3 ملاعق", "3 yk"),
    b2g1Ing("salt", "Salt & pepper", "Salz & Pfeffer", "ملح وفلفل", "Tuz ve biber", "to taste", "nach Geschmack", "حسب الذوق", "damak tadına göre"),
  ],
  localeCopy: {
    en: b2g1Loc(
      "Dawood basha: Syrian meatballs with pine nuts simmered in tomato sauce — served with rice; distinct from basha wa asakro (eggplant layers).",
      "Syrian",
      ["Toast pine nuts before mixing into the meat.", "Brown meatballs then simmer in sauce.", "Sauce should be rich but spoonable."],
      "Keeps 3 days; reheat gently with rice.",
      [
        "Mix minced meat with grated onion, toasted pine nuts, spices, salt and pepper; form meatballs.",
        "Brown meatballs in oil; set aside.",
        "Make tomato sauce with onion, garlic, grated tomato and paste.",
        "Return meatballs to the sauce and simmer until cooked through.",
        "Serve hot with plain or vermicelli rice.",
      ],
    ),
    de: b2g1Loc(
      "Dawood Basha: syrische Fleischbällchen mit Pinienkernen in Tomatensauce — mit Reis; anders als Basha wa Asakro.",
      "Syrisch",
      ["Pinienkerne rösten.", "Bällchen anbraten, dann in der Sauce köcheln.", "Sauce reichhaltig halten."],
      "3 Tage haltbar; mit Reis erwärmen.",
      [
        "Hack mit Zwiebel, Pinienkernen und Gewürzen mischen; Bällchen formen.",
        "Anbraten und beiseitestellen.",
        "Tomatensauce mit Zwiebel, Knoblauch und Tomate bereiten.",
        "Bällchen zurückgeben und gar köcheln.",
        "Heiß mit Reis servieren.",
      ],
    ),
    ar: b2g1Loc(
      "داوود باشا: كرات لحم سورية بالصنوبر في صلصة بندورة — مع الرز؛ متميزة عن باشا وعساكره بطبقات الباذنجان.",
      "سوري",
      ["حمّصي الصنوبر قبل خلطه باللحم.", "حمّري الكرات ثم اتركيه تغلي في الصلصة.", "الصلصة غنية وملعقية."],
      "3 أيام؛ أعيدي التسخين مع الرز.",
      [
        "اخلطي اللحم مع البصل المبشور والصنوبر والبهار؛ شكّلي كرات.",
        "حمّري الكرات في الزيت؛ أبعديها.",
        "حضّري صلصة البندورة بالبصل والثوم والمعجون.",
        "أعيدي الكرات واتركيه تغلي حتى تنضج.",
        "قدّمي ساخنة مع أرز أبيض أو بالشعيرية.",
      ],
    ),
    tr: b2g1Loc(
      "Davud Paşa: çam fıstıklı Suriye köftesi domates sosunda — pilavla; Basha wa Asakro’dan (patlıcanlı) ayrı.",
      "Suriye",
      ["Çam fıstığını kıymaya katmadan kavurun.", "Köfteleri kızartıp sosta pişirin.", "Sos zengin ama akışkan olsun."],
      "3 gün saklanır; pilavla ısıtın.",
      [
        "Kıymayı soğan, çam fıstığı ve baharatla yoğurup köfte yapın.",
        "Kızartıp kenara alın.",
        "Soğan, sarımsak ve domatesten sos yapın.",
        "Köfteleri sosa ekleyip pişirin.",
        "Sıcak pilavla servis edin.",
      ],
    ),
  },
  naturalYield: {
    baseServingsMin: 3,
    baseServingsMax: 4,
    servingLabel: "Serves ~3 with rice",
    scalingNote: "Scale meatballs and tomato sauce together. Distinct from Basha wa Asakro.",
  },
  defaultRole: "main",
  canServeAsMain: false,
  photo: b2g1Photo(
    "Syrian dawood basha meatballs in tomato sauce with pine nuts.",
    "Meatballs in sauce as hero.",
    "Dawood basha meatballs — not basha wa asakro eggplant dish.",
    "/assets/dishes/arab/dawood-basha.jpg",
  ),
});

const STUFFED_CABBAGE: GeneratedRecipe = b2g1Recipe({
  matchKeys: [
    "syrian stuffed cabbage stew",
    "malfouf mahshi stew",
    "cabbage rolls lemon garlic",
    "يخنة ملفوف محشي",
    "ملفوف محشي بالثوم والحامض",
    "محشي ملفوف سوري",
  ],
  canonicalTitle: "Syrian Stuffed Cabbage Stew",
  prepMinutes: 110,
  difficulty: "medium",
  servings: 3,
  mealTypes: ["main", "stew"],
  mealSlotRole: "dinner_complete",
  mealIntents: ["family_friendly", "special", "high_calorie"],
  proteinCategory: "mixed",
  budgetTier: "medium",
  suitability: ["guest_friendly", "everyday_host", "shareable"],
  moods: ["special", "everyday"],
  dietaryTags: ["contains_meat"],
  allergens: [],
  ingredientTokens: ["cabbage", "rice", "minced meat", "garlic", "lemon"],
  pantryIngredients: [
    { canonicalId: "cabbage", role: "critical", tokens: ["cabbage"] },
    { canonicalId: "rice", role: "critical", tokens: ["rice"] },
    { canonicalId: "minced-meat", role: "critical", tokens: ["minced meat"] },
    { canonicalId: "garlic", role: "supporting", tokens: ["garlic"] },
    { canonicalId: "lemon", role: "supporting", tokens: ["lemon"] },
  ],
  ingredients: [
    b2g1Ing("cabbage", "White cabbage", "Weißkohl", "ملفوف أبيض", "Beyaz lahana", "1 medium head", "1 mittelgroßer Kopf", "رأس متوسط", "1 orta boy baş"),
    b2g1Ing("rice", "Rice", "Reis", "أرز", "Pirinç", "1 cup (200 g)", "1 Tasse (200 g)", "كوب (200 غ)", "1 su bardağı (200 g)"),
    b2g1Ing("minced-meat", "Minced lamb or beef", "Hackfleisch", "لحم مفروم", "Kıyma", "350 g", "350 g", "350 غرام", "350 g"),
    b2g1Ing("garlic", "Garlic", "Knoblauch", "ثوم", "Sarımsak", "8–10 cloves, for broth", "8–10 Zehen", "8–10 فصوص للمرق", "8–10 diş"),
    b2g1Ing("lemon", "Lemon juice", "Zitronensaft", "عصير ليمون / حامض", "Limon suyu", "1/3–1/2 cup", "1/3–1/2 Tasse", "ثلث إلى نصف كوب", "1/3–1/2 su bardağı"),
    b2g1Ing("mint", "Dried mint", "Getrocknete Minze", "نعناع يابس", "Kuru nane", "1 tsp optional", "1 TL optional", "ملعقة اختيارية", "1 tk isteğe bağlı"),
    b2g1Ing("spice", "Allspice", "Piment", "بهار حلو", "Yenibahar", "1 tsp", "1 TL", "ملعقة صغيرة", "1 tk"),
    b2g1Ing("oil", "Oil or ghee", "Öl oder Butterschmalz", "زيت أو سمن", "Yağ veya sadeyağ", "2 tbsp", "2 EL", "ملعقتان", "2 yk"),
    b2g1Ing("salt", "Salt & pepper", "Salz & Pfeffer", "ملح وفلفل", "Tuz ve biber", "to taste", "nach Geschmack", "حسب الذوق", "damak tadına göre"),
  ],
  localeCopy: {
    en: b2g1Loc(
      "Syrian stuffed cabbage stew: cabbage rolls filled with rice and meat, simmered with abundant garlic and lemon — a sharp, comforting Levantine pot.",
      "Syrian",
      ["Blanch cabbage leaves so they roll easily.", "Do not overfill — rice expands.", "Garlic-lemon broth is the dish’s signature."],
      "Keeps 3 days; flavour improves next day.",
      [
        "Blanch cabbage leaves; trim thick ribs.",
        "Mix rinsed rice with minced meat, allspice, salt and pepper.",
        "Roll leaves snugly and arrange in a pot.",
        "Cover with water, crushed garlic, lemon juice, mint and salt; weight with a plate.",
        "Simmer gently until rice and cabbage are tender; serve hot.",
      ],
    ),
    de: b2g1Loc(
      "Syrischer gefüllter Kohl-Eintopf: Kohlrouladen mit Reis und Fleisch in Knoblauch-Zitronen-Brühe.",
      "Syrisch",
      ["Kohlblätter blanchieren.", "Nicht zu voll füllen.", "Knoblauch-Zitrone ist das Markenzeichen."],
      "3 Tage haltbar; am nächsten Tag besser.",
      [
        "Kohlblätter blanchieren; dicke Rippen entfernen.",
        "Reis mit Hack, Piment, Salz und Pfeffer mischen.",
        "Rollen und im Topf schichten.",
        "Mit Wasser, Knoblauch, Zitrone, Minze und Salz bedecken; mit Teller beschweren.",
        "Sanft garen bis Reis und Kohl zart sind.",
      ],
    ),
    ar: b2g1Loc(
      "يخنة ملفوف محشي سورية: ملفوف محشو بالأرز واللحم يُطهى بثوم وحامض وفير — قدر شامي حادّ ومريح.",
      "سوري",
      ["اسلقي أوراق الملفوف ليسهل لفّها.", "لا تملئي بإفراط.", "مرق الثوم والحامض هو هوية الطبق."],
      "3 أيام؛ تتحسّن في اليوم التالي.",
      [
        "اسلقي أوراق الملفوف وقصّي العروق الغليظة.",
        "اخلطي الأرز المغسول مع اللحم المفروم والبهار والملح والفلفل.",
        "لفّي بإحكام ورصّي في القدر.",
        "غطّي بالماء والثوم المهروس وعصير الليمون والنعناع والملح؛ ثقّلي بصحن.",
        "اتركيه يغلي بهدوء حتى ينضج الأرز والملفوف؛ قدّمي ساخنة.",
      ],
    ),
    tr: b2g1Loc(
      "Suriye usulü lahana sarması yahnisi: pirinç-etli sarmalar bol sarımsak ve limonla — keskin Levanten tencere yemeği.",
      "Suriye",
      ["Lahana yapraklarını haşlayın.", "İçi fazla doldurmayın.", "Sarımsak-limon suyu yemeğin imzasıdır."],
      "3 gün saklanır; ertesi gün daha iyi.",
      [
        "Lahana yapraklarını haşlayıp kalın damarları kesin.",
        "Yıkanmış pirinci kıyma, yenibahar, tuz ve biberle karıştırın.",
        "Sıkı sarın ve tencereye dizin.",
        "Su, ezilmiş sarımsak, limon, nane ve tuz ekleyip tabakla bastırın.",
        "Pirinç ve lahana yumuşayana dek hafifçe pişirin; sıcak servis edin.",
      ],
    ),
  },
  naturalYield: {
    baseServingsMin: 3,
    baseServingsMax: 4,
    servingLabel: "Serves ~3 as a stew main",
    scalingNote: "Scale cabbage rolls and garlic-lemon broth together. Distinct from mixed Iraqi dolma.",
  },
  defaultRole: "main",
  canServeAsMain: false,
  photo: b2g1Photo(
    "Pot of Syrian stuffed cabbage rolls in garlic-lemon broth.",
    "Stew pot as hero.",
    "Syrian malfouf with garlic and lemon — not generic cabbage rolls.",
    "/assets/dishes/arab/syrian-stuffed-cabbage-stew.jpg",
  ),
});

const CAULIFLOWER_MEAT: GeneratedRecipe = b2g1Recipe({
  matchKeys: [
    "syrian cauliflower with meat",
    "arnabeet bil lahmeh",
    "zahra bil lahmeh",
    "زهرة باللحمة والثوم",
    "قرنبيط باللحمة",
    "زهرة باللحم والثوم مع الرز",
  ],
  canonicalTitle: "Syrian Cauliflower with Meat",
  prepMinutes: 70,
  difficulty: "medium",
  servings: 3,
  mealTypes: ["main", "stew"],
  mealSlotRole: "dinner_complete",
  mealIntents: ["family_friendly", "budget", "high_calorie"],
  proteinCategory: "lamb",
  budgetTier: "medium",
  suitability: ["everyday_host", "shareable"],
  moods: ["everyday"],
  dietaryTags: ["contains_meat"],
  allergens: [],
  ingredientTokens: ["cauliflower", "meat", "garlic", "tomato", "rice"],
  pantryIngredients: [
    { canonicalId: "cauliflower", role: "critical", tokens: ["cauliflower"] },
    { canonicalId: "meat", role: "critical", tokens: ["meat", "lamb"] },
    { canonicalId: "garlic", role: "supporting", tokens: ["garlic"] },
    { canonicalId: "rice", role: "supporting", tokens: ["rice"] },
  ],
  ingredients: [
    b2g1Ing("cauliflower", "Cauliflower", "Blumenkohl", "زهرة / قرنبيط", "Karnabahar", "1 medium head, florets", "1 Kopf, Röschen", "رأس متوسط زهيرات", "1 orta boy, çiçek"),
    b2g1Ing("meat", "Lamb or beef cubes", "Fleischwürfel", "لحم مكعّبات", "Kuşbaşı et", "400 g", "400 g", "400 غرام", "400 g"),
    b2g1Ing("garlic", "Garlic", "Knoblauch", "ثوم", "Sarımsak", "6–8 cloves, crushed", "6–8 Zehen", "6–8 فصوص مهروسة", "6–8 diş"),
    b2g1Ing("tomato", "Tomato", "Tomate", "بندورة", "Domates", "2 grated + 1 tbsp paste optional", "2 gerieben + optional Mark", "حبتان مبشورتان + معجون اختياري", "2 rendelenmiş + isteğe bağlı salça"),
    b2g1Ing("coriander", "Ground coriander", "Koriander", "كزبرة", "Kişniş", "1 tsp", "1 TL", "ملعقة صغيرة", "1 tk"),
    b2g1Ing("rice", "Rice, to serve", "Reis zum Servieren", "أرز للتقديم", "Pilav", "1.5 cups", "1,5 Tassen", "كوب ونصف", "1,5 su bardağı"),
    b2g1Ing("oil", "Oil", "Öl", "زيت", "Yağ", "for frying cauliflower", "zum Braten", "لقلي الزهرة", "kızartmak için"),
    b2g1Ing("salt", "Salt & pepper", "Salz & Pfeffer", "ملح وفلفل", "Tuz ve biber", "to taste", "nach Geschmack", "حسب الذوق", "damak tadına göre"),
  ],
  localeCopy: {
    en: b2g1Loc(
      "Syrian cauliflower with meat and garlic, served with rice — fried florets simmered with tender meat; not a maqluba layer dish.",
      "Syrian",
      ["Fry cauliflower until golden before the stew.", "Plenty of garlic is traditional.", "Serve with plain rice."],
      "Keeps 3 days refrigerated.",
      [
        "Brown meat cubes; add water and simmer until tender; reserve broth.",
        "Fry cauliflower florets until golden; drain.",
        "Return meat with tomato, garlic, coriander, salt and pepper; add florets and enough broth.",
        "Simmer until cauliflower is soft and sauce flavorful.",
        "Serve hot with rice.",
      ],
    ),
    de: b2g1Loc(
      "Syrischer Blumenkohl mit Fleisch und Knoblauch, mit Reis — gebratene Röschen mit zartem Fleisch; kein Maqluba.",
      "Syrisch",
      ["Blumenkohl zuerst goldbraun braten.", "Viel Knoblauch.", "Mit Reis servieren."],
      "3 Tage kühlbar.",
      [
        "Fleisch anbraten und weich köcheln; Brühe zurückhalten.",
        "Röschen goldbraun braten.",
        "Fleisch mit Tomate, Knoblauch und Koriander; Röschen und Brühe zugeben.",
        "Köcheln bis weich und aromatisch.",
        "Heiß mit Reis servieren.",
      ],
    ),
    ar: b2g1Loc(
      "زهرة باللحمة والثوم سورية مع الرز — زهيرات مقلية مع لحم طري؛ ليست طبقة مقلوبة.",
      "سوري",
      ["اقلي الزهرة حتى تذهبّ قبل اليخنة.", "الثوم الوفير تقليدي.", "قدّمي مع أرز أبيض."],
      "3 أيام في الثلاجة.",
      [
        "حمّري اللحم واطبخيه حتى يطرى؛ احتفظي بالمرق.",
        "اقلي زهيرات القرنبيط حتى تذهبّ؛ صفّيها.",
        "أعيدي اللحم مع البندورة والثوم والكزبرة؛ أضيفي الزهرة والمرق.",
        "اتركيه يغلي حتى تطرى الزهرة وتغنى الصلصة.",
        "قدّمي ساخنة مع الرز.",
      ],
    ),
    tr: b2g1Loc(
      "Suriye usulü etli sarımsaklı karnabahar, pilavla — kızarmış çiçekler ve yumuşak et; maklube katmanı değil.",
      "Suriye",
      ["Karnabaharı önce altın rengi kızartın.", "Bol sarımsak gelenekseldir.", "Sade pilavla servis edin."],
      "3 gün saklanır.",
      [
        "Eti kavurup yumuşayana dek pişirin; suyunu ayırın.",
        "Karnabahar çiçeklerini kızartıp süzün.",
        "Eti domates, sarımsak ve kişnişle birleştirip karnabahar ve su ekleyin.",
        "Karnabahar yumuşayıp sos lezzetlenene dek pişirin.",
        "Sıcak pilavla servis edin.",
      ],
    ),
  },
  naturalYield: {
    baseServingsMin: 3,
    baseServingsMax: 4,
    servingLabel: "Serves ~3 with rice",
    scalingNote: "Scale cauliflower and meat together. Distinct from maqluba’s cauliflower layer.",
  },
  defaultRole: "main",
  canServeAsMain: false,
  photo: b2g1Photo(
    "Syrian cauliflower and meat stew with garlic, rice beside.",
    "Stew as hero; rice secondary.",
    "Zahra bil lahmeh stew — not maqluba.",
    "/assets/dishes/arab/syrian-cauliflower-with-meat.jpg",
  ),
});

const POTATO_GARLIC_OIL: GeneratedRecipe = b2g1Recipe({
  matchKeys: [
    "syrian potato garlic olive oil stew",
    "batata bil thoum",
    "potato garlic yellow broth",
    "بطاطا بالثوم وزيت الزيتون",
    "بطاطا بالثوم والمرق الأصفر",
    "يخنة بطاطا بالثوم",
  ],
  canonicalTitle: "Syrian Potato Garlic Olive Oil Stew",
  prepMinutes: 50,
  difficulty: "easy",
  servings: 3,
  mealTypes: ["main", "stew"],
  mealSlotRole: "dinner_complete",
  mealIntents: ["family_friendly", "budget", "healthy"],
  proteinCategory: "vegetable",
  budgetTier: "low",
  suitability: ["everyday_host", "shareable"],
  moods: ["everyday"],
  dietaryTags: ["vegetarian_ok", "vegan_ok"],
  allergens: [],
  ingredientTokens: ["potato", "garlic", "olive oil", "turmeric", "coriander"],
  pantryIngredients: [
    { canonicalId: "potato", role: "critical", tokens: ["potato"] },
    { canonicalId: "garlic", role: "critical", tokens: ["garlic"] },
    { canonicalId: "olive-oil", role: "critical", tokens: ["olive oil"] },
  ],
  ingredients: [
    b2g1Ing("potato", "Potatoes", "Kartoffeln", "بطاطا", "Patates", "800 g, chunks", "800 g, Stücke", "800 غ قطع", "800 g parçalar"),
    b2g1Ing("garlic", "Garlic", "Knoblauch", "ثوم", "Sarımsak", "8–10 cloves, crushed", "8–10 Zehen", "8–10 فصوص مهروسة", "8–10 diş"),
    b2g1Ing("olive-oil", "Olive oil", "Olivenöl", "زيت زيتون", "Zeytinyağı", "1/3 cup", "1/3 Tasse", "ثلث كوب", "1/3 su bardağı"),
    b2g1Ing("turmeric", "Turmeric", "Kurkuma", "كركم", "Zerdeçal", "1/2 tsp, for yellow broth", "1/2 TL", "نصف ملعقة للمرق الأصفر", "1/2 tk sarı su için"),
    b2g1Ing("coriander", "Ground coriander", "Koriander", "كزبرة", "Kişniş", "1 tsp", "1 TL", "ملعقة صغيرة", "1 tk"),
    b2g1Ing("lemon", "Lemon juice", "Zitronensaft", "عصير ليمون", "Limon suyu", "1–2 tbsp optional", "1–2 EL optional", "1–2 ملاعق اختيارية", "1–2 yk isteğe bağlı"),
    b2g1Ing("salt", "Salt & pepper", "Salz & Pfeffer", "ملح وفلفل", "Tuz ve biber", "to taste", "nach Geschmack", "حسب الذوق", "damak tadına göre"),
  ],
  localeCopy: {
    en: b2g1Loc(
      "Syrian potato stew with garlic, olive oil and a light yellow turmeric broth — simple home cooking with bread or rice.",
      "Syrian",
      ["Fry garlic gently in olive oil without burning.", "Turmeric tints the broth yellow.", "Potatoes should be soft and broth light."],
      "Keeps 3 days refrigerated.",
      [
        "Warm olive oil; soften crushed garlic with coriander (do not burn).",
        "Add potato chunks, turmeric, salt and pepper; toss to coat.",
        "Add water to almost cover; simmer until potatoes are tender.",
        "Finish with lemon if desired.",
        "Serve with bread or rice.",
      ],
    ),
    de: b2g1Loc(
      "Syrischer Kartoffel-Eintopf mit Knoblauch, Olivenöl und leicht gelber Kurkuma-Brühe.",
      "Syrisch",
      ["Knoblauch sanft im Öl anschwitzen.", "Kurkuma färbt die Brühe gelb.", "Kartoffeln weich, Brühe leicht."],
      "3 Tage kühlbar.",
      [
        "Olivenöl erwärmen; Knoblauch mit Koriander anschwitzen (nicht verbrennen).",
        "Kartoffeln, Kurkuma, Salz und Pfeffer zugeben.",
        "Mit Wasser fast bedecken; weich köcheln.",
        "Optional mit Zitrone abschließen.",
        "Mit Brot oder Reis servieren.",
      ],
    ),
    ar: b2g1Loc(
      "يخنة بطاطا سورية بالثوم وزيت الزيتون ومرق أصفر خفيف بالكركم — طبخ بيتي بسيط مع الخبز أو الرز.",
      "سوري",
      ["قلّبي الثوم بلطف في الزيت دون حرق.", "الكركم يلوّن المرق أصفر.", "البطاطا طرية والمرق خفيف."],
      "3 أيام في الثلاجة.",
      [
        "سخّني زيت الزيتون؛ ليّني الثوم المهروس مع الكزبرة دون حرق.",
        "أضيفي قطع البطاطا والكركم والملح والفلفل.",
        "أضيفي ماءً يكاد يغطّي؛ اتركيه يغلي حتى تطرى البطاطا.",
        "أنهي بالليمون إن رغبت.",
        "قدّمي مع خبز أو رز.",
      ],
    ),
    tr: b2g1Loc(
      "Suriye usulü sarımsaklı zeytinyağlı patates yahnisi; zerdeçallı açık sarı suyla — ekmek veya pilavla sade ev yemeği.",
      "Suriye",
      ["Sarımsağı yağda yakmadan yumuşatın.", "Zerdeçal suyu sarıya boyar.", "Patates yumuşak, su hafif olsun."],
      "3 gün saklanır.",
      [
        "Zeytinyağını ısıtıp ezilmiş sarımsağı kişnişle yakmadan soteleyin.",
        "Patates, zerdeçal, tuz ve biberi ekleyin.",
        "Neredeyse örtecek su ekleyip yumuşayana dek pişirin.",
        "İsterseniz limon ekleyin.",
        "Ekmek veya pilavla servis edin.",
      ],
    ),
  },
  naturalYield: {
    baseServingsMin: 3,
    baseServingsMax: 4,
    servingLabel: "Serves ~3 as a home stew",
    scalingNote: "Scale potatoes and garlic-oil base together.",
  },
  defaultRole: "main",
  canServeAsMain: false,
  photo: b2g1Photo(
    "Bowl of Syrian potato garlic olive oil stew with yellow broth.",
    "Stew bowl as hero.",
    "Batata bil thoum yellow-broth stew — not batata harra.",
    "/assets/dishes/arab/syrian-potato-garlic-olive-oil-stew.jpg",
  ),
});

const TUNISIAN_COUSCOUS: GeneratedRecipe = b2Recipe(
  {
    matchKeys: [
      "tunisian couscous with meat",
      "tunisian couscous vegetables",
      "couscous tunisien",
      "كسكسي تونسي",
      "كسكسي تونسي بالخضار واللحم",
      "كسكس تونسي",
    ],
    canonicalTitle: "Tunisian Couscous with Meat and Vegetables",
    prepMinutes: 100,
    difficulty: "medium",
    servings: 3,
    mealTypes: ["main"],
    mealSlotRole: "dinner_complete",
    mealIntents: ["family_friendly", "special", "high_calorie"],
    proteinCategory: "lamb",
    budgetTier: "medium",
    suitability: ["guest_friendly", "everyday_host", "shareable"],
    moods: ["special"],
    dietaryTags: ["contains_meat"],
    allergens: ["Gluten"],
    ingredientTokens: ["couscous", "lamb", "chickpeas", "carrot", "zucchini", "harissa"],
    pantryIngredients: [
      { canonicalId: "couscous", role: "critical", tokens: ["couscous"] },
      { canonicalId: "meat", role: "critical", tokens: ["lamb", "beef"] },
      { canonicalId: "chickpeas", role: "supporting", tokens: ["chickpeas"] },
      { canonicalId: "harissa", role: "supporting", tokens: ["harissa"] },
    ],
    ingredients: [
      b2g1Ing("couscous", "Medium couscous", "Couscous mittel", "كسكسي متوسط", "Kuskus", "300 g", "300 g", "300 غرام", "300 g"),
      b2g1Ing("meat", "Lamb or beef pieces", "Lamm-/Rindfleisch", "لحم غنم أو بقر", "Kuzu veya dana", "500 g", "500 g", "500 غرام", "500 g"),
      b2g1Ing("chickpeas", "Chickpeas", "Kichererbsen", "حمّص", "Nohut", "1 cup cooked", "1 Tasse", "كوب مطبوخ", "1 su bardağı"),
      b2g1Ing("carrot", "Carrots", "Karotten", "جزر", "Havuç", "2, chunks", "2, Stücke", "حبتان قطع", "2, parça"),
      b2g1Ing("zucchini", "Zucchini / squash", "Zucchini", "كوسا", "Kabak", "2, chunks", "2, Stücke", "حبتان قطع", "2, parça"),
      b2g1Ing("potato", "Potato", "Kartoffel", "بطاطا", "Patates", "2, chunks", "2, Stücke", "حبتان قطع", "2, parça"),
      b2g1Ing("tomato", "Tomato paste + tomato", "Tomatenmark + Tomate", "معجون طماطم + طماطم", "Salça + domates", "2 tbsp paste + 1 tomato", "2 EL Mark + 1 Tomate", "ملعقتان معجون + حبة", "2 yk salça + 1 domates"),
      b2g1Ing("harissa", "Harissa", "Harissa", "هريسة", "Harissa", "1–2 tsp to taste", "1–2 TL", "1–2 ملاعق صغيرة", "1–2 tk"),
      b2g1Ing("spice", "Ras el hanout or cumin + coriander", "Ras el hanout / Kreuzkümmel", "رأس الحانوت أو كمون وكزبرة", "Ras el hanout / kimyon", "1.5 tsp", "1,5 TL", "ملعقة ونصف", "1,5 tk"),
      b2g1Ing("oil", "Olive oil", "Olivenöl", "زيت زيتون", "Zeytinyağı", "3 tbsp", "3 EL", "3 ملاعق", "3 yk"),
      b2g1Ing("salt", "Salt", "Salz", "ملح", "Tuz", "to taste", "nach Geschmack", "حسب الذوق", "damak tadına göre"),
    ],
    localeCopy: {
      en: b2g1Loc(
        "Tunisian couscous with meat and vegetables: steamed couscous under a spicy meat-and-vegetable stew with harissa — Maghreb identity, not Levantine rice.",
        "Tunisian",
        ["Steam couscous in stages, fluffing between.", "Harissa heat is part of the Tunisian profile.", "Serve broth generous over the grains."],
        "Keeps 3 days; steam couscous fresh when reheating if possible.",
        [
          "Brown meat in oil with tomato paste, spices and harissa; add water and simmer.",
          "Add chickpeas, carrot, potato and zucchini in stages until tender.",
          "Steam couscous with olive oil and salt, fluffing between steamings until light.",
          "Mound couscous on a platter; ladle meat, vegetables and broth over.",
          "Serve hot with extra harissa on the side.",
        ],
      ),
      de: b2g1Loc(
        "Tunesischer Couscous mit Fleisch und Gemüse: gedämpfter Couscous unter würzigem Eintopf mit Harissa — maghrebinisch.",
        "Tunesisch",
        ["Couscous in Etappen dämpfen.", "Harissa gehört dazu.", "Brühe großzügig über die Körner."],
        "3 Tage haltbar; Couscous möglichst frisch dämpfen.",
        [
          "Fleisch mit Mark, Gewürzen und Harissa anbraten; mit Wasser köcheln.",
          "Kichererbsen und Gemüse etappenweise garen.",
          "Couscous mit Öl und Salz dämpfen und auflockern.",
          "Couscous anrichten; Fleisch, Gemüse und Brühe darüber.",
          "Heiß mit extra Harissa servieren.",
        ],
      ),
      ar: b2g1Loc(
        "كسكسي تونسي باللحم والخضار: كسكسي مبخّر تحت يخنة حارة بالهريسة — هوية مغاربية لا أرز شامي.",
        "تونسي",
        ["بخّري الكسكسي على دفعات مع تفكيكه.", "حرارة الهريسة جزء من الطابع التونسي.", "اسكبي المرق بسخاء فوق الحبّ."],
        "3 أيام؛ بخّري الكسكسي طازجاً عند التسخين إن أمكن.",
        [
          "حمّري اللحم مع المعجون والبهار والهريسة؛ أضيفي ماء واتركيه يغلي.",
          "أضيفي الحمّص والجزر والبطاطا والكوسة على مراحل حتى تنضج.",
          "بخّري الكسكسي بزيت وملح مع تفكيكه بين البخارات.",
          "كوّمي الكسكسي واسكبي فوقه اللحم والخضار والمرق.",
          "قدّمي ساخناً مع هريسة إضافية.",
        ],
      ),
      tr: b2g1Loc(
        "Tunus kuskusu: et ve sebzeli baharatlı yahni, harissa ile — Mağrip kimliği, Levanten pilav değil.",
        "Tunus",
        ["Kuskusu aşamalı buharlayın.", "Harissa Tunus profilinin parçasıdır.", "Suyu bol gezdirin."],
        "3 gün saklanır; mümkünse kuskusu taze buharlayın.",
        [
          "Eti salça, baharat ve harissa ile kavurup su ekleyerek pişirin.",
          "Nohut ve sebzeleri aşamalı ekleyin.",
          "Kuskusu yağ ve tuzla buharlayıp kabartın.",
          "Kuskusu tabağa yığıp et, sebze ve suyu üzerine koyun.",
          "Sıcak, yanında ekstra harissa ile servis edin.",
        ],
      ),
    },
    naturalYield: {
      baseServingsMin: 3,
      baseServingsMax: 4,
      servingLabel: "Serves ~3 as a couscous main",
      scalingNote: "Scale couscous, meat and vegetables together; keep harissa to taste.",
    },
    defaultRole: "main",
    canServeAsMain: false,
    photo: b2g1Photo(
      "Tunisian couscous mound with meat, vegetables and broth, harissa aside.",
      "Couscous platter as hero.",
      "Tunisian couscous with harissa — Maghreb, not Levantine rice.",
      "/assets/dishes/arab/tunisian-couscous-with-meat-and-vegetables.jpg",
    ),
  },
  B2_REGION_TUNISIAN,
);

const MOROCCAN_TAGINE: GeneratedRecipe = b2Recipe(
  {
    matchKeys: [
      "moroccan meat tagine with prunes",
      "moroccan lamb tagine with prunes",
      "moroccan beef tagine prunes",
      "tagine prunes",
      "طاجين اللحم المغربي بالبرقوق",
      "طاجين برقوق",
      "طاجين لحم بالبرقوق",
    ],
    canonicalTitle: "Moroccan Meat Tagine with Prunes",
    prepMinutes: 120,
    difficulty: "medium",
    servings: 3,
    mealTypes: ["main", "stew"],
    mealSlotRole: "dinner_complete",
    mealIntents: ["family_friendly", "special", "high_calorie"],
    proteinCategory: "lamb",
    budgetTier: "medium",
    suitability: ["guest_friendly", "everyday_host", "shareable"],
    moods: ["special"],
    dietaryTags: ["contains_meat"],
    allergens: ["Nuts"],
    ingredientTokens: ["lamb", "prunes", "onion", "cinnamon", "ginger", "almonds"],
    pantryIngredients: [
      { canonicalId: "meat", role: "critical", tokens: ["lamb", "beef"] },
      { canonicalId: "prunes", role: "critical", tokens: ["prunes", "dried plums"] },
      { canonicalId: "onion", role: "supporting", tokens: ["onion"] },
    ],
    ingredients: [
      b2g1Ing("meat", "Lamb or beef pieces", "Lamm-/Rindfleisch", "لحم غنم أو بقر", "Kuzu veya dana", "700 g", "700 g", "700 غرام", "700 g"),
      b2g1Ing("prunes", "Pitted prunes", "Entsteinte Pflaumen", "برقوق مجفّف منزوع النوى", "Çekirdeksiz erik kurusu", "200 g", "200 g", "200 غرام", "200 g"),
      b2g1Ing("onion", "Onion", "Zwiebel", "بصل", "Soğan", "2, sliced", "2, in Scheiben", "حبتان شرائح", "2, dilim"),
      b2g1Ing("spice", "Cinnamon, ginger, turmeric, pepper", "Zimt, Ingwer, Kurkuma, Pfeffer", "قرفة زنجبيل كركم فلفل", "Tarçın, zencefil, zerdeçal, biber", "1 tsp each cinnamon & ginger + 1/2 tsp turmeric", "je 1 TL Zimt/Ingwer + 1/2 TL Kurkuma", "ملعقة قرفة وزنجبيل + نصف كركم", "1 tk tarçın/zencefil + 1/2 zerdeçal"),
      b2g1Ing("honey", "Honey", "Honig", "عسل", "Bal", "1–2 tbsp", "1–2 EL", "1–2 ملاعق", "1–2 yk"),
      b2g1Ing("almonds", "Blanched almonds", "Mandeln", "لوز", "Badem", "1/3 cup, toasted, garnish", "1/3 Tasse geröstet", "ثلث كوب محمّص", "1/3 su bardağı kavrulmuş"),
      b2g1Ing("oil", "Oil or smen", "Öl oder Smen", "زيت أو سمن", "Yağ veya smen", "3 tbsp", "3 EL", "3 ملاعق", "3 yk"),
      b2g1Ing("salt", "Salt", "Salz", "ملح", "Tuz", "to taste", "nach Geschmack", "حسب الذوق", "damak tadına göre"),
    ],
    localeCopy: {
      en: b2g1Loc(
        "Moroccan meat tagine with prunes: slow-cooked lamb or beef with warm spices, honeyed prunes and toasted almonds — sweet-savory Maghreb main.",
        "Moroccan",
        ["Cook meat until very tender before adding prunes.", "Balance honey so it is fragrant, not cloying.", "Serve with bread or couscous."],
        "Keeps 3 days; reheat gently.",
        [
          "Brown meat with onion, oil and spices; add water and simmer covered until tender.",
          "Add prunes and honey; simmer until sauce is glossy and fruit plump.",
          "Taste for salt and sweetness.",
          "Garnish with toasted almonds.",
          "Serve hot with bread or couscous.",
        ],
      ),
      de: b2g1Loc(
        "Marokkanisches Fleisch-Tagine mit Pflaumen: langsam gegartes Fleisch mit warmen Gewürzen, honigsüßen Pflaumen und Mandeln.",
        "Marokkanisch",
        ["Fleisch zuerst sehr zart garen.", "Honig ausgewogen halten.", "Mit Brot oder Couscous."],
        "3 Tage haltbar; sanft erwärmen.",
        [
          "Fleisch mit Zwiebel, Öl und Gewürzen anbraten; mit Wasser zugedeckt garen.",
          "Pflaumen und Honig zugeben; glänzend einkochen.",
          "Mit Salz und Süße abschmecken.",
          "Mit Mandeln garnieren.",
          "Heiß mit Brot oder Couscous servieren.",
        ],
      ),
      ar: b2g1Loc(
        "طاجين لحم مغربي بالبرقوق: لحم مطهو ببطء مع بهارات دافئة وبرقوق بالعسل ولوز محمّص — طبق مغاربي حلو-مالح.",
        "مغربي",
        ["اطبخي اللحم حتى يطرى جداً قبل البرقوق.", "وازني العسل دون إفراط.", "مع خبز أو كسكسي."],
        "3 أيام؛ أعيدي التسخين بهدوء.",
        [
          "حمّري اللحم مع البصل والزيت والبهار؛ أضيفي ماء وغطّي حتى يطرى.",
          "أضيفي البرقوق والعسل؛ اتركيه يغلي حتى تلمع الصلصة وينتفخ الفاكهة.",
          "ذوقّي الملح والحلاوة.",
          "زيّني باللوز المحمّص.",
          "قدّمي ساخناً مع خبز أو كسكسي.",
        ],
      ),
      tr: b2g1Loc(
        "Fas usulü erikli et tajini: baharatlı yumuşak et, ballı erik ve kavrulmuş badem — tatlı-tuzlu Mağrip ana yemeği.",
        "Fas",
        ["Eriği eklemeden önce eti çok yumuşatın.", "Balı dengeli tutun.", "Ekmek veya kuskusla servis edin."],
        "3 gün saklanır; hafif ısıtın.",
        [
          "Eti soğan, yağ ve baharatla kavurup su ekleyerek kapalı pişirin.",
          "Erik ve balı ekleyip sos parlak, meyve şişene dek pişirin.",
          "Tuz ve tatlılığı ayarlayın.",
          "Kavrulmuş bademle süsleyin.",
          "Sıcak ekmek veya kuskusla servis edin.",
        ],
      ),
    },
    naturalYield: {
      baseServingsMin: 3,
      baseServingsMax: 4,
      servingLabel: "Serves ~3 as a tagine main",
      scalingNote: "Scale meat and prunes together; keep honey balanced.",
    },
    defaultRole: "main",
    canServeAsMain: false,
    photo: b2g1Photo(
      "Moroccan meat tagine with prunes and almonds in a shallow dish.",
      "Tagine stew as hero.",
      "Moroccan prune tagine — Maghreb sweet-savory identity.",
      "/assets/dishes/arab/moroccan-meat-tagine-with-prunes.jpg",
    ),
  },
  B2_REGION_MOROCCAN,
);

const MOROCCAN_CHICKEN: GeneratedRecipe = b2Recipe(
  {
    matchKeys: [
      "moroccan chicken with preserved lemon and olives",
      "moroccan chicken preserved lemon olives",
      "chicken tagine lemon olives",
      "دجاج مغربي بالليمون المصير والزيتون",
      "دجاج بالليمون المصير",
      "طاجين دجاج بالزيتون والليمون",
    ],
    canonicalTitle: "Moroccan Chicken with Preserved Lemon and Olives",
    prepMinutes: 90,
    difficulty: "medium",
    servings: 3,
    mealTypes: ["main", "stew"],
    mealSlotRole: "dinner_complete",
    mealIntents: ["family_friendly", "special", "healthy"],
    proteinCategory: "chicken",
    budgetTier: "medium",
    suitability: ["guest_friendly", "everyday_host", "shareable"],
    moods: ["special", "everyday"],
    dietaryTags: ["contains_meat"],
    allergens: [],
    ingredientTokens: ["chicken", "preserved lemon", "olives", "onion", "saffron", "ginger"],
    pantryIngredients: [
      { canonicalId: "chicken", role: "critical", tokens: ["chicken"] },
      { canonicalId: "preserved-lemon", role: "critical", tokens: ["preserved lemon", "lemon confit"] },
      { canonicalId: "olives", role: "critical", tokens: ["olives"] },
    ],
    ingredients: [
      b2g1Ing("chicken", "Chicken pieces", "Hähnchenteile", "قطع دجاج", "Tavuk parçaları", "1 kg", "1 kg", "1 كغ", "1 kg"),
      b2g1Ing("preserved-lemon", "Preserved lemon", "Eingelegte Zitrone", "ليمون مصير / مخلل", "Turşu limon", "1–2, pulp rinsed, peel sliced", "1–2, Schale in Streifen", "1–2 شرائح قشر بعد الشطف", "1–2, kabuk dilimleri"),
      b2g1Ing("olives", "Green or purple olives", "Oliven", "زيتون أخضر أو بنفسجي", "Zeytin", "1 cup, rinsed", "1 Tasse", "كوب مغسول", "1 su bardağı"),
      b2g1Ing("onion", "Onion", "Zwiebel", "بصل", "Soğan", "2, sliced", "2, in Scheiben", "حبتان شرائح", "2, dilim"),
      b2g1Ing("garlic", "Garlic", "Knoblauch", "ثوم", "Sarımsak", "4 cloves", "4 Zehen", "4 فصوص", "4 diş"),
      b2g1Ing("spice", "Ginger, turmeric, pepper, saffron", "Ingwer, Kurkuma, Pfeffer, Safran", "زنجبيل كركم فلفل زعفران", "Zencefil, zerdeçal, biber, safran", "1 tsp ginger + 1/2 tsp turmeric + pinch saffron", "1 TL Ingwer + 1/2 TL Kurkuma + Prise Safran", "ملعقة زنجبيل + نصف كركم + رشة زعفران", "1 tk zencefil + 1/2 zerdeçal + safran"),
      b2g1Ing("cilantro", "Cilantro / coriander leaves", "Koriandergrün", "كزبرة خضراء", "Taze kişniş", "1/2 cup chopped", "1/2 Tasse", "نصف كوب", "1/2 su bardağı"),
      b2g1Ing("oil", "Olive oil", "Olivenöl", "زيت زيتون", "Zeytinyağı", "3 tbsp", "3 EL", "3 ملاعق", "3 yk"),
      b2g1Ing("salt", "Salt", "Salz", "ملح", "Tuz", "to taste (olives & lemon are salty)", "nach Geschmack", "حسب الذوق (الزيتون والليمون مالحان)", "damak tadına göre"),
    ],
    localeCopy: {
      en: b2g1Loc(
        "Moroccan chicken with preserved lemon and olives: braised chicken in onion-spice sauce finished with salty lemon peel and olives.",
        "Moroccan",
        ["Rinse preserved lemon pulp; use peel for aroma.", "Do not oversalt — olives and lemon are salty.", "Serve with bread or couscous."],
        "Keeps 3 days refrigerated.",
        [
          "Brown chicken lightly; soften onion and garlic in oil with spices.",
          "Return chicken with a little water; simmer covered until almost tender.",
          "Add olives and preserved lemon peel; finish cooking until sauce is reduced.",
          "Stir in chopped cilantro.",
          "Serve hot with bread or couscous.",
        ],
      ),
      de: b2g1Loc(
        "Marokkanisches Hähnchen mit eingelegter Zitrone und Oliven: geschmort in Zwiebel-Gewürz-Sauce.",
        "Marokkanisch",
        ["Zitronenschale verwenden.", "Nicht zu stark salzen.", "Mit Brot oder Couscous."],
        "3 Tage kühlbar.",
      [
          "Hähnchen leicht anbräunen; Zwiebel und Knoblauch mit Gewürzen anschwitzen.",
          "Hähnchen mit etwas Wasser zugedeckt garen.",
          "Oliven und Zitronenschale zugeben; einkochen.",
          "Koriandergrün unterheben.",
          "Heiß mit Brot oder Couscous servieren.",
        ],
      ),
      ar: b2g1Loc(
        "دجاج مغربي بالليمون المصير والزيتون: دجاج مطهو في صلصة بصل وبهارات يُختَم بقشر الليمون المملّح والزيتون.",
        "مغربي",
        ["اشطفي لب الليمون المصير واستخدمي القشر.", "لا تفرطي بالملح.", "مع خبز أو كسكسي."],
        "3 أيام في الثلاجة.",
        [
          "حمّري الدجاج قليلاً؛ ليّني البصل والثوم بالزيت والبهار.",
          "أعيدي الدجاج مع قليل من الماء وغطّي حتى يكاد ينضج.",
          "أضيفي الزيتون وقشر الليمون المصير؛ اتركيه حتى تتكثّف الصلصة.",
          "قلّبي الكزبرة الخضراء.",
          "قدّمي ساخناً مع خبز أو كسكسي.",
        ],
      ),
      tr: b2g1Loc(
        "Fas usulü turşu limonlu zeytinli tavuk: soğanlı baharat sosunda haşlanmış tavuk.",
        "Fas",
        ["Turşu limonun kabuğunu kullanın.", "Tuzu abartmayın.", "Ekmek veya kuskusla servis edin."],
        "3 gün saklanır.",
        [
          "Tavuğu hafifçe kızartın; soğan ve sarımsağı baharatla yumuşatın.",
          "Tavuğu biraz suyla kapağı kapalı pişirin.",
          "Zeytin ve turşu limon kabuğunu ekleyip sos koyulaşana dek pişirin.",
          "Taze kişnişi karıştırın.",
          "Sıcak ekmek veya kuskusla servis edin.",
        ],
      ),
    },
    naturalYield: {
      baseServingsMin: 3,
      baseServingsMax: 4,
      servingLabel: "Serves ~3 as a braise main",
      scalingNote: "Scale chicken, olives and preserved lemon carefully for salt balance.",
    },
    defaultRole: "main",
    canServeAsMain: false,
    photo: b2g1Photo(
      "Moroccan chicken braise with olives and preserved lemon slices.",
      "Chicken and sauce as hero.",
      "Preserved lemon and olive chicken — Moroccan identity.",
      "/assets/dishes/arab/moroccan-chicken-with-preserved-lemon-and-olives.jpg",
    ),
  },
  B2_REGION_MOROCCAN,
);

const BATATA_HARRA: GeneratedRecipe = b2Recipe(
  {
    matchKeys: [
      "lebanese batata harra",
      "batata harra",
      "spicy potatoes lebanese",
      "بطاطا حرة لبنانية",
      "بطاطا حرّة",
      "بطاطا حارة",
    ],
    canonicalTitle: "Lebanese Batata Harra",
    prepMinutes: 45,
    difficulty: "easy",
    servings: 3,
    mealTypes: ["side"],
    mealSlotRole: "side_component",
    mealIntents: ["family_friendly", "budget", "quick"],
    proteinCategory: "vegetable",
    budgetTier: "low",
    suitability: ["everyday_host", "guest_friendly", "shareable"],
    moods: ["everyday", "quick"],
    dietaryTags: ["vegetarian_ok", "vegan_ok"],
    allergens: [],
    ingredientTokens: ["potato", "garlic", "cilantro", "chili", "lemon", "olive oil"],
    pantryIngredients: [
      { canonicalId: "potato", role: "critical", tokens: ["potato"] },
      { canonicalId: "garlic", role: "supporting", tokens: ["garlic"] },
      { canonicalId: "cilantro", role: "supporting", tokens: ["cilantro", "coriander"] },
      { canonicalId: "chili", role: "supporting", tokens: ["chili", "pepper"] },
    ],
    ingredients: [
      b2g1Ing("potato", "Potatoes", "Kartoffeln", "بطاطا", "Patates", "700 g, cubed and fried or roasted", "700 g, gewürfelt gebraten/geröstet", "700 غ مكعّبات مقلية أو محمّصة", "700 g küp kızartılmış/fırın"),
      b2g1Ing("garlic", "Garlic", "Knoblauch", "ثوم", "Sarımsak", "4–5 cloves, crushed", "4–5 Zehen", "4–5 فصوص مهروسة", "4–5 diş"),
      b2g1Ing("cilantro", "Fresh cilantro", "Frischer Koriander", "كزبرة خضراء", "Taze kişniş", "1 cup chopped", "1 Tasse", "كوب مفروم", "1 su bardağı"),
      b2g1Ing("chili", "Fresh chili or chili flakes", "Chili", "فلفل حار", "Acı biber", "to taste", "nach Geschmack", "حسب الذوق", "damak tadına göre"),
      b2g1Ing("lemon", "Lemon juice", "Zitronensaft", "عصير ليمون", "Limon suyu", "2–3 tbsp", "2–3 EL", "2–3 ملاعق", "2–3 yk"),
      b2g1Ing("olive-oil", "Olive oil", "Olivenöl", "زيت زيتون", "Zeytinyağı", "4 tbsp", "4 EL", "4 ملاعق", "4 yk"),
      b2g1Ing("salt", "Salt", "Salz", "ملح", "Tuz", "to taste", "nach Geschmack", "حسب الذوق", "damak tadına göre"),
    ],
    localeCopy: {
      en: b2g1Loc(
        "Lebanese batata harra: crispy fried potatoes tossed with garlic, cilantro, chili and lemon — a spicy mezze/side, distinct from soft Syrian potato stews.",
        "Lebanese",
        ["Potatoes must be crisp outside.", "Add garlic-cilantro off the heat so it stays bright.", "Lemon finishes the heat."],
        "Best fresh; re-crisp in a hot pan if needed.",
        [
          "Fry or roast potato cubes until golden and crisp; salt lightly.",
          "Warm olive oil; briefly cook garlic and chili (do not burn).",
          "Toss potatoes with garlic oil, chopped cilantro and lemon juice.",
          "Taste for salt and heat.",
          "Serve immediately as mezze or side.",
        ],
      ),
      de: b2g1Loc(
        "Libanesische Batata Harra: knusprige Kartoffeln mit Knoblauch, Koriander, Chili und Zitrone — anders als weiche syrische Kartoffeleintöpfe.",
        "Libanesisch",
        ["Kartoffeln außen knusprig.", "Knoblauch-Koriander nicht verbrennen.", "Mit Zitrone abschließen."],
        "Am besten frisch; bei Bedarf nachrösten.",
        [
          "Kartoffeln goldbraun knusprig braten/rösten; leicht salzen.",
          "Olivenöl erwärmen; Knoblauch und Chili kurz anschwitzen.",
          "Kartoffeln mit Öl, Koriander und Zitrone vermengen.",
          "Abschmecken.",
          "Sofort als Mezze/Beilage servieren.",
        ],
      ),
      ar: b2g1Loc(
        "بطاطا حرّة لبنانية: بطاطا مقرمشة مع ثوم وكزبرة وفلفل حار وليمون — مقبلات/جانب حار، متميزة عن يخنة البطاطا السورية الطرية.",
        "لبناني",
        ["البطاطا مقرمشة من الخارج.", "أضيفي الثوم والكزبرة بعيداً عن الحرارة الشديدة.", "الليمون يختتم الحدّة."],
        "الأفضل طازجة؛ أعيدي تحميرها إن لزم.",
        [
          "اقلي أو اشوي مكعّبات البطاطا حتى تذهبّ وتقرمش؛ رشّي ملحاً خفيفاً.",
          "سخّني زيت الزيتون؛ قلّبي الثوم والفلفل قليلاً دون حرق.",
          "قلّبي البطاطا مع زيت الثوم والكزبرة وعصير الليمون.",
          "ذوقّي الملح والحرارة.",
          "قدّمي فوراً كمقبّلات أو جانب.",
        ],
      ),
      tr: b2g1Loc(
        "Lübnan batata harrası: sarımsak, kişniş, acı ve limonlu çıtır patates — yumuşak Suriye patates yahnilerinden ayrı.",
        "Lübnan",
        ["Patates dışı çıtır olmalı.", "Sarımsak-kişnişi yakmayın.", "Limonla bitirin."],
        "En iyisi taze; gerekirse tavada yeniden kızartın.",
        [
          "Patates küplerini altın ve çıtır olana dek kızartın/fırınlayın; hafif tuzlayın.",
          "Zeytinyağında sarımsak ve acıyı kısa soteleyin.",
          "Patatesi sarımsaklı yağ, kişniş ve limonla karıştırın.",
          "Tuz ve acıyı ayarlayın.",
          "Hemen meze veya yan olarak servis edin.",
        ],
      ),
    },
    naturalYield: {
      baseServingsMin: 3,
      baseServingsMax: 4,
      servingLabel: "Serves 3–4 as mezze/side",
      scalingNote: "Scale potatoes and garlic-cilantro dressing together. Distinct from soft potato stews.",
    },
    defaultRole: "side",
    canServeAsMain: true,
    photo: b2g1Photo(
      "Lebanese batata harra crispy potatoes with cilantro garlic chili lemon.",
      "Potato plate as hero.",
      "Batata harra — crispy spicy Lebanese potatoes, not soft stew.",
      "/assets/dishes/arab/lebanese-batata-harra.jpg",
    ),
  },
  B2_REGION_LEBANESE,
);

export const ARAB_BATCH_2_GROUP_2_B: GeneratedRecipe[] = [
  DAWOOD_BASHA,
  STUFFED_CABBAGE,
  CAULIFLOWER_MEAT,
  POTATO_GARLIC_OIL,
  TUNISIAN_COUSCOUS,
  MOROCCAN_TAGINE,
  MOROCCAN_CHICKEN,
  BATATA_HARRA,
];
