/**
 * Arab Batch 2 Group 1B — Syrian / Levantine mains, sides, bakery (part 2).
 * Studio draft sources only. No images in this pass.
 */

import {
  b2g1Ing,
  b2g1Loc,
  b2g1Photo,
  b2g1Recipe,
} from "./arabBatch2Group1Shared";
import type { GeneratedRecipe } from "./generatedRecipeLibrary";

const ARTICHOKE_SALAD: GeneratedRecipe = b2g1Recipe({
  matchKeys: [
    "artichoke salad",
    "syrian artichoke salad",
    "ardi shoki salad",
    "سلطة أرضي شوكي",
    "سلطة ارضي شوكي",
    "سلطة الخرشوف",
  ],
  canonicalTitle: "Artichoke Salad",
  prepMinutes: 35,
  difficulty: "easy",
  servings: 3,
  mealTypes: ["salad", "side"],
  mealSlotRole: "side_component",
  mealIntents: ["family_friendly", "healthy", "quick"],
  proteinCategory: "vegetable",
  budgetTier: "medium",
  suitability: ["everyday_host", "guest_friendly", "shareable"],
  moods: ["everyday", "quick"],
  dietaryTags: ["vegetarian_ok", "vegan_ok"],
  allergens: [],
  ingredientTokens: ["artichoke", "lemon", "garlic", "olive oil", "parsley"],
  pantryIngredients: [
    { canonicalId: "artichoke", role: "critical", tokens: ["artichoke", "ardi shoki"] },
    { canonicalId: "lemon", role: "supporting", tokens: ["lemon"] },
    { canonicalId: "olive-oil", role: "supporting", tokens: ["olive oil"] },
  ],
  ingredients: [
    b2g1Ing("artichoke", "Artichoke hearts", "Artischockenherzen", "قلوب أرضي شوكي", "Enginar kalbi", "400 g cooked (fresh or jarred, drained)", "400 g gegart", "400 غ مطبوخة", "400 g haşlanmış"),
    b2g1Ing("lemon", "Lemon juice", "Zitronensaft", "عصير ليمون", "Limon suyu", "3–4 tbsp", "3–4 EL", "3–4 ملاعق", "3–4 yk"),
    b2g1Ing("garlic", "Garlic", "Knoblauch", "ثوم", "Sarımsak", "1–2 cloves, crushed", "1–2 Zehen", "1–2 فصوص", "1–2 diş"),
    b2g1Ing("olive-oil", "Olive oil", "Olivenöl", "زيت زيتون", "Zeytinyağı", "4 tbsp", "4 EL", "4 ملاعق", "4 yk"),
    b2g1Ing("parsley", "Flat-leaf parsley", "Petersilie", "بقدونس", "Maydanoz", "2 tbsp, chopped", "2 EL gehackt", "ملعقتان مفروم", "2 yk doğranmış"),
    b2g1Ing("salt", "Salt & pepper", "Salz & Pfeffer", "ملح وفلفل", "Tuz ve biber", "to taste", "nach Geschmack", "حسب الذوق", "damak tadına göre"),
  ],
  localeCopy: {
    en: b2g1Loc(
      "Syrian artichoke salad: tender artichoke hearts dressed with lemon, garlic and olive oil — a bright mezze or side.",
      "Syrian",
      ["If using jarred hearts, rinse well.", "Dress while still slightly warm to absorb flavour.", "Keep the dressing sharp with lemon."],
      "Best within 2 days refrigerated.",
      [
        "Drain and, if needed, gently warm or blanch artichoke hearts; cut into bite-size pieces.",
        "Whisk lemon juice, crushed garlic, olive oil, salt and pepper.",
        "Toss artichokes with the dressing and chopped parsley.",
        "Rest 10 minutes and serve cool or at room temperature.",
      ],
    ),
    de: b2g1Loc(
      "Syrischer Artischockensalat: zarte Herzen mit Zitrone, Knoblauch und Olivenöl — helles Mezze oder Beilage.",
      "Syrisch",
      ["Eingelegte Herzen gut abspülen.", "Leicht warm marinieren.", "Dressing zitronig halten."],
      "Innerhalb von 2 Tagen am besten.",
      [
        "Artischockenherzen abtropfen, ggf. kurz erwärmen; mundgerecht schneiden.",
        "Zitronensaft, Knoblauch, Olivenöl, Salz und Pfeffer verrühren.",
        "Mit Petersilie vermengen.",
        "10 Min. ziehen lassen; kühl oder Zimmertemperatur servieren.",
      ],
    ),
    ar: b2g1Loc(
      "سلطة أرضي شوكي سورية: قلوب طرية بتتبيلة ليمون وثوم وزيت زيتون — مقبلات أو طبق جانبي.",
      "سوري",
      ["إن كانت من مرطبان فاغسليها جيداً.", "تبّليها وهي دافئة قليلاً.", "أبقي التتبيلة حامضية."],
      "الأفضل خلال يومين.",
      [
        "صفّي قلوب الأرضي شوكي وقطّعيها قطعاً مناسبة.",
        "اخفقي الليمون والثوم وزيت الزيتون والملح والفلفل.",
        "قلّبي مع البقدونس.",
        "اتركيها 10 دقائق وقدّمي باردة أو بدرجة حرارة الغرفة.",
      ],
    ),
    tr: b2g1Loc(
      "Suriye enginar salatası: limon, sarımsak ve zeytinyağıyla — ferah meze veya yan.",
      "Suriye",
      ["Kavanozdan ise iyice durulayın.", "Hafif ılıyken soslayın.", "Sosu limonlu tutun."],
      "2 gün içinde en iyisi.",
      [
        "Enginar kalplerini süzüp doğrayın.",
        "Limon, sarımsak, zeytinyağı, tuz ve biberi çırpın.",
        "Maydanozla karıştırın.",
        "10 dk dinlendirip soğuk veya oda sıcaklığında servis edin.",
      ],
    ),
  },
  naturalYield: {
    baseServingsMin: 3,
    baseServingsMax: 4,
    servingLabel: "Serves 3–4 as mezze/side",
    scalingNote: "Scale artichokes and dressing together.",
  },
  defaultRole: "side",
  canServeAsMain: false,
  photo: b2g1Photo(
    "Simple Syrian artichoke salad with lemon-olive oil dressing and parsley.",
    "Salad bowl as hero; calm neutrals.",
    "Artichoke hearts with lemon-garlic dressing — Syrian mezze salad.",
    "/assets/dishes/arab/artichoke-salad.jpg",
  ),
});

const OUZI: GeneratedRecipe = b2g1Recipe({
  matchKeys: [
    "syrian ouzi",
    "ouzi",
    "ouzi rice",
    "ozy",
    "أوزى",
    "أوزي",
    "أوزي سوري",
  ],
  canonicalTitle: "Syrian Ouzi",
  prepMinutes: 100,
  difficulty: "medium",
  servings: 3,
  mealTypes: ["main", "rice"],
  mealSlotRole: "dinner_complete",
  mealIntents: ["family_friendly", "special", "high_calorie"],
  proteinCategory: "mixed",
  budgetTier: "medium",
  suitability: ["guest_friendly", "everyday_host", "shareable"],
  moods: ["special"],
  dietaryTags: ["contains_meat"],
  allergens: ["Nuts"],
  ingredientTokens: ["rice", "minced meat", "peas", "chicken", "almonds", "allspice"],
  pantryIngredients: [
    { canonicalId: "rice", role: "critical", tokens: ["rice"] },
    { canonicalId: "minced-meat", role: "critical", tokens: ["minced meat"] },
    { canonicalId: "peas", role: "supporting", tokens: ["peas"] },
    { canonicalId: "chicken", role: "supporting", tokens: ["chicken"] },
  ],
  ingredients: [
    b2g1Ing("rice", "Egyptian / short-grain rice", "Rundkornreis", "أرز مصري", "Kısa taneli pirinç", "2 cups (400 g)", "2 Tassen (400 g)", "كوبان (400 غ)", "2 su bardağı (400 g)"),
    b2g1Ing("minced-meat", "Minced lamb or beef", "Hackfleisch", "لحم مفروم", "Kıyma", "300 g", "300 g", "300 غرام", "300 g"),
    b2g1Ing("chicken", "Chicken pieces (optional top)", "Hähnchenteile (optional)", "قطع دجاج (اختياري فوق)", "Tavuk (isteğe bağlı)", "500 g, roasted or boiled", "500 g", "500 غ", "500 g"),
    b2g1Ing("peas", "Green peas", "Erbsen", "بازيلاء", "Bezelye", "1 cup, cooked", "1 Tasse", "كوب مطبوخ", "1 su bardağı"),
    b2g1Ing("onion", "Onion", "Zwiebel", "بصل", "Soğan", "1, chopped", "1, gehackt", "حبة مفرومة", "1, doğranmış"),
    b2g1Ing("spice", "Allspice & cinnamon", "Piment & Zimt", "بهار وقرفة", "Yenibahar ve tarçın", "1.5 tsp + 1/2 tsp", "1,5 + 1/2 TL", "ملعقة ونصف + نصف", "1,5 + 1/2 tk"),
    b2g1Ing("almonds", "Toasted almonds & pine nuts", "Mandeln & Pinienkerne", "لوز وصنوبر محمّص", "Badem ve çam fıstığı", "1/3 cup", "1/3 Tasse", "ثلث كوب", "1/3 su bardağı"),
    b2g1Ing("ghee", "Ghee or oil", "Butterschmalz oder Öl", "سمن أو زيت", "Sadeyağ veya yağ", "3 tbsp", "3 EL", "3 ملاعق", "3 yk"),
    b2g1Ing("salt", "Salt & pepper", "Salz & Pfeffer", "ملح وفلفل", "Tuz ve biber", "to taste", "nach Geschmack", "حسب الذوق", "damak tadına göre"),
  ],
  localeCopy: {
    en: b2g1Loc(
      "Syrian ouzi: fragrant rice mixed with spiced minced meat, peas and toasted nuts, often topped with chicken — a Syrian celebration rice, not Gulf kabsa or mandi.",
      "Syrian",
      ["Brown minced meat separately then fold into the rice.", "Toast nuts for crunch.", "Chicken on top is traditional for gatherings."],
      "Refrigerate up to 3 days; reheat with a splash of water.",
      [
        "Cook or roast the chicken until done; keep warm.",
        "Brown onion and minced meat with allspice, cinnamon, salt and pepper; stir in peas.",
        "Rinse rice and cook in ghee with enough water/broth until fluffy.",
        "Fold the meat-pea mixture and most of the nuts into the rice.",
        "Mound on a platter, top with chicken pieces and remaining nuts.",
        "Serve hot as a family main.",
      ],
    ),
    de: b2g1Loc(
      "Syrisches Ouzi: duftender Reis mit gewürztem Hack, Erbsen und Nüssen, oft mit Hähnchen — syrischer Festtagsreis, kein Golf-Kabsa/Mandi.",
      "Syrisch",
      ["Hack separat anbraten, dann unter den Reis heben.", "Nüsse rösten.", "Hähnchen obenauf für Gäste."],
      "Bis zu 3 Tage kühlen; mit etwas Wasser erwärmen.",
      [
        "Hähnchen garen oder braten; warm halten.",
        "Zwiebel und Hack mit Gewürzen anbraten; Erbsen unterrühren.",
        "Reis in Butterschmalz mit Wasser/Brühe fluffig garen.",
        "Hack-Erbsen-Mischung und die meisten Nüsse unterheben.",
        "Auf Platte anrichten, Hähnchen und Restnüsse obenauf.",
        "Heiß als Familienessen servieren.",
      ],
    ),
    ar: b2g1Loc(
      "أوزى سوري: أرز معطر بلحم مفروم متبّل وبازيلاء ومكسّرات، وغالباً دجاج فوقه — رز مناسبات سوري، لا كبسة أو مندي خليجي.",
      "سوري",
      ["حمّري اللحم المفروم ثم اخلطيه بالأرز.", "حمّصي المكسّرات.", "الدجاج فوق تقليد للضيوف."],
      "تُحفظ حتى 3 أيام؛ أعيدي التسخين برشة ماء.",
      [
        "اطبخي أو اشوي الدجاج؛ أبقيه دافئاً.",
        "حمّري البصل واللحم المفروم بالبهار والقرفة؛ أضيفي البازيلاء.",
        "اطبخي الأرز بالسمن حتى ينفش.",
        "اخلطي خليط اللحم والبازيلاء ومعظم المكسّرات بالأرز.",
        "كوّمي على صحن كبير مع قطع الدجاج وبقية المكسّرات.",
        "قدّمي ساخناً كطبق عائلي.",
      ],
    ),
    tr: b2g1Loc(
      "Suriye ouzisi: baharatlı kıyma, bezelye ve kuruyemişli pilav, genelde üstünde tavuk — Körfez kabsa/mandi değil.",
      "Suriye",
      ["Kıymayı ayrı kavurup pilava katın.", "Kuruyemişleri kavurun.", "Misafir için üstte tavuk."],
      "3 güne kadar saklayın; biraz suyla ısıtın.",
      [
        "Tavuğu pişirin veya kızartın; sıcak tutun.",
        "Soğan ve kıymayı baharatla kavurup bezelyeyi ekleyin.",
        "Pirinci sadeyağla kabarık pişirin.",
        "Kıyma-bezelye karışımını ve kuruyemişin çoğunu pilava katın.",
        "Tabağa yığıp üstüne tavuk ve kalan kuruyemişi koyun.",
        "Sıcak aile yemeği olarak servis edin.",
      ],
    ),
  },
  naturalYield: {
    baseServingsMin: 3,
    baseServingsMax: 4,
    servingLabel: "Serves ~3–4 as a celebration main",
    scalingNote: "Scale rice, minced meat and peas together. Keep distinct from kabsa/mandi.",
  },
  defaultRole: "main",
  canServeAsMain: false,
  photo: b2g1Photo(
    "Syrian ouzi rice mound with minced meat, peas, nuts and chicken on top.",
    "Rice mound as hero; chicken on top optional but recognizable.",
    "Syrian ouzi — not Gulf kabsa or mandi.",
    "/assets/dishes/arab/syrian-ouzi.jpg",
  ),
});

const PEAS_TOMATO: GeneratedRecipe = b2g1Recipe({
  matchKeys: [
    "peas with tomato",
    "bazella w banadoura",
    "bazella wa banadoura",
    "peas tomato stew",
    "بازلاء وبندورة",
    "بازيلاء وبندورة",
    "بازلاء بالبندورة",
  ],
  canonicalTitle: "Peas with Tomato",
  prepMinutes: 50,
  difficulty: "easy",
  servings: 3,
  mealTypes: ["main", "stew"],
  mealSlotRole: "dinner_complete",
  mealIntents: ["family_friendly", "budget", "healthy"],
  proteinCategory: "vegetable",
  budgetTier: "low",
  suitability: ["everyday_host", "shareable"],
  moods: ["everyday"],
  dietaryTags: ["vegetarian_ok", "vegan_ok"],
  allergens: [],
  ingredientTokens: ["peas", "tomato", "onion", "garlic", "olive oil"],
  pantryIngredients: [
    { canonicalId: "peas", role: "critical", tokens: ["peas", "bazella"] },
    { canonicalId: "tomato", role: "critical", tokens: ["tomato", "banadoura"] },
    { canonicalId: "onion", role: "supporting", tokens: ["onion"] },
  ],
  ingredients: [
    b2g1Ing("peas", "Green peas", "Erbsen", "بازيلاء / بازلاء", "Bezelye", "500 g fresh or frozen", "500 g frisch oder TK", "500 غ طازجة أو مجمدة", "500 g taze veya donuk"),
    b2g1Ing("tomato", "Tomatoes", "Tomaten", "بندورة", "Domates", "4 grated + 1 tbsp paste", "4 gerieben + 1 EL Mark", "4 مبشورة + ملعقة معجون", "4 rendelenmiş + 1 yk salça"),
    b2g1Ing("onion", "Onion", "Zwiebel", "بصل", "Soğan", "1, chopped", "1, gehackt", "حبة مفرومة", "1, doğranmış"),
    b2g1Ing("garlic", "Garlic", "Knoblauch", "ثوم", "Sarımsak", "3 cloves", "3 Zehen", "3 فصوص", "3 diş"),
    b2g1Ing("olive-oil", "Olive oil", "Olivenöl", "زيت زيتون", "Zeytinyağı", "1/4 cup", "1/4 Tasse", "ربع كوب", "1/4 su bardağı"),
    b2g1Ing("spice", "Allspice (optional)", "Piment (optional)", "بهار حلو (اختياري)", "Yenibahar (isteğe bağlı)", "1/2 tsp", "1/2 TL", "نصف ملعقة", "1/2 tk"),
    b2g1Ing("salt", "Salt & pepper", "Salz & Pfeffer", "ملح وفلفل", "Tuz ve biber", "to taste", "nach Geschmack", "حسب الذوق", "damak tadına göre"),
  ],
  localeCopy: {
    en: b2g1Loc(
      "Syrian peas with tomato: a simple home stew of peas simmered in tomato sauce — everyday comfort with bread or rice.",
      "Syrian",
      ["Frozen peas work well.", "Cook until sauce is rich and peas tender.", "Serve with bread or vermicelli rice."],
      "Keeps 3 days refrigerated.",
      [
        "Warm olive oil; soften onion and garlic.",
        "Add grated tomato, paste, salt, pepper and optional allspice; simmer.",
        "Add peas and a splash of water; cook covered until tender.",
        "Uncover to thicken the sauce if needed.",
        "Serve hot with bread or rice.",
      ],
    ),
    de: b2g1Loc(
      "Syrische Erbsen mit Tomate: einfacher Hauseintopf — Alltagskomfort mit Brot oder Reis.",
      "Syrisch",
      ["TK-Erbsen eignen sich gut.", "Sauce reichhaltig und Erbsen zart kochen.", "Mit Brot oder Reis."],
      "3 Tage kühlbar.",
      [
        "Olivenöl erwärmen; Zwiebel und Knoblauch anschwitzen.",
        "Tomate, Mark, Salz, Pfeffer und optional Piment zugeben.",
        "Erbsen und etwas Wasser zugeben; zugedeckt garen.",
        "Bei Bedarf ohne Deckel eindicken.",
        "Heiß mit Brot oder Reis servieren.",
      ],
    ),
    ar: b2g1Loc(
      "بازلاء وبندورة على الطريقة السورية: يخنة بيتية بسيطة — راحة يومية مع الخبز أو الرز.",
      "سوري",
      ["البازيلاء المجمدة مناسبة.", "اطبخي حتى تغنى الصلصة وتطرى البازيلاء.", "مع خبز أو رز بالشعيرية."],
      "تُحفظ 3 أيام.",
      [
        "سخّني الزيت؛ ليّني البصل والثوم.",
        "أضيفي البندورة والمعجون والملح والفلفل والبهار الاختياري.",
        "أضيفي البازيلاء ورشة ماء؛ غطّي حتى تطرى.",
        "ارفعي الغطاء لتكثيف الصلصة إن لزم.",
        "قدّمي ساخنة مع خبز أو رز.",
      ],
    ),
    tr: b2g1Loc(
      "Suriye usulü domatesli bezelye: sade ev yahnisi — ekmek veya pilavla günlük rahat yemek.",
      "Suriye",
      ["Donuk bezelye uygundur.", "Sos zengin, bezelye yumuşak olsun.", "Ekmek veya şehriyeli pilavla."],
      "3 gün saklanır.",
      [
        "Zeytinyağında soğan ve sarımsağı yumuşatın.",
        "Domates, salça, tuz, biber ve isteğe bağlı yenibaharı ekleyin.",
        "Bezelye ve biraz su ekleyip kapağı kapalı pişirin.",
        "Gerekirse kapağı açıp koyulaştırın.",
        "Sıcak ekmek veya pilavla servis edin.",
      ],
    ),
  },
  naturalYield: {
    baseServingsMin: 3,
    baseServingsMax: 4,
    servingLabel: "Serves ~3 as a home-style main",
    scalingNote: "Scale peas and tomato together.",
  },
  defaultRole: "main",
  canServeAsMain: false,
  photo: b2g1Photo(
    "Homestyle Syrian peas in tomato sauce in a simple bowl.",
    "Stew as hero; calm neutrals.",
    "Bazella w banadoura — peas and tomato Syrian stew.",
    "/assets/dishes/arab/peas-with-tomato.jpg",
  ),
});

const STUFFED_CHICKEN: GeneratedRecipe = b2g1Recipe({
  matchKeys: [
    "syrian stuffed chicken",
    "stuffed chicken syrian",
    "dajaj mahshi",
    "دجاج محشي",
    "دجاج محشي سوري",
  ],
  canonicalTitle: "Syrian Stuffed Chicken",
  prepMinutes: 120,
  difficulty: "medium",
  servings: 3,
  mealTypes: ["main"],
  mealSlotRole: "dinner_complete",
  mealIntents: ["family_friendly", "special", "high_calorie"],
  proteinCategory: "chicken",
  budgetTier: "medium",
  suitability: ["guest_friendly", "everyday_host", "shareable"],
  moods: ["special"],
  dietaryTags: ["contains_meat"],
  allergens: ["Nuts"],
  ingredientTokens: ["chicken", "rice", "minced meat", "pine nuts", "allspice"],
  pantryIngredients: [
    { canonicalId: "chicken", role: "critical", tokens: ["chicken"] },
    { canonicalId: "rice", role: "critical", tokens: ["rice"] },
    { canonicalId: "minced-meat", role: "supporting", tokens: ["minced meat"] },
  ],
  ingredients: [
    b2g1Ing("chicken", "Whole chicken", "Ganzes Hähnchen", "دجاجة كاملة", "Bütün tavuk", "1.4–1.6 kg, cavity cleaned", "1,4–1,6 kg", "1.4–1.6 كغ", "1,4–1,6 kg"),
    b2g1Ing("rice", "Rice", "Reis", "أرز", "Pirinç", "1 cup (200 g), for stuffing", "1 Tasse (200 g)", "كوب (200 غ) للحشو", "1 su bardağı (200 g)"),
    b2g1Ing("minced-meat", "Minced meat", "Hackfleisch", "لحم مفروم", "Kıyma", "150 g", "150 g", "150 غرام", "150 g"),
    b2g1Ing("onion", "Onion", "Zwiebel", "بصل", "Soğan", "1 small, for stuffing", "1 kleine", "حبة صغيرة", "1 küçük"),
    b2g1Ing("pine-nuts", "Pine nuts", "Pinienkerne", "صنوبر", "Çam fıstığı", "3 tbsp, toasted", "3 EL geröstet", "3 ملاعق محمّص", "3 yk kavrulmuş"),
    b2g1Ing("spice", "Allspice & cinnamon", "Piment & Zimt", "بهار وقرفة", "Yenibahar ve tarçın", "1.5 tsp mix", "1,5 TL Mischung", "ملعقة ونصف", "1,5 tk"),
    b2g1Ing("butter", "Butter or ghee", "Butter oder Butterschmalz", "زبدة أو سمن", "Tereyağı veya sadeyağ", "2 tbsp, for rubbing", "2 EL", "ملعقتان", "2 yk"),
    b2g1Ing("salt", "Salt & pepper", "Salz & Pfeffer", "ملح وفلفل", "Tuz ve biber", "to taste", "nach Geschmack", "حسب الذوق", "damak tadına göre"),
  ],
  localeCopy: {
    en: b2g1Loc(
      "Syrian stuffed chicken: a whole bird filled with spiced rice, minced meat and pine nuts, roasted until golden.",
      "Syrian",
      ["Do not overpack the cavity — rice expands.", "Season the skin well.", "Rest before carving."],
      "Refrigerate up to 3 days; reheat covered.",
      [
        "Par-cook rice briefly; mix with browned minced meat, onion, pine nuts and spices.",
        "Season chicken inside and out; stuff loosely and tie or skewer the cavity.",
        "Rub with butter, salt and pepper.",
        "Roast at 190°C until juices run clear and skin is golden (about 75–90 minutes depending on size).",
        "Rest 10 minutes; carve and serve stuffing alongside.",
      ],
    ),
    de: b2g1Loc(
      "Syrisches gefülltes Hähnchen: ganzer Vogel mit gewürztem Reis, Hack und Pinienkernen, goldbraun geröstet.",
      "Syrisch",
      ["Höhle nicht zu voll stopfen.", "Haut gut würzen.", "Vor dem Zerlegen ruhen."],
      "Bis zu 3 Tage kühlen.",
      [
        "Reis kurz vorkochen; mit angebratenem Hack, Zwiebel, Pinienkernen und Gewürzen mischen.",
        "Hähnchen innen und außen würzen; locker füllen und verschließen.",
        "Mit Butter, Salz und Pfeffer einreiben.",
        "Bei 190 °C goldbraun garen (ca. 75–90 Min.).",
        "10 Min. ruhen; zerlegen und Füllung dazu servieren.",
      ],
    ),
    ar: b2g1Loc(
      "دجاج محشي سوري: دجاجة محشوّة بأرز متبّل ولحم مفروم وصنوبر، تُشوى حتى تذهبّ.",
      "سوري",
      ["لا تملئي التجويف بإفراط — الأرز ينتفخ.", "تبّلي الجلد جيداً.", "اتركيه يرتاح قبل التقطيع."],
      "يُحفظ حتى 3 أيام.",
      [
        "اسلقي الأرز قليلاً؛ اخلطيه مع اللحم المفروم المحمّر والبصل والصنوبر والبهار.",
        "تبّلي الدجاج من الداخل والخارج؛ احشيه برخاوة وأغلقي.",
        "ادهنيه بالزبدة والملح والفلفل.",
        "اشويه على 190° حتى ينضج ويذهبّ الجلد (حوالي 75–90 دقيقة).",
        "اتركيه 10 دقائق؛ قطّعيه وقدّمي الحشو إلى جانبه.",
      ],
    ),
    tr: b2g1Loc(
      "Suriye usulü içli tavuk: baharatlı pirinç, kıyma ve çam fıstığıyla doldurulmuş bütün tavuk.",
      "Suriye",
      ["İçi fazla doldurmayın — pirinç şişer.", "Deriyi iyi baharatlayın.", "Kesmeden önce dinlendirin."],
      "3 güne kadar saklanır.",
      [
        "Pirinci kısa haşlayıp kavrulmuş kıyma, soğan, çam fıstığı ve baharatla karıştırın.",
        "Tavuğu içten dıştan baharatlayıp gevşek doldurun.",
        "Tereyağı, tuz ve biber sürün.",
        "190°C’de altın rengi olana dek pişirin (yaklaşık 75–90 dk).",
        "10 dk dinlendirip dilimleyin; iç harcı yanında servis edin.",
      ],
    ),
  },
  naturalYield: {
    baseServingsMin: 3,
    baseServingsMax: 4,
    servingLabel: "One stuffed chicken · serves ~3–4",
    scalingNote: "Use a larger bird and scale stuffing proportionally.",
  },
  defaultRole: "main",
  canServeAsMain: false,
  photo: b2g1Photo(
    "Whole roasted Syrian stuffed chicken with rice-meat stuffing visible.",
    "Whole bird as hero on a simple platter.",
    "Syrian dajaj mahshi — stuffed whole chicken with rice and meat.",
    "/assets/dishes/arab/syrian-stuffed-chicken.jpg",
  ),
});

const FREEKEH: GeneratedRecipe = b2g1Recipe({
  matchKeys: [
    "freekeh with meat",
    "freekeh bil lahm",
    "frikeh with meat",
    "فريكة باللحم",
    "فريكة باللحمة",
    "فريكة سورية",
  ],
  canonicalTitle: "Freekeh with Meat",
  prepMinutes: 80,
  difficulty: "medium",
  servings: 3,
  mealTypes: ["main"],
  mealSlotRole: "dinner_complete",
  mealIntents: ["family_friendly", "healthy", "high_calorie"],
  proteinCategory: "lamb",
  budgetTier: "medium",
  suitability: ["everyday_host", "guest_friendly", "shareable"],
  moods: ["everyday", "special"],
  dietaryTags: ["contains_meat"],
  allergens: ["Gluten", "Nuts"],
  ingredientTokens: ["freekeh", "lamb", "onion", "cinnamon", "almonds"],
  pantryIngredients: [
    { canonicalId: "freekeh", role: "critical", tokens: ["freekeh", "frikeh"] },
    { canonicalId: "meat", role: "critical", tokens: ["lamb", "meat"] },
    { canonicalId: "onion", role: "supporting", tokens: ["onion"] },
  ],
  ingredients: [
    b2g1Ing("freekeh", "Freekeh (green cracked wheat)", "Freekeh (grüner Weizen)", "فريكة", "Firik", "1.5 cups (300 g), rinsed", "1,5 Tassen (300 g)", "كوب ونصف (300 غ)", "1,5 su bardağı (300 g)"),
    b2g1Ing("meat", "Lamb pieces", "Lammstücke", "قطع لحم غنم", "Kuzu eti", "500 g", "500 g", "500 غرام", "500 g"),
    b2g1Ing("onion", "Onion", "Zwiebel", "بصل", "Soğan", "1, chopped", "1, gehackt", "حبة مفرومة", "1, doğranmış"),
    b2g1Ing("spice", "Cinnamon & allspice", "Zimt & Piment", "قرفة وبهار", "Tarçın ve yenibahar", "1 tsp cinnamon + 1 tsp allspice", "je 1 TL", "ملعقة من كل", "1 tk her birinden"),
    b2g1Ing("almonds", "Toasted almonds or pine nuts", "Mandeln/Pinienkerne", "لوز أو صنوبر", "Badem/çam fıstığı", "1/4 cup garnish", "1/4 Tasse", "ربع كوب", "1/4 su bardağı"),
    b2g1Ing("ghee", "Ghee or oil", "Butterschmalz oder Öl", "سمن أو زيت", "Sadeyağ veya yağ", "3 tbsp", "3 EL", "3 ملاعق", "3 yk"),
    b2g1Ing("salt", "Salt & pepper", "Salz & Pfeffer", "ملح وفلفل", "Tuz ve biber", "to taste", "nach Geschmack", "حسب الذوق", "damak tadına göre"),
  ],
  localeCopy: {
    en: b2g1Loc(
      "Syrian freekeh with meat: smoky green wheat simmered with tender lamb — a hearty Levantine main.",
      "Syrian",
      ["Rinse freekeh well to reduce smokiness if preferred.", "Cook meat until tender before adding freekeh.", "Garnish with toasted nuts."],
      "Refrigerate up to 3 days; reheat with a splash of broth.",
      [
        "Brown meat with onion in ghee; season with cinnamon, allspice, salt and pepper.",
        "Add water to cover and simmer until meat is tender; reserve broth.",
        "Add rinsed freekeh with enough broth to cook like rice.",
        "Simmer covered until freekeh is tender and liquid absorbed.",
        "Rest 5 minutes; garnish with toasted almonds or pine nuts.",
      ],
    ),
    de: b2g1Loc(
      "Syrisches Freekeh mit Fleisch: rauchiger grüner Weizen mit zartem Lamm — herzhaftes levantinisches Hauptgericht.",
      "Syrisch",
      ["Freekeh gut spülen.", "Fleisch zuerst zart garen.", "Mit gerösteten Nüssen garnieren."],
      "Bis zu 3 Tage kühlen.",
      [
        "Fleisch mit Zwiebel in Butterschmalz anbräunen; würzen.",
        "Mit Wasser bedecken und garen; Brühe zurückhalten.",
        "Abgespültes Freekeh mit genug Brühe wie Reis garen.",
        "Zugedeckt köcheln, bis zart und Flüssigkeit aufgenommen.",
        "5 Min. ruhen; mit Nüssen garnieren.",
      ],
    ),
    ar: b2g1Loc(
      "فريكة باللحم سورية: قمح أخضر مدخّن مع لحم طري — طبق رئيسي شامي دسم.",
      "سوري",
      ["اغسلي الفريكة جيداً.", "اطبخي اللحم حتى يطرى قبل إضافة الفريكة.", "زيّني بالمكسّرات المحمّصة."],
      "تُحفظ حتى 3 أيام.",
      [
        "حمّري اللحم مع البصل بالسمن؛ تبّلي بالقرفة والبهار.",
        "غطّي بالماء واطبخي حتى يطرى اللحم؛ احتفظي بالمرق.",
        "أضيفي الفريكة المغسولة مع مرق كافٍ كالأرز.",
        "اطبخي مغطّاة حتى تنضج وتُمتصّ السوائل.",
        "اتركيها 5 دقائق؛ زيّني باللوز أو الصنوبر.",
      ],
    ),
    tr: b2g1Loc(
      "Suriye usulü etli firik: dumanlı yeşil buğday ve yumuşak kuzu — doyurucu Levanten ana yemek.",
      "Suriye",
      ["Firiği iyi yıkayın.", "Önce eti yumuşatın.", "Kavrulmuş kuruyemişle süsleyin."],
      "3 güne kadar saklanır.",
      [
        "Eti soğanla sadeyağda kavurup baharatlayın.",
        "Su ekleyip yumuşayana dek pişirin; suyunu ayırın.",
        "Yıkanmış firiği pirinç gibi yeterli suyla ekleyin.",
        "Kapağı kapalı yumuşayıp suyu çekilene dek pişirin.",
        "5 dk dinlendirip kuruyemişle süsleyin.",
      ],
    ),
  },
  naturalYield: {
    baseServingsMin: 3,
    baseServingsMax: 4,
    servingLabel: "Serves ~3 as a hearty main",
    scalingNote: "Scale freekeh and meat together.",
  },
  defaultRole: "main",
  canServeAsMain: false,
  photo: b2g1Photo(
    "Bowl of Syrian freekeh with lamb pieces and toasted nuts.",
    "Freekeh and meat as hero.",
    "Freekeh with meat — smoky green wheat Syrian main.",
    "/assets/dishes/arab/freekeh-with-meat.jpg",
  ),
});

const SAVORY_PASTRIES: GeneratedRecipe = b2g1Recipe({
  matchKeys: [
    "syrian savory pastries",
    "syrian pastry dough",
    "syrian fatayer dough",
    "معجنات سورية",
    "عجينة معجنات سورية",
    "عجينة فطاير",
  ],
  canonicalTitle: "Syrian Savory Pastries",
  prepMinutes: 90,
  difficulty: "medium",
  servings: 4,
  mealTypes: ["side"],
  mealSlotRole: "light_meal",
  mealIntents: ["family_friendly", "budget", "special"],
  proteinCategory: "mixed",
  budgetTier: "low",
  suitability: ["everyday_host", "guest_friendly", "shareable"],
  moods: ["everyday", "special"],
  dietaryTags: ["contains_egg", "vegetarian_ok"],
  allergens: ["Gluten", "Eggs", "Dairy"],
  ingredientTokens: ["flour", "yeast", "olive oil", "yogurt", "cheese", "zaatar"],
  pantryIngredients: [
    { canonicalId: "flour", role: "critical", tokens: ["flour"] },
    { canonicalId: "yeast", role: "critical", tokens: ["yeast"] },
    { canonicalId: "olive-oil", role: "supporting", tokens: ["olive oil"] },
  ],
  ingredients: [
    b2g1Ing("flour", "Flour", "Mehl", "طحين", "Un", "500 g", "500 g", "500 غرام", "500 g"),
    b2g1Ing("yeast", "Instant yeast", "Trockenhefe", "خميرة فورية", "İnstant maya", "1 tbsp (7–8 g)", "1 EL (7–8 g)", "ملعقة كبيرة", "1 yk (7–8 g)"),
    b2g1Ing("olive-oil", "Olive oil", "Olivenöl", "زيت زيتون", "Zeytinyağı", "4 tbsp + more for brushing", "4 EL", "4 ملاعق", "4 yk"),
    b2g1Ing("yogurt", "Yogurt or milk", "Joghurt oder Milch", "لبن أو حليب", "Yoğurt veya süt", "1/2 cup warm", "1/2 Tasse warm", "نصف كوب دافئ", "1/2 su bardağı ılık"),
    b2g1Ing("sugar", "Sugar", "Zucker", "سكر", "Şeker", "1 tsp", "1 TL", "ملعقة صغيرة", "1 tk"),
    b2g1Ing("salt", "Salt", "Salz", "ملح", "Tuz", "1 tsp", "1 TL", "ملعقة صغيرة", "1 tk"),
    b2g1Ing("cheese", "White cheese (optional filling)", "Weißkäse (optionale Füllung)", "جبنة بيضاء (حشوة اختيارية)", "Beyaz peynir (isteğe bağlı)", "200 g crumbled", "200 g zerbrösel", "200 غ مفتتة", "200 g ufaklanmış"),
    b2g1Ing("zaatar", "Zaatar (optional filling)", "Zaatar (optionale Füllung)", "زعتر (حشوة اختيارية)", "Zaatar (isteğe bağlı)", "3 tbsp + olive oil", "3 EL + Öl", "3 ملاعق + زيت", "3 yk + yağ"),
    b2g1Ing("egg", "Egg wash (optional)", "Eistreiche (optional)", "دهان بيض (اختياري)", "Yumurta (isteğe bağlı)", "1 egg beaten", "1 verquirlt", "بيضة مخفوقة", "1 çırpılmış"),
  ],
  localeCopy: {
    en: b2g1Loc(
      "Syrian savory pastry core dough: one soft yeast dough for family pastries. Use with cheese or zaatar here; meat sfiha and spinach fatayer are separate recipes that share this dough tradition.",
      "Syrian",
      [
        "Treat this as the master dough — do not duplicate full recipes for every filling.",
        "Supported simple fillings here: white cheese, or zaatar-oil.",
        "For meat open pastries see Syrian Sfiha; for spinach triangles see Spinach Fatayer.",
      ],
      "Dough can rest refrigerated up to 24 hours. Baked pastries keep 2 days; reheat in the oven.",
      [
        "Dissolve yeast with sugar in warm yogurt/milk; rest until foamy.",
        "Mix flour, salt, olive oil and yeast mixture into a soft dough; knead 8–10 minutes.",
        "Rise covered until doubled (about 1 hour).",
        "Divide; for cheese: fill rounds with crumbled white cheese; for zaatar: spread zaatar mixed with olive oil on flat ovals.",
        "Brush with olive oil or egg wash; bake at 220°C until golden.",
        "Serve warm as bakery/light meal.",
      ],
    ),
    de: b2g1Loc(
      "Syrischer Herzstück-Teig für herzhafte Gebäcke: ein Hefeteig für die Familie. Hier Käse oder Zaatar; Fleisch-Sfiha und Spinat-Fatayer sind eigene Rezepte.",
      "Syrisch",
      [
        "Als Meisterteig behandeln — nicht für jede Füllung ein Duplikat-Rezept.",
        "Einfache Füllungen hier: Weißkäse oder Zaatar-Öl.",
        "Für Fleisch siehe Syrian Sfiha; für Spinat siehe Spinach Fatayer.",
      ],
      "Teig bis 24 Std. kühlbar. Gebäck 2 Tage; im Ofen erwärmen.",
      [
        "Hefe mit Zucker in warmem Joghurt/Milch lösen; schäumen lassen.",
        "Mehl, Salz, Olivenöl und Hefemischung zu weichem Teig verkneten (8–10 Min.).",
        "Zugedeckt gehen lassen bis verdoppelt (ca. 1 Std.).",
        "Teilen; Käse: mit Weißkäse füllen; Zaatar: Zaatar-Öl auf flache Ovale streichen.",
        "Mit Öl oder Ei bestreichen; bei 220 °C goldbraun backen.",
        "Warm als Gebäck/leichte Mahlzeit servieren.",
      ],
    ),
    ar: b2g1Loc(
      "عجينة معجنات سورية الأساسية: عجينة خميرة طرية للعائلة. هنا جبنة أو زعتر؛ الصفيحة وفطاير السبانخ وصفات منفصلة تشترك بهذا التقليد.",
      "سوري",
      [
        "اعتبريها عجينة أم — لا تكرّري وصفة كاملة لكل حشوة.",
        "حشوات بسيطة هنا: جبنة بيضاء أو زعتر بزيت.",
        "للحمة المفتوحة انظري Syrian Sfiha؛ لمثلثات السبانخ Spinach Fatayer.",
      ],
      "العجين حتى 24 ساعة في الثلاجة. المعجنات يومان؛ أعيدي تسخينها بالفرن.",
      [
        "ذوّبي الخميرة مع السكر في اللبن/الحليب الدافئ حتى تزبد.",
        "اخلطي الطحين والملح والزيت والخميرة إلى عجينة طرية؛ اعجني 8–10 دقائق.",
        "اتركيها ترتاح مغطّاة حتى تتضاعف (حوالي ساعة).",
        "قسّمي؛ للجبنة: احشي بدوائر؛ للزعتر: وزّعي زعتر بزيت على أشكال بيضاوية.",
        "ادهني بزيت أو بيض؛ اخبزي على 220° حتى تذهبّ.",
        "قدّمي دافئة كمعجنات/وجبة خفيفة.",
      ],
    ),
    tr: b2g1Loc(
      "Suriye tuzlu börek ana hamuru: aile için yumuşak mayalı hamur. Burada peynir veya zaatar; etli sfiha ve ıspanaklı fatayer ayrı tariflerdir.",
      "Suriye",
      [
        "Ana hamur olarak düşünün — her iç için ayrı tarif çoğaltmayın.",
        "Basit içler: beyaz peynir veya zaatar-yağ.",
        "Etli açık börek için Syrian Sfiha; ıspanak üçgeni için Spinach Fatayer.",
      ],
      "Hamur 24 saate kadar buzdolabında. Pişmişler 2 gün; fırında ısıtın.",
      [
        "Mayayı şekerle ılık yoğurt/sütte köpürene dek bekletin.",
        "Un, tuz, zeytinyağı ve mayayı yumuşak hamur yapıp 8–10 dk yoğurun.",
        "Üzeri kapalı iki kat olana dek mayalandırın (yaklaşık 1 saat).",
        "Bölün; peynir: daireleri doldurun; zaatar: yağlı zaatarı ovalere sürün.",
        "Yağ veya yumurta sürüp 220°C’de altın rengi pişirin.",
        "Ilık börek/hafif öğün olarak servis edin.",
      ],
    ),
  },
  naturalYield: {
    baseServingsMin: 3,
    baseServingsMax: 4,
    servingLabel: "Makes ~12–16 small pastries · serves 3–4",
    scalingNote: "Scale flour and liquid together. Meat and spinach fillings live in separate recipes.",
  },
  defaultRole: "side",
  canServeAsMain: true,
  photo: b2g1Photo(
    "Tray of Syrian savory pastries — cheese and zaatar styles — homemade look.",
    "Pastries as hero on a simple tray.",
    "Core Syrian pastry dough family — not a duplicate of sfiha or spinach fatayer.",
    "/assets/dishes/arab/syrian-savory-pastries.jpg",
  ),
});

const SFIHA: GeneratedRecipe = b2g1Recipe({
  matchKeys: [
    "syrian sfiha",
    "sfiha",
    "sfeeha",
    "lahm bi ajeen syrian",
    "lahm bi ajin",
    "صفيحة باللحمة",
    "صفيحة",
    "لحم بعجين",
  ],
  canonicalTitle: "Syrian Sfiha",
  prepMinutes: 90,
  difficulty: "medium",
  servings: 4,
  mealTypes: ["side"],
  mealSlotRole: "light_meal",
  mealIntents: ["family_friendly", "budget", "special"],
  proteinCategory: "lamb",
  budgetTier: "low",
  suitability: ["everyday_host", "guest_friendly", "shareable"],
  moods: ["everyday", "special"],
  dietaryTags: ["contains_meat"],
  allergens: ["Gluten"],
  ingredientTokens: ["flour", "minced meat", "tomato", "onion", "pomegranate molasses"],
  pantryIngredients: [
    { canonicalId: "flour", role: "critical", tokens: ["flour", "dough"] },
    { canonicalId: "minced-meat", role: "critical", tokens: ["minced meat"] },
    { canonicalId: "tomato", role: "supporting", tokens: ["tomato"] },
    { canonicalId: "onion", role: "supporting", tokens: ["onion"] },
  ],
  ingredients: [
    b2g1Ing("flour", "Flour", "Mehl", "طحين", "Un", "400 g, for dough", "400 g für Teig", "400 غ للعجين", "400 g hamur"),
    b2g1Ing("yeast", "Yeast", "Hefe", "خميرة", "Maya", "2 tsp", "2 TL", "ملعقتان صغيرتان", "2 tk"),
    b2g1Ing("olive-oil", "Olive oil", "Olivenöl", "زيت زيتون", "Zeytinyağı", "3 tbsp", "3 EL", "3 ملاعق", "3 yk"),
    b2g1Ing("minced-meat", "Minced lamb or beef", "Hackfleisch", "لحم مفروم", "Kıyma", "350 g", "350 g", "350 غرام", "350 g"),
    b2g1Ing("tomato", "Tomato", "Tomate", "بندورة", "Domates", "2, finely chopped or grated", "2, fein", "حبتان مفرومتان", "2, ince"),
    b2g1Ing("onion", "Onion", "Zwiebel", "بصل", "Soğan", "1, finely chopped", "1, fein", "حبة ناعمة", "1, ince"),
    b2g1Ing("pepper", "Green pepper (optional)", "Paprika (optional)", "فلفل أخضر (اختياري)", "Yeşil biber (isteğe bağlı)", "1 small", "1 kleine", "حبة صغيرة", "1 küçük"),
    b2g1Ing("molasses", "Pomegranate molasses", "Granatapfelmelasse", "دبس رمان", "Nar ekşisi", "1–2 tbsp", "1–2 EL", "1–2 ملاعق", "1–2 yk"),
    b2g1Ing("spice", "Allspice & chili", "Piment & Chili", "بهار وفلفل حار", "Yenibahar ve pul biber", "1 tsp allspice + chili to taste", "1 TL + Chili", "ملعقة بهار + فلفل", "1 tk + pul biber"),
    b2g1Ing("salt", "Salt", "Salz", "ملح", "Tuz", "to taste", "nach Geschmack", "حسب الذوق", "damak tadına göre"),
  ],
  localeCopy: {
    en: b2g1Loc(
      "Syrian sfiha: open flat meat pastries with minced meat, tomato and onion — Levantine lahm bi ajeen style, distinct from Turkish lahmacun.",
      "Syrian",
      ["Spread topping thinly so it cooks through.", "Pomegranate molasses gives the Syrian tang.", "Bake hot for crisp edges."],
      "Best fresh; reheat in a hot oven up to 2 days.",
      [
        "Make a soft yeast dough with flour, yeast, oil, salt and warm water; rise until doubled.",
        "Mix raw minced meat with tomato, onion, optional pepper, molasses, spices and salt.",
        "Divide dough into small balls; flatten into thin ovals or rounds.",
        "Spread a thin layer of meat topping on each.",
        "Bake at 230°C until dough is cooked and topping browned.",
        "Serve hot as a light meal or bakery plate.",
      ],
    ),
    de: b2g1Loc(
      "Syrische Sfiha: offene Fleischfladen mit Hack, Tomate und Zwiebel — levantinisch, nicht türkisches Lahmacun.",
      "Syrisch",
      ["Belag dünn streichen.", "Granatapfelmelasse für syrische Säure.", "Heiß backen."],
      "Am besten frisch; bis 2 Tage im heißen Ofen erwärmen.",
      [
        "Weichen Hefeteig bereiten; gehen lassen.",
        "Rohes Hack mit Tomate, Zwiebel, Melasse und Gewürzen mischen.",
        "Teig in kleine Kugeln teilen; dünn ausdrücken.",
        "Dünn mit Fleischbelag bestreichen.",
        "Bei 230 °C backen bis gar und gebräunt.",
        "Heiß als leichte Mahlzeit servieren.",
      ],
    ),
    ar: b2g1Loc(
      "صفيحة سورية باللحمة: معجنات مفتوحة بلحم مفروم وبندورة وبصل — أسلوب شامي، متميزة عن اللحم بعجين التركي.",
      "سوري",
      ["وزّعي الحشوة رقيقة.", "دبس الرمان يعطي الحموضة السورية.", "اخبزي على حرارة عالية."],
      "الأفضل طازجة؛ أعيدي التسخين بفرن حار حتى يومين.",
      [
        "اعجني عجينة خميرة طرية واتركيها تختمر.",
        "اخلطي اللحم النيء مع البندورة والبصل ودبس الرمان والبهار.",
        "قسّمي العجين كرات وافرديها رقيقة.",
        "وزّعي طبقة رقيقة من الحشوة.",
        "اخبزي على 230° حتى تنضج وتحمر.",
        "قدّمي ساخنة كوجبة خفيفة.",
      ],
    ),
    tr: b2g1Loc(
      "Suriye sfihası: kıyma, domates ve soğanlı açık etli börek — Türk lahmacundan ayrı Levanten kimlik.",
      "Suriye",
      ["Harçı ince yayın.", "Nar ekşisi Suriye ekşiliğini verir.", "Sıcak fırında pişirin."],
      "En iyisi taze; 2 güne kadar sıcak fırında ısıtın.",
      [
        "Yumuşak mayalı hamur yoğurup mayalandırın.",
        "Çiğ kıymayı domates, soğan, nar ekşisi ve baharatla karıştırın.",
        "Hamuru bezeler yapıp ince açın.",
        "İnce et harcı sürün.",
        "230°C’de hamur pişip üzeri kızarana dek pişirin.",
        "Sıcak hafif öğün olarak servis edin.",
      ],
    ),
  },
  naturalYield: {
    baseServingsMin: 3,
    baseServingsMax: 4,
    servingLabel: "Makes ~10–12 sfiha · serves 3–4",
    scalingNote: "Scale dough and topping together. No existing sfiha/lahm bi ajeen in catalog.",
  },
  defaultRole: "side",
  canServeAsMain: true,
  photo: b2g1Photo(
    "Syrian open meat sfiha pastries with minced meat tomato topping.",
    "Several sfiha on a tray as hero.",
    "Syrian sfiha / lahm bi ajeen — not Turkish lahmacun.",
    "/assets/dishes/arab/syrian-sfiha.jpg",
  ),
});

const SPINACH_FATAYER: GeneratedRecipe = b2g1Recipe({
  matchKeys: [
    "spinach fatayer",
    "fatayer sabanekh",
    "spinach triangles",
    "فطاير سبانخ",
    "فطائر سبانخ",
    "فطاير السبانخ",
  ],
  canonicalTitle: "Spinach Fatayer",
  prepMinutes: 90,
  difficulty: "medium",
  servings: 4,
  mealTypes: ["side"],
  mealSlotRole: "light_meal",
  mealIntents: ["family_friendly", "budget", "healthy"],
  proteinCategory: "vegetable",
  budgetTier: "low",
  suitability: ["everyday_host", "guest_friendly", "shareable"],
  moods: ["everyday", "special"],
  dietaryTags: ["vegetarian_ok", "vegan_ok"],
  allergens: ["Gluten"],
  ingredientTokens: ["flour", "spinach", "onion", "sumac", "lemon", "olive oil"],
  pantryIngredients: [
    { canonicalId: "flour", role: "critical", tokens: ["flour"] },
    { canonicalId: "spinach", role: "critical", tokens: ["spinach"] },
    { canonicalId: "sumac", role: "supporting", tokens: ["sumac"] },
    { canonicalId: "onion", role: "supporting", tokens: ["onion"] },
  ],
  ingredients: [
    b2g1Ing("flour", "Flour", "Mehl", "طحين", "Un", "400 g", "400 g", "400 غرام", "400 g"),
    b2g1Ing("yeast", "Yeast", "Hefe", "خميرة", "Maya", "2 tsp", "2 TL", "ملعقتان صغيرتان", "2 tk"),
    b2g1Ing("olive-oil", "Olive oil", "Olivenöl", "زيت زيتون", "Zeytinyağı", "4 tbsp", "4 EL", "4 ملاعق", "4 yk"),
    b2g1Ing("spinach", "Spinach", "Spinat", "سبانخ", "Ispanak", "500 g, washed and chopped", "500 g, gehackt", "500 غ مغسولة مفرومة", "500 g yıkanmış doğranmış"),
    b2g1Ing("onion", "Onion", "Zwiebel", "بصل", "Soğan", "1 large, finely chopped", "1 große, fein", "حبة كبيرة ناعمة", "1 büyük ince"),
    b2g1Ing("sumac", "Sumac", "Sumach", "سماق", "Sumak", "1.5–2 tbsp", "1,5–2 EL", "1.5–2 ملاعق", "1,5–2 yk"),
    b2g1Ing("lemon", "Lemon juice", "Zitronensaft", "عصير ليمون", "Limon suyu", "2 tbsp", "2 EL", "ملعقتان", "2 yk"),
    b2g1Ing("salt", "Salt & pepper", "Salz & Pfeffer", "ملح وفلفل", "Tuz ve biber", "to taste", "nach Geschmack", "حسب الذوق", "damak tadına göre"),
  ],
  localeCopy: {
    en: b2g1Loc(
      "Spinach fatayer: triangular Syrian pastries with a tangy spinach-onion-sumac filling — classic Levantine sour-savory bakery.",
      "Syrian",
      ["Salt spinach and squeeze dry so pastries are not soggy.", "Sumac and lemon give the Levantine tang.", "Seal triangles firmly."],
      "Best same day; reheat in oven up to 2 days.",
      [
        "Make soft yeast dough with flour, yeast, oil, salt and warm water; rise until doubled.",
        "Salt chopped spinach, rest, then squeeze out excess water.",
        "Mix spinach with onion, sumac, lemon, olive oil, salt and pepper.",
        "Roll dough rounds; place filling; fold into tight triangles.",
        "Bake at 220°C until golden.",
        "Serve warm as bakery/side/light meal.",
      ],
    ),
    de: b2g1Loc(
      "Spinat-Fatayer: dreieckige syrische Teigtaschen mit säuerlicher Spinat-Zwiebel-Sumach-Füllung.",
      "Syrisch",
      ["Spinat salzen und ausdrücken.", "Sumach und Zitrone für die Säure.", "Dreiecke fest schließen."],
      "Am besten am selben Tag; bis 2 Tage im Ofen erwärmen.",
      [
        "Weichen Hefeteig bereiten; gehen lassen.",
        "Spinat salzen, ruhen, gut ausdrücken.",
        "Mit Zwiebel, Sumach, Zitrone, Öl, Salz und Pfeffer mischen.",
        "Teigkreise füllen und zu festen Dreiecken falten.",
        "Bei 220 °C goldbraun backen.",
        "Warm als Gebäck/Beilage servieren.",
      ],
    ),
    ar: b2g1Loc(
      "فطاير سبانخ: مثلثات سورية بحشوة سبانخ وبصل وسماق حامضية — معجنات شامية كلاسيكية.",
      "سوري",
      ["ملّحي السبانخ واعصريها جيداً.", "السماق والليمون يعطيان الحموضة.", "أغلقي المثلثات بإحكام."],
      "الأفضل نفس اليوم؛ أعيدي التسخين بالفرن حتى يومين.",
      [
        "اعجني عجينة خميرة طرية واتركيها تختمر.",
        "ملّحي السبانخ المفرومة ثم اعصري الماء الزائد.",
        "اخلطي مع البصل والسماق والليمون والزيت والملح والفلفل.",
        "افردي دوائر، ضعي الحشوة، واطوي مثلثات محكمة.",
        "اخبزي على 220° حتى تذهبّ.",
        "قدّمي دافئة كمعجنات/جانب/وجبة خفيفة.",
      ],
    ),
    tr: b2g1Loc(
      "Ispanaklı fatayer: sumaklı, limonlu ekşi-baharatlı ıspanak-soğan içli Suriye üçgen böreği.",
      "Suriye",
      ["Ispanağı tuzlayıp suyunu iyice sıkın.", "Sumak ve limon Levanten ekşiliğini verir.", "Üçgenleri sıkı kapatın."],
      "Aynı gün en iyisi; 2 güne kadar fırında ısıtın.",
      [
        "Yumuşak mayalı hamur yapıp mayalandırın.",
        "Doğranmış ıspanağı tuzlayıp suyunu sıkın.",
        "Soğan, sumak, limon, yağ, tuz ve biberle karıştırın.",
        "Hamur dairelerini doldurup sıkı üçgen kapatın.",
        "220°C’de altın rengi pişirin.",
        "Ilık börek/yan/hafif öğün olarak servis edin.",
      ],
    ),
  },
  naturalYield: {
    baseServingsMin: 3,
    baseServingsMax: 4,
    servingLabel: "Makes ~12 triangles · serves 3–4",
    scalingNote: "Scale dough and spinach filling together.",
  },
  defaultRole: "side",
  canServeAsMain: true,
  photo: b2g1Photo(
    "Triangular Syrian spinach fatayer with golden pastry, homemade look.",
    "Triangles on a simple tray as hero.",
    "Spinach fatayer with sumac-lemon tang — Levantine identity.",
    "/assets/dishes/arab/spinach-fatayer.jpg",
  ),
});

export const ARAB_BATCH_2_GROUP_1_B: GeneratedRecipe[] = [
  ARTICHOKE_SALAD,
  OUZI,
  PEAS_TOMATO,
  STUFFED_CHICKEN,
  FREEKEH,
  SAVORY_PASTRIES,
  SFIHA,
  SPINACH_FATAYER,
];
