/**
 * Golden personas — realistic user profiles for Fitness Brain quality validation.
 * Each persona runs through runBrainPipeline with deterministic clock settings.
 */

import type { ActivityLogEntry } from "../activity/types";
import type { DailyBehaviorLog } from "../storage/behaviorSignals";
import type { BrainValidationClock, UserDataInput } from "../types";
import type { PersonaExpectations } from "./personaExpectations";

export type GoldenPersona = {
  id: string;
  label: string;
  narrative: string;
  userData: UserDataInput;
  clock: BrainValidationClock;
  activityLogs?: ActivityLogEntry[];
  behaviorLogs?: DailyBehaviorLog[];
  expectations: PersonaExpectations;
};

const TRAINING_MWF: number[] = [1, 3, 5];

function todayIsoDate(): string {
  return new Date().toISOString().slice(0, 10);
}

function activityLog(
  activityId: string,
  durationMinutes: number,
  intensity: "light" | "moderate" | "hard",
  estimatedMET: number,
  estimatedCalories: number,
): ActivityLogEntry {
  const date = todayIsoDate();
  return {
    id: `val-${activityId}-${durationMinutes}`,
    activityId,
    activityCategory: activityId === "running" ? "running" : "strength",
    durationMinutes,
    intensity,
    estimatedMET,
    estimatedCalories,
    energySystem: activityId === "running" ? "aerobic" : "anaerobic",
    recoveryPriority: durationMinutes >= 45 ? "high" : "moderate",
    hydrationImportance: activityId === "running" ? "high" : "moderate",
    proteinImportance: activityId === "strength_training" ? "high" : "moderate",
    date,
    time: "10:30",
    localInstallationId: "validation-installation",
    loggedAt: `${date}T10:30:00.000Z`,
  };
}

export const GOLDEN_PERSONAS: GoldenPersona[] = [
  {
    id: "weight_loss_user",
    label: "Weight loss user",
    narrative: "Female office worker targeting sustainable fat loss with moderate activity.",
    userData: {
      age: 34,
      gender: "female",
      heightCm: 168,
      weightKg: 82,
      goal: "lose",
      activityLevel: "light",
      experienceLevel: "intermediate",
      primarySportId: "bodybuilding",
      trainingDays: TRAINING_MWF,
      caloriesEaten: 950,
      proteinEatenG: 65,
      waterLitersConsumed: 1.6,
      sleepHours: 7,
      adherenceScore: 72,
      consecutiveTrainingDays: 1,
      trainedYesterday: false,
    },
    clock: { hour: 11, dayOfWeek: 3 },
    expectations: {
      rationale:
        "Fat-loss goal should produce a calorie deficit below TDEE; midday should not ignore nutrition progress.",
      shouldPrioritize: [
        "hydration_focus",
        "protein_focus",
        "protein_low",
        "calorie_balance",
        "steady_progress",
        "complete_workout",
      ],
      mustNotRecommend: ["overtraining_risk"],
      metabolism: { goal: "fat_loss", dailyTargetBelowTdee: true },
      validationMustPass: true,
    },
  },
  {
    id: "muscle_gain_user",
    label: "Muscle gain user",
    narrative: "Active male lifter with surplus calories and high protein target.",
    userData: {
      age: 28,
      gender: "male",
      heightCm: 180,
      weightKg: 78,
      goal: "muscle",
      activityLevel: "active",
      experienceLevel: "intermediate",
      primarySportId: "bodybuilding",
      trainingDays: TRAINING_MWF,
      caloriesEaten: 2100,
      proteinEatenG: 120,
      waterLitersConsumed: 2.5,
      sleepHours: 7.5,
      adherenceScore: 80,
      consecutiveTrainingDays: 1,
    },
    clock: { hour: 12, dayOfWeek: 1 },
    expectations: {
      rationale: "Muscle-gain goal applies a conservative surplus and higher protein g/kg.",
      shouldPrioritize: [
        "complete_workout",
        "protein_focus",
        "protein_low",
        "steady_progress",
        "movement_day",
      ],
      mustNotRecommend: ["overtraining_risk", "recovery_rest"],
      metabolism: { goal: "muscle_gain", dailyTargetAboveTdee: true, minProteinPerKg: 1.9 },
      validationMustPass: true,
    },
  },
  {
    id: "maintenance_user",
    label: "Maintenance user",
    narrative: "Balanced adult maintaining weight with moderate habits.",
    userData: {
      age: 40,
      gender: "female",
      heightCm: 165,
      weightKg: 62,
      goal: "fit",
      activityLevel: "moderate",
      experienceLevel: "intermediate",
      primarySportId: "bodybuilding",
      trainingDays: TRAINING_MWF,
      caloriesEaten: 1800,
      proteinEatenG: 90,
      waterLitersConsumed: 2.1,
      sleepHours: 7,
      adherenceScore: 75,
    },
    clock: { hour: 13, dayOfWeek: 5 },
    expectations: {
      rationale: "Maintenance goal keeps calorie adjustment near zero with stable macro targets.",
      shouldPrioritize: [
        "complete_workout",
        "steady_progress",
        "movement_day",
        "hydration_focus",
        "protein_focus",
      ],
      metabolism: { goal: "maintenance", goalAdjustmentNearZero: true },
      validationMustPass: true,
    },
  },
  {
    id: "beginner",
    label: "Beginner",
    narrative: "New trainee on first structured program — should not receive advanced splits.",
    userData: {
      age: 22,
      gender: "male",
      heightCm: 175,
      weightKg: 70,
      goal: "fit",
      activityLevel: "sedentary",
      experienceLevel: "beginner",
      primarySportId: "bodybuilding",
      trainingDays: TRAINING_MWF,
      caloriesEaten: 1400,
      proteinEatenG: 70,
      waterLitersConsumed: 1.5,
      sleepHours: 7,
      adherenceScore: 60,
    },
    clock: { hour: 10, dayOfWeek: 1 },
    expectations: {
      rationale: "Beginners on a training day receive full-body basics, not advanced split sessions.",
      shouldPrioritize: ["complete_workout", "steady_progress", "movement_day", "hydration_focus"],
      trainingMustInclude: ["Full-body basics"],
      trainingMustNotInclude: ["Lower body strength", "Upper body strength"],
      validationMustPass: true,
    },
  },
  {
    id: "advanced_trainee",
    label: "Advanced trainee",
    narrative: "Experienced lifter on muscle-gain phase with higher volume tolerance.",
    userData: {
      age: 32,
      gender: "male",
      heightCm: 183,
      weightKg: 88,
      goal: "muscle",
      activityLevel: "active",
      experienceLevel: "advanced",
      primarySportId: "bodybuilding",
      trainingDays: TRAINING_MWF,
      caloriesEaten: 2600,
      proteinEatenG: 150,
      waterLitersConsumed: 3,
      sleepHours: 8,
      adherenceScore: 85,
      consecutiveTrainingDays: 1,
    },
    clock: { hour: 11, dayOfWeek: 1 },
    expectations: {
      rationale: "Advanced trainees on training days get split-style sessions, not beginner templates.",
      shouldPrioritize: ["complete_workout", "steady_progress", "protein_focus"],
      trainingMustNotInclude: ["Full-body basics"],
      validationMustPass: true,
    },
  },
  {
    id: "office_worker",
    label: "Office worker",
    narrative: "Sedentary desk job with low PAL — lower TDEE estimate.",
    userData: {
      age: 45,
      gender: "female",
      heightCm: 163,
      weightKg: 68,
      goal: "lose",
      activityLevel: "sedentary",
      experienceLevel: "beginner",
      primarySportId: "bodybuilding",
      trainingDays: [2, 4],
      caloriesEaten: 800,
      proteinEatenG: 55,
      waterLitersConsumed: 1.1,
      sleepHours: 6.5,
      adherenceScore: 55,
    },
    clock: { hour: 14, dayOfWeek: 2 },
    expectations: {
      rationale: "Sedentary PAL lowers TDEE; nutrition or hydration gaps should surface before hard training push.",
      shouldPrioritize: [
        "hydration_focus",
        "protein_low",
        "protein_focus",
        "steady_progress",
        "movement_day",
        "calorie_balance",
      ],
      mustNotRecommend: ["complete_workout"],
      metabolism: { goal: "fat_loss", maxActivityMultiplier: 1.25 },
      validationMustPass: true,
    },
  },
  {
    id: "active_worker",
    label: "Active worker",
    narrative: "Physically active job with higher daily energy needs.",
    userData: {
      age: 38,
      gender: "male",
      heightCm: 178,
      weightKg: 80,
      goal: "fit",
      activityLevel: "active",
      experienceLevel: "intermediate",
      primarySportId: "bodybuilding",
      trainingDays: TRAINING_MWF,
      caloriesEaten: 2200,
      proteinEatenG: 110,
      waterLitersConsumed: 2.8,
      sleepHours: 7,
      adherenceScore: 78,
    },
    clock: { hour: 12, dayOfWeek: 4 },
    expectations: {
      rationale: "Active PAL raises TDEE relative to sedentary profiles with same body size.",
      shouldPrioritize: ["steady_progress", "movement_day", "complete_workout"],
      metabolism: { minActivityMultiplier: 1.7 },
      validationMustPass: true,
    },
  },
  {
    id: "low_recovery_user",
    label: "Low recovery user",
    narrative: "Stacked training days and short sleep — readiness is compromised.",
    userData: {
      age: 29,
      gender: "male",
      heightCm: 177,
      weightKg: 76,
      goal: "fit",
      activityLevel: "moderate",
      experienceLevel: "intermediate",
      primarySportId: "bodybuilding",
      trainingDays: TRAINING_MWF,
      sleepHours: 5,
      consecutiveTrainingDays: 4,
      trainedYesterday: true,
      caloriesEaten: 1800,
      proteinEatenG: 100,
      waterLitersConsumed: 2,
      adherenceScore: 70,
    },
    clock: { hour: 11, dayOfWeek: 3 },
    expectations: {
      rationale: "Four consecutive training days with poor sleep triggers overtraining/rest priority, not hard sessions.",
      shouldPrioritize: ["overtraining_risk", "recovery_rest"],
      mustNotRecommend: ["complete_workout"],
      recoveryLevelIn: ["overtraining_risk", "low_recovery"],
      validationMustPass: true,
    },
  },
  {
    id: "high_training_load_user",
    label: "High training load user",
    narrative: "Hard long run today — elevated energy demand and recovery cost.",
    userData: {
      age: 31,
      gender: "female",
      heightCm: 170,
      weightKg: 64,
      goal: "fit",
      activityLevel: "moderate",
      experienceLevel: "intermediate",
      primarySportId: "bodybuilding",
      trainingDays: TRAINING_MWF,
      sleepHours: 7,
      waterLitersConsumed: 0.9,
      proteinEatenG: 45,
      caloriesEaten: 1200,
      activityMinutesToday: 65,
      activityCountToday: 1,
      lastActivityId: "running",
      lastActivityIntensity: "hard",
      adherenceScore: 75,
    },
    clock: { hour: 17, dayOfWeek: 4 },
    activityLogs: [activityLog("running", 65, "hard", 10.2, 680)],
    expectations: {
      rationale: "Post-activity hydration/protein should outrank a generic workout completion push.",
      shouldPrioritize: [
        "post_activity_hydration",
        "post_activity_protein",
        "post_activity_fuel",
        "hydration_focus",
        "recovery_rest",
      ],
      mustNotRecommend: ["complete_workout"],
      validationMustPass: true,
    },
  },
  {
    id: "poor_hydration_user",
    label: "Poor hydration user",
    narrative: "Well below daily fluid target in the afternoon.",
    userData: {
      age: 27,
      gender: "female",
      heightCm: 166,
      weightKg: 60,
      goal: "fit",
      activityLevel: "moderate",
      experienceLevel: "intermediate",
      primarySportId: "bodybuilding",
      trainingDays: TRAINING_MWF,
      waterLitersConsumed: 0.4,
      proteinEatenG: 55,
      caloriesEaten: 1100,
      sleepHours: 7,
      adherenceScore: 65,
    },
    clock: { hour: 14, dayOfWeek: 2 },
    expectations: {
      rationale: "Low hydration progress after mid-morning should elevate hydration-focused daily action.",
      shouldPrioritize: ["hydration_critical", "hydration_focus", "post_activity_hydration"],
      mustNotRecommend: ["complete_workout"],
      nutritionFocusIn: ["hydration"],
      validationMustPass: true,
    },
  },
  {
    id: "low_protein_user",
    label: "Low protein user (muscle gain)",
    narrative: "Muscle-gain goal but protein intake far below target in the afternoon.",
    userData: {
      age: 26,
      gender: "male",
      heightCm: 181,
      weightKg: 84,
      goal: "muscle",
      activityLevel: "moderate",
      experienceLevel: "intermediate",
      primarySportId: "bodybuilding",
      trainingDays: TRAINING_MWF,
      proteinEatenG: 28,
      caloriesEaten: 1600,
      waterLitersConsumed: 2,
      sleepHours: 7.5,
      consecutiveTrainingDays: 1,
      adherenceScore: 70,
    },
    clock: { hour: 15, dayOfWeek: 2 },
    expectations: {
      rationale: "Low afternoon protein on a muscle-gain goal should raise protein priority.",
      shouldPrioritize: ["protein_low", "protein_focus"],
      nutritionFocusIn: ["protein"],
      metabolism: { goal: "muscle_gain", minProteinPerKg: 1.9 },
      validationMustPass: true,
    },
  },
  {
    id: "calorie_deficit_low_energy",
    label: "Large deficit + low energy",
    narrative: "Very low intake and poor sleep — recovery before aggressive training.",
    userData: {
      age: 36,
      gender: "female",
      heightCm: 167,
      weightKg: 74,
      goal: "lose",
      activityLevel: "light",
      experienceLevel: "intermediate",
      primarySportId: "bodybuilding",
      trainingDays: TRAINING_MWF,
      caloriesEaten: 450,
      proteinEatenG: 40,
      waterLitersConsumed: 1.2,
      sleepHours: 5.5,
      consecutiveTrainingDays: 2,
      trainedYesterday: true,
      adherenceScore: 50,
    },
    clock: { hour: 16, dayOfWeek: 3 },
    expectations: {
      rationale: "Low recovery and large calorie gap should not prioritize completing a hard workout.",
      shouldPrioritize: ["recovery_rest", "overtraining_risk", "calorie_off_track", "hydration_focus"],
      mustNotRecommend: ["complete_workout"],
      recoveryLevelIn: ["low_recovery", "overtraining_risk", "neutral"],
      validationMustPass: true,
    },
  },
  {
    id: "new_user_missing_data",
    label: "New user (missing data)",
    narrative: "Minimal profile — Brain should use defaults and lower confidence, not pretend certainty.",
    userData: {
      age: 30,
      gender: "male",
      waterLitersConsumed: 2,
      adherenceScore: 40,
    },
    clock: { hour: 12, dayOfWeek: 1 },
    expectations: {
      rationale:
        "Sparse signals trigger Collect phase — nutrition unknown at midday, hydration logged so intake is not assumed zero.",
      shouldPrioritize: ["collect_nutrition_evidence", "steady_progress", "movement_day", "collect_primary_sport_evidence"],
      maxConfidence: "low",
      validationMustPass: true,
      allowLowConfidence: true,
    },
  },
];

export function getGoldenPersona(id: string): GoldenPersona | undefined {
  return GOLDEN_PERSONAS.find((p) => p.id === id);
}
